### ISSUE TITLE
osc ci crashes with git-based checkout

### ISSUE THREAD

**Issue by mcepl** [openSUSE/osc#1050]
**Describe the bug**
When trying to commit changed python-orangebox to OBS I get this traceback:
```
stitny~/b/t/d/python-orangebox (main)$ osc ci --verbose
Traceback (most recent call last):
  File "/home/matej/.bin/osc", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/home/matej/archiv/knihovna/repos/osc/osc-wrapper.py", line 45, in <module>
    r = babysitter.run(osccli)
  File "/home/matej/archiv/knihovna/repos/osc/osc/babysitter.py", line 67, in run
    return prg.main(argv)
  File "/home/matej/archiv/knihovna/repos/osc/osc/cmdln.py", line 349, in main
    return self.cmd(args)
  File "/home/matej/archiv/knihovna/repos/osc/osc/cmdln.py", line 372, in cmd
    retval = self.onecmd(argv)
  File "/home/matej/archiv/knihovna/repos/osc/osc/cmdln.py", line 506, in onecmd
    return self._dispatch_cmd(handler, argv)
  File "/home/matej/archiv/knihovna/repos/osc/osc/cmdln.py", line 1237, in _dispatch_cmd
    return handler(argv[0], opts, *args)
  File "/home/matej/archiv/knihovna/repos/osc/osc/commandline.py", line 4984, in do_commit
    self._commit(subcmd, opts, args)
  File "/home/matej/archiv/knihovna/repos/osc/osc/commandline.py", line 5081, in _commit
    msg = get_commit_msg(prj.absdir, pac_objs[prj_path])
  File "/home/matej/archiv/knihovna/repos/osc/osc/core.py", line 7540, in get_commit_msg
    states = sorted(p.get_status(False, ' ', '?'), key=cmp_to_key(compare))
  File "/home/matej/archiv/knihovna/repos/osc/osc/core.py", line 1923, in get_status
    [i for i in self.filenamelist_unvers if not os.path.isdir(os.path.join(self.absdir, i))]
AttributeError: 'Package' object has no attribute 'filenamelist_unvers'
stitny~/b/t/d/python-orangebox (main)$ 
```

**Versions**
- Operating system: `(source /etc/os-release; echo $PRETTY_NAME)` openSUSE Tumbleweed
- Packages: `rpm -q osc` not package, `main` branch of https://github.com/openSUSE/osc/commit/715a30f3f35c32b67c934b47d0e98fd9e89a9c2a

**To Reproduce**
1. osc co devel:languages:python python-orangebox
2. cd devel:languages:python/python-orangebox
3. osc build  # everything works fine
4. edit, edit, edit
5. osc vc
6. git commit -a -v
7. git push  git@github.com:mcepl/git-example-3.git main
8. create PR https://github.com/adrianschroeter/git-example-3/pull/1
9. osc ci
10. See backtrace above

**Expected behavior**
opening `$EDITOR` to edit commit message, or perhaps even commit with the default message

**Comment by adrianschroeter** [comment]
On Freitag, 3. Juni 2022, 17:09:40 CEST Matěj Cepl wrote:
...
> **Expected behavior**
> opening `$EDITOR` to edit commit message, or perhaps even commit with the default message

It should not crash, but commit/pushing needs to be done via git tooling atm. 


-- 

Adrian Schroeter ***@***.***>
Build Infrastructure Project Manager

SUSE Software Solutions Germany GmbH, Maxfeldstr. 5, 90409 Nürnberg, Germany
(HRB 36809, AG Nürnberg) Geschäftsführer: Ivo Totev

**Comment by mcepl** [comment]
> **Expected behavior** opening `$EDITOR` to edit commit message, or perhaps even commit with the default message
> It should not crash, but commit/pushing needs to be done via git tooling atm.

??? How can I commit to OBS via git?

**Comment by adrianschroeter** [comment]
On Freitag, 3. Juni 2022, 19:06:34 CEST Matěj Cepl wrote:
> > **Expected behavior** opening `$EDITOR` to edit commit message, or perhaps even commit with the default message
> > It should not crash, but commit/pushing needs to be done via git tooling atm.
> 
> ??? How can I commit to OBS via git?

you can not commit to OBS in that sense at all.

You can commit to some git repository and OBS is following.

The scmsync approach is the approach to offload the 
submission workflow from OBS to some github/gitab/pagure/gerrit/... 
instance.

-- 

Adrian Schroeter ***@***.***>
Build Infrastructure Project Manager

SUSE Software Solutions Germany GmbH, Maxfeldstr. 5, 90409 Nürnberg, Germany
(HRB 36809, AG Nürnberg) Geschäftsführer: Ivo Totev

**Comment by mcepl** [comment]
> you can not commit to OBS in that sense at all. You can commit to some git repository and OBS is following. The scmsync approach is the approach to offload the submission workflow from OBS to some github/gitab/pagure/gerrit/... instance.

So, I cannot get my changes in the current situation to OBS in other way that by removing your git-based package from d:l:p, recreating it as a normal package, and submit that?

**Comment by adrianschroeter** [comment]
On Samstag, 4. Juni 2022, 11:37:48 CEST Matěj Cepl wrote:
> > you can not commit to OBS in that sense at all. You can commit to some git repository and OBS is following. The scmsync approach is the approach to offload the submission workflow from OBS to some github/gitab/pagure/gerrit/... instance.
> 
> So, I cannot get my changes in the current situation to OBS in other way that by removing your git-based package from d:l:p, recreating it as a normal package, and submit that?

You can create a pull request to the git repository or I can grant you write
permissions there.

I see that you found the git repo and created a pull request there already :)

As said before, the approach is have git as first place citizen and OBS 
should just follow in the long term.

For now we have only this mixed model to avoid breakage of the tooling around
the distribution.

I will take care that osc will come up with a proper message though.

And we should maybe discuss a better place for the git repo instead of
my personal area... but let's do that via chat or mail.

good morning
adrian

-- 

Adrian Schroeter ***@***.***>
Build Infrastructure Project Manager

SUSE Software Solutions Germany GmbH, Maxfeldstr. 5, 90409 Nürnberg, Germany
(HRB 36809, AG Nürnberg) Geschäftsführer: Ivo Totev
