### ISSUE TITLE
bug: osc called without subcommand results in `index out of range`

### ISSUE THREAD

**Issue by m-ildefons** [openSUSE/osc#1057]
When executing `osc` with just global options (just an API endpoint specifically), `osc` terminates with an uncaught `IndexError: list index out of range`

**Versions**
```
│ ~/qam │► cat /etc/os-release 
NAME="openSUSE Leap"
VERSION="15.4 Beta"
ID="opensuse-leap"
ID_LIKE="suse opensuse"
VERSION_ID="15.4"
PRETTY_NAME="openSUSE Leap 15.4 Beta"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:opensuse:leap:15.4"
BUG_REPORT_URL="https://bugs.opensuse.org"
HOME_URL="https://www.opensuse.org/"
DOCUMENTATION_URL="https://en.opensuse.org/Portal:Leap"
LOGO="distributor-logo-Leap"
│ ~/qam │► uname -a
Linux GLaDOS.fritz.box 5.14.21-150400.19-default #1 SMP PREEMPT_DYNAMIC Wed Apr 20 08:32:52 UTC 2022 (d6fb753) x86_64 x86_64 x86_64 GNU/Linux
│ ~/qam │► sudo rpm -q osc
[sudo] password for root: 
osc-0.178.0-150400.328.1.noarch
```

**To Reproduce**
### What I did:
```bash
│ ~/qam │► osc -A https://build.suse.de
```

### What I got
```bash
│ ~/qam │► osc -A https://build.suse.de
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/osc/babysitter.py", line 67, in run
    return prg.main(argv)
  File "/usr/lib/python3.6/site-packages/osc/cmdln.py", line 341, in main
    self.postoptparse()
  File "/usr/lib/python3.6/site-packages/osc/commandline.py", line 137, in postoptparse
    if self._get_canonical_cmd_name(self.args[0]) == "help":
IndexError: list index out of range
> /usr/lib/python3.6/site-packages/osc/commandline.py(137)postoptparse()
-> if self._get_canonical_cmd_name(self.args[0]) == "help":
(Pdb)
```

**Expected behavior**
Either a short error explaining the user mistake:
```bash
│ ~/qam │► osc -A https://build.suse.de
osc: no subcommand specified
│ ~/qam │ 1 ►
```
or being dropped into an osc shell where subcommands can be executed:
```bash
│ ~/qam │► osc -A https://build.suse.de
osc (https://build.suse.de) >
```
or just show the help page.

**Screenshots, console outputs**
```bash
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/osc/babysitter.py", line 67, in run
    return prg.main(argv)
  File "/usr/lib/python3.6/site-packages/osc/cmdln.py", line 341, in main
    self.postoptparse()
  File "/usr/lib/python3.6/site-packages/osc/commandline.py", line 137, in postoptparse
    if self._get_canonical_cmd_name(self.args[0]) == "help":
IndexError: list index out of range
> /usr/lib/python3.6/site-packages/osc/commandline.py(137)postoptparse()
-> if self._get_canonical_cmd_name(self.args[0]) == "help":
(Pdb)
```

**Comment by m-ildefons** [comment]
Fixed by f2474fa7f02fa2551c35154810cdc54a15df41d8  in 0.179
