### ISSUE TITLE
osc build fails in scmsynced checkout

### ISSUE THREAD

**Issue by coolo** [openSUSE/osc#1080]
**Describe the bug**
I try to do a local build of home:coolo:alp/aaa_base it crashes:
```
Building aaa_base.spec for standard/x86_64
Traceback (most recent call last):
  File "/home/coolo/prod/osc/osc-wrapper.py", line 45, in <module>
    r = babysitter.run(osccli)
  File "/home/coolo/prod/osc/osc/babysitter.py", line 67, in run
    return prg.main(argv)
  File "/home/coolo/prod/osc/osc/cmdln.py", line 349, in main
    return self.cmd(args)
  File "/home/coolo/prod/osc/osc/cmdln.py", line 372, in cmd
    retval = self.onecmd(argv)
  File "/home/coolo/prod/osc/osc/cmdln.py", line 506, in onecmd
    return self._dispatch_cmd(handler, argv)
  File "/home/coolo/prod/osc/osc/cmdln.py", line 1237, in _dispatch_cmd
    return handler(argv[0], opts, *args)
  File "/home/coolo/prod/osc/osc/commandline.py", line 6793, in do_build
    return osc.build.main(self.get_api_url(), opts, args)
  File "/home/coolo/prod/osc/osc/build.py", line 852, in main
    r = p.run_source_services(verbose=True)
  File "/home/coolo/prod/osc/osc/core.py", line 2487, in run_source_services
    if self.filenamelist.count('_service') or self.filenamelist_unvers.count('_service'):
AttributeError: 'Package' object has no attribute 'filenamelist_unvers'
```

**Versions**
I'm running today's master (4deaf2b9c39e579c56b14b186f778e810f273bd7) on Tumbleweed
- Operating system: `(source /etc/os-release; echo $PRETTY_NAME)`
- Packages: `rpm -q osc`

**To Reproduce**
- osc co home:coolo:alp aaa_base
- cd aaa_base
- osc build

**Comment by coolo** [comment]
workaround: build with `--no-service`
