### ISSUE TITLE
unattenteded passwordless auth with ssh fails

### ISSUE THREAD

**Issue by olafhering** [openSUSE/osc#1081]
The failure to use a properly typed language bites again.

````
+ export OSC_CONFIG=/path/to/oscrc-for-separate-user
+ OSC_CONFIG=/path/to/oscrc-for-separate-user
+ exec /usr/bin/osc --config=/path/to/oscrc-for-separate-user -A https://api.suse.de ls Devel
Traceback (most recent call last):
  File "/usr/bin/osc", line 45, in <module>
    r = babysitter.run(osccli)
  File "/usr/lib/python3.6/site-packages/osc/babysitter.py", line 67, in run
    return prg.main(argv)
  File "/usr/lib/python3.6/site-packages/osc/cmdln.py", line 341, in main
    self.postoptparse()
  File "/usr/lib/python3.6/site-packages/osc/commandline.py", line 151, in postoptparse
    override_verbose = self.options.verbose)
  File "/usr/lib/python3.6/site-packages/osc/conf.py", line 1104, in get_config
    password = creds_mgr.get_password(url, user, defer=True)
  File "/usr/lib/python3.6/site-packages/osc/credentials.py", line 156, in get_password
    return self.decode_password(passwd)
  File "/usr/lib/python3.6/site-packages/osc/credentials.py", line 169, in decode_password
    compressed_pw = base64.b64decode(password.encode("ascii"))
AttributeError: 'NoneType' object has no attribute 'encode'
````

What I need to achieve is a setup which works without any password every time.
How do i achieve that?
````
set -ex
read td < <(mktemp --directory --tmpdir=/dev/shm .XXX)
trap "rm -rfv ${td}" EXIT
private_key=$1
test -f "${private_key}"
pushd "${td}"
cp -avit . "${private_key}" "${private_key}.pub"
read private_key < <(readlink -f "${private_key##*/}")
eval $(ssh-agent)
ssh-add "${private_key}"
ssh-add -l
touch separate-oscrc
read oscrc < <(readlink -f separate-oscrc)
tee "${oscrc}" <<_EOF_
[general]
apiurl = https://api.suse.de
plaintext_passwd=0
[https://api.suse.de]
user=separate-user
credentials_mgr_class=osc.credentials.ObfuscatedConfigFileCredentialsManager
sshkey=${private_key}
_EOF_
exec env OSC_CONFIG="${oscrc}" /usr/bin/osc --config="${oscrc}" --no-keyring --no-gnome-keyring -A https://api.suse.de ls Devel
````

**Comment by dmach** [comment]
@olafhering what if you add `pass=` to the `[https://api.suse.de]` section?
For historical reasons, password was never supposed to be unset (`None`).
It is definitely something that deserves a fix.

**Comment by olafhering** [comment]
Thanks, an empty `pass=` helps indeed.

**Comment by dmach** [comment]
I've created PR #1083 that fixes the crash.
If this situation happens, osc asks for a password, you leave it empty, hit enter and the following will be stored in the config:
```
user=<USER>
credentials_mgr_class=<MGR>
pass=
or
pass=QlpoORdyRThQkAAAAAA= (which is obfuscated equivalent of an empty password)
```

and osc will use ssh auth instead of the password.

This is probably the best I can do now without breaking osc internals too much.
