### ISSUE TITLE
bug: KeyError with `osc qam my` on new maintenance incidents

### ISSUE THREAD

**Issue by m-ildefons** [openSUSE/osc#1118]
The format of maintenance incident logs has changed and the metadata section was factored out into it's own file (metadata.json). This breaks osc since it expects the metadata to reside inside the log file:
```
$ osc qam assign -G qam-ses SUSE:Maintenance:25512:277811
[...]
$ osc qam my
Traceback (most recent call last):
  File "/usr/bin/osc", line 45, in <module>
    r = babysitter.run(osccli)
  File "/usr/lib/python3.6/site-packages/osc/babysitter.py", line 67, in run
    return prg.main(argv)
  File "/usr/lib/python3.6/site-packages/osc/cmdln.py", line 349, in main
    return self.cmd(args)
  File "/usr/lib/python3.6/site-packages/osc/cmdln.py", line 372, in cmd
    retval = self.onecmd(argv)
  File "/usr/lib/python3.6/site-packages/osc/cmdln.py", line 506, in onecmd
    return self._dispatch_cmd(handler, argv)
  File "/usr/lib/python3.6/site-packages/osc/cmdln.py", line 1237, in _dispatch_cmd
    return handler(argv[0], opts, *args)
  File "/usr/lib/osc-plugins/qam.py", line 615, in do_qam
    ret = interp.onecmd(sys.argv[index + 1:])
  File "/usr/lib/python3.6/site-packages/osc/cmdln.py", line 506, in onecmd
    return self._dispatch_cmd(handler, argv)
  File "/usr/lib/python3.6/site-packages/osc/cmdln.py", line 1237, in _dispatch_cmd
    return handler(argv[0], opts, *args)
  File "/usr/lib/osc-plugins/qam.py", line 319, in do_my
    self.do_assigned(subcmd, opts)
  File "/usr/lib/osc-plugins/qam.py", line 288, in do_assigned
    self._list_requests(action, opts.tabular, keys)
  File "/usr/lib/osc-plugins/qam.py", line 181, in _list_requests
    listdata = action()
  File "/usr/lib/python3.6/site-packages/oscqam/actions.py", line 76, in __call__
    return self.action(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/oscqam/actions.py", line 187, in action
    self.group_sort_reports()
  File "/usr/lib/python3.6/site-packages/oscqam/actions.py", line 174, in group_sort_reports
    lambda l: l.request.incident_priority,
  File "/usr/lib/python3.6/site-packages/oscqam/actions.py", line 46, in multi_level_sort
    return [s for sub in subsorts for s in sub]
  File "/usr/lib/python3.6/site-packages/oscqam/actions.py", line 46, in <listcomp>
    return [s for sub in subsorts for s in sub]
  File "/usr/lib/python3.6/site-packages/oscqam/actions.py", line 45, in <genexpr>
    subsorts = (multi_level_sort(list(value), criteria[:-1]) for _, value in grouped)
  File "/usr/lib/python3.6/site-packages/oscqam/actions.py", line 43, in multi_level_sort
    xss = sorted(xs, key=extractor)
  File "/usr/lib/python3.6/site-packages/oscqam/actions.py", line 173, in <lambda>
    lambda l: l.template.log_entries["Rating"],
KeyError: 'Rating'
```
**Versions**
- Operating system: openSUSE Leap 15.4 Beta
- Packages: osc-0.179.0-150400.330.1.noarch

**To Reproduce**
see above

**Expected behavior**
Expected behavior is that `osc` just lists all review requests or maintenance incidents assigned to myself.

**Comment by m-ildefons** [comment]
Nevermind, the error came from an outdated `osc-plugin-qam` package.
