### ISSUE TITLE
osc diff crashes on SLE12

### ISSUE THREAD

**Issue by hramrach** [openSUSE/osc#1122]
**Describe the bug**
When there are source changes osc diff crashes on SLE12

**Versions**
- Operating system: SUSE Linux Enterprise Server 12 SP5
- Packages: osc-0.181.0-kt.345.2.x86_64

**To Reproduce**

1. checkout a package
2. change to the package directory, edit a file
3. run `osc diff`

**Expected behavior**
A diff is shown.

**Screenshots, console outputs**
```
msuchanek@appolonius:~/SUSE:SLE-15-SP5:GA/iniparser> osc diff
Traceback (most recent call last):
  File "/usr/bin/osc", line 47, in <module>
    r = babysitter.run(osccli)
  File "/usr/lib/python3.4/site-packages/osc/babysitter.py", line 67, in run
    return prg.main(argv)
  File "/usr/lib/python3.4/site-packages/osc/cmdln.py", line 349, in main
    return self.cmd(args)
  File "/usr/lib/python3.4/site-packages/osc/cmdln.py", line 372, in cmd
    retval = self.onecmd(argv)
  File "/usr/lib/python3.4/site-packages/osc/cmdln.py", line 506, in onecmd
    return self._dispatch_cmd(handler, argv)
  File "/usr/lib/python3.4/site-packages/osc/cmdln.py", line 1237, in _dispatch_cmd
    return handler(argv[0], opts, *args)
  File "/usr/lib/python3.4/site-packages/osc/commandline.py", line 4040, in do_diff
    for i in pac.get_diff(rev1):
  File "/usr/lib/python3.4/site-packages/osc/core.py", line 2111, in get_diff
    yield [diff_hdr % f.name.encode()]
TypeError: unsupported operand type(s) for %: 'bytes' and 'bytes'
```

**Additional context**
Self-built package - build of upstream osc crashes on SLE12

**Comment by hramrach** [comment]
This is specific to python 3.4

On systems that have python 3 this old it is advisable to use python 2 instead.
