### ISSUE TITLE
Cannot run tests on SLE12

### ISSUE THREAD

**Issue by hramrach** [openSUSE/osc#1123]
**Describe the bug**
tests crash on SLE12

**Versions**
- Operating system: SUSE Linux Enterprise Server 12 SP5
- Packages: osc-0.181.0-kt.345.2.x86_64

**To Reproduce**
1. get osc sources
2. run tests as described in README

**Expected behavior**
test results

**Screenshots, console outputs**
```
msuchanek@appolonius:~/openSUSE.org:Kernel:tools/osc/osc-0.181.0> ./setup.py test
running test
running egg_info
creating osc.egg-info
writing osc.egg-info/PKG-INFO
writing top-level names to osc.egg-info/top_level.txt
writing requirements to osc.egg-info/requires.txt
writing dependency_links to osc.egg-info/dependency_links.txt
writing manifest file 'osc.egg-info/SOURCES.txt'
reading manifest file 'osc.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching 'README'
writing manifest file 'osc.egg-info/SOURCES.txt'
running build_ext
Traceback (most recent call last):
  File "./setup.py", line 132, in <module>
    test_suite="tests",
  File "/usr/lib/python3.4/site-packages/setuptools/__init__.py", line 143, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib64/python3.4/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib64/python3.4/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/lib64/python3.4/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/lib/python3.4/site-packages/setuptools/command/test.py", line 228, in run
    self.run_tests()
  File "/usr/lib/python3.4/site-packages/setuptools/command/test.py", line 250, in run_tests
    exit=False,
  File "/usr/lib64/python3.4/unittest/main.py", line 92, in __init__
    self.parseArgs(argv)
  File "/usr/lib64/python3.4/unittest/main.py", line 139, in parseArgs
    self.createTests()
  File "/usr/lib64/python3.4/unittest/main.py", line 146, in createTests
    self.module)
  File "/usr/lib64/python3.4/unittest/loader.py", line 157, in loadTestsFromNames
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/usr/lib64/python3.4/unittest/loader.py", line 157, in <listcomp>
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/usr/lib64/python3.4/unittest/loader.py", line 128, in loadTestsFromName
    return self.loadTestsFromModule(obj)
  File "/usr/lib/python3.4/site-packages/setuptools/command/test.py", line 54, in loadTestsFromModule
    tests.append(self.loadTestsFromName(submodule))
  File "/usr/lib64/python3.4/unittest/loader.py", line 128, in loadTestsFromName
    return self.loadTestsFromModule(obj)
  File "/usr/lib/python3.4/site-packages/setuptools/command/test.py", line 54, in loadTestsFromModule
    tests.append(self.loadTestsFromName(submodule))
  File "/usr/lib64/python3.4/unittest/loader.py", line 125, in loadTestsFromName
    parent, obj = obj, getattr(obj, part)
AttributeError: 'module' object has no attribute 'checker'
```

**Comment by dmach** [comment]
The tests work fine when you use the code from `0.x-maint` branch and run `python2 -m unittest`
