### ISSUE TITLE
Error when trying to set up credentials with osc when password includes a percentage sign

### ISSUE THREAD

**Issue by mlegner** [openSUSE/osc#1155]
**Describe the bug**

During the initial launch of `osc`, it tries to set up the credentials. This fails with a `ValueError: invalid interpolation syntax` if the password includes a percentage sign (`%`). It also prints out the password in clear when printing the error trace.

**Versions**

- Operating system: Ubuntu 22.04.1 LTS
- Packages: 
  - osc: 0.169.1
  - Python: 3.10.5

**To Reproduce**

1. Remove `~/.config/osc/oscrc`
2. Run `osc`
3. Enter any username and a password including a `%`
4. Select option `5`

**Expected behavior**

Should properly handle passwords with `%` (as they are generally allowed with OBS).

In particular, it should also *not print out* the password.

**Screenshots, console outputs**

Output when using password `%`:
```text
Your user account / password are not configured yet.
You will be asked for them below, and they will be stored in
/home/<user>/.config/osc/oscrc for future use.

Creating osc configuration file /home/<user>/.config/osc/oscrc ...
Username: x     
Password: 
1) SecretService Keyring (Backend provided by python-keyring)
2) chainer ChainerBackend (Backend provided by python-keyring)
3) fail Keyring (Backend provided by python-keyring)
4) libsecret Keyring (Backend provided by python-keyring)
5) Config file credentials manager (Store the credentials in the config file (plain text))
6) Obfuscated Config file credentials manager (Store the credentials in the config file (obfuscated))
7) Transient password store (Do not store the password and always ask for the password)
Select credentials manager: 5
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/osc/commandline.py", line 138, in postoptparse
    conf.get_config(override_conffile = self.options.conffile,
  File "/usr/lib/python3/dist-packages/osc/conf.py", line 837, in get_config
    raise oscerr.NoConfigfile(conffile, \
osc.oscerr.NoConfigfile

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/osc", line 41, in <module>
    r = babysitter.run(osccli)
  File "/usr/lib/python3/dist-packages/osc/babysitter.py", line 64, in run
    return prg.main(argv)
  File "/usr/lib/python3/dist-packages/osc/cmdln.py", line 339, in main
    self.postoptparse()
  File "/usr/lib/python3/dist-packages/osc/commandline.py", line 154, in postoptparse
    conf.interactive_config_setup(e.file, apiurl)
  File "/usr/lib/python3/dist-packages/osc/conf.py", line 1019, in interactive_config_setup
    write_initial_config(conffile, config, creds_mgr_descriptor=creds_mgr_descr)
  File "/usr/lib/python3/dist-packages/osc/conf.py", line 767, in write_initial_config
    creds_mgr.set_password(config['apiurl'], config['user'], config['pass'])
  File "/usr/lib/python3/dist-packages/osc/credentials.py", line 71, in set_password
    self._cp.set(url, 'pass', password)
  File "/usr/lib/python3.10/configparser.py", line 1205, in set
    super().set(section, option, value)
  File "/usr/lib/python3.10/configparser.py", line 895, in set
    value = self._interpolation.before_set(self, section, option,
  File "/usr/lib/python3.10/configparser.py", line 402, in before_set
    raise ValueError("invalid interpolation syntax in %r at "
ValueError: invalid interpolation syntax in '%' at position 0
```

**Comment by dmach** [comment]
Thanks for reporting this.
The problem is that config interpolation is enabled in python's config parser by default and '%' is a control character.
I've disabled interpolation in #1157.
