### ISSUE TITLE
osc fails to run with git master

### ISSUE THREAD

**Issue by Firstyear** [openSUSE/osc#1162]
```
 osc build --clean
Building cargo-audit.spec for openSUSE_Tumbleweed/x86_64
Traceback (most recent call last):
  File "/home/william/development/osc/osc-wrapper.py", line 9, in <module>
    osc.babysitter.main()
  File "/home/886b45ce-98b2-4d79-9069-c9ff25bc0232/development/osc/osc/babysitter.py", line 208, in main
    sys.exit(run(commandline.Osc()))
  File "/home/886b45ce-98b2-4d79-9069-c9ff25bc0232/development/osc/osc/babysitter.py", line 56, in run
    return prg.main(argv)
  File "/home/886b45ce-98b2-4d79-9069-c9ff25bc0232/development/osc/osc/cmdln.py", line 262, in main
    cmd(self.options.command, self.options, *self.args)
  File "/home/886b45ce-98b2-4d79-9069-c9ff25bc0232/development/osc/osc/commandline.py", line 6538, in do_build
    return osc_build.main(self.get_api_url(), opts, args)
  File "/home/886b45ce-98b2-4d79-9069-c9ff25bc0232/development/osc/osc/build.py", line 796, in main
    build_root = config['api_host_options'][apiurl].get('build-root', build_root)
KeyError: 'api_host_options'
```

This appears to be because "config" doesn't have this key. A dump of the config dict at this point is:

```
DEBUG: {'apiurl': 'https://api.opensuse.org', 'user': None, 'pass': None, 'passx': None, 'sshkey': None, 'packagecachedir': '/var/tmp/osbuild-packagecache', 'su-wrapper': 'sudo', 'build-cmd': '/usr/bin/build', 'build-type': '', 'build-root': '/var/tmp/build-root/%(repo)s-%(arch)s', 'build-uid': '', 'build-device': '', 'build-memory': '', 'build-shell-after-fail': False, 'build-swap': '', 'build-vmdisk-rootsize': '', 'build-vmdisk-swapsize': '', 'build-vmdisk-filesystem': '', 'build-vm-user': '', 'build-kernel': '', 'build-initrd': '', 'download-assets-cmd': '/usr/lib/build/download_assets', 'build-jobs': 4, 'builtin_signature_check': True, 'icecream': '0', 'ccache': False, 'sccache': False, 'sccache_uri': '', 'buildlog_strip_time': False, 'debug': False, 'http_debug': False, 'http_full_debug': False, 'http_retries': '3', 'verbose': '0', 'no_preinstallimage': False, 'traceback': False, 'post_mortem': False, 'use_keyring': False, 'cookiejar': '~/.osc_cookiejar', 'no_verify': False, 'do_package_tracking': True, 'extra-pkgs': '', 'build_repository': 'openSUSE_Factory', 'getpac_default_project': 'openSUSE:Factory', 'checkout_no_colon': False, 'project_separator': ':', 'checkout_rooted': False, 'exclude_glob': '.osc CVS .svn .* _linkerror *~ #*# *.orig *.bak *.changes.vctmp.*', 'print_web_links': False, 'request_list_days': 0, 'check_filelist': True, 'check_for_request_on_action': True, 'submitrequest_on_accept_action': '', 'request_show_interactive': False, 'request_show_source_buildstatus': False, 'review_inherit_group': False, 'submitrequest_accepted_template': '', 'submitrequest_declined_template': '', 'linkcontrol': False, 'include_request_from_project': True, 'local_service_run': True, 'maintained_attribute': 'OBS:Maintained', 'maintenance_attribute': 'OBS:MaintenanceProject', 'maintained_update_project_attribute': 'OBS:UpdateProject', 'show_download_progress': False, 'vc-cmd': '/usr/lib/build/vc', 'status_mtime_heuristic': False}
```

No other patches involved, this is direct from git master on fully updated tumbleweed

**Comment by Firstyear** [comment]
git bisect shows the issue is introduced in:

```
b511be20ff17ffe78d29ac90f0cec6d6e8fb2532 is the first bad commit
commit b511be20ff17ffe78d29ac90f0cec6d6e8fb2532
Author: Daniel Mach <daniel.mach@suse.com>
Date:   Fri Sep 9 11:46:28 2022 +0200

    Always import at the toplevel

 osc/build.py                 | 10 +++----
 osc/commandline.py           | 67 +++++++++++++++++---------------------------
 osc/conf.py                  |  1 -
 osc/connection.py            |  6 ----
 osc/core.py                  | 57 +++++++------------------------------
 osc/fetch.py                 | 11 ++++----
 osc/grabber.py               |  1 -
 osc/oscssl.py                |  4 ---
 osc/util/archquery.py        |  3 +-
 osc/util/cpio.py             |  1 -
 osc/util/debquery.py         |  2 +-
 osc/util/helper.py           |  2 +-
 osc/util/packagequery.py     |  3 +-
 osc/util/rpmquery.py         |  2 +-
 tests/test_addfiles.py       |  3 +-
 tests/test_commit.py         |  3 +-
 tests/test_core.py           |  1 -
 tests/test_deletefiles.py    |  3 +-
 tests/test_difffiles.py      |  3 +-
 tests/test_init_package.py   |  3 +-
 tests/test_init_project.py   |  5 ++--
 tests/test_package_status.py |  3 +-
 tests/test_prdiff.py         |  3 +-
 tests/test_project_status.py |  3 +-
 tests/test_repairwc.py       |  5 ++--
 tests/test_request.py        |  3 +-
 tests/test_results.py        |  3 +-
 tests/test_revertfiles.py    |  3 +-
 tests/test_setlinkrev.py     |  3 +-
 tests/test_update.py         |  3 +-
 30 files changed, 68 insertions(+), 152 deletions(-)
```

**Comment by lethliel** [comment]
Thanks for the report. I am already working on this.. ETA this evening...
