### ISSUE TITLE
osc 1.0.0 - error when cleaning up adi staging project

### ISSUE THREAD

**Issue by DimStar77** [openSUSE/osc#1216]
This error happens at least in context of staging, but is very likely also triggered by other means

Pick any staging with only few requests in it (preferably a red one, so we don't break workflows of the products):
![image](https://user-images.githubusercontent.com/532559/213655474-a597114b-7b1b-4129-87a3-fa0e7cba61fb.png)

`osc staging unselect imv` (to remove that request from staging and put it back on the backlog

This gives a stack trace like this:

```
Traceback (most recent call last):
  File "/usr/bin/osc", line 33, in <module>
    sys.exit(load_entry_point('osc==1.0.0b3', 'console_scripts', 'osc')())
  File "/usr/lib/python3.10/site-packages/osc/babysitter.py", line 208, in main
    sys.exit(run(commandline.Osc()))
  File "/usr/lib/python3.10/site-packages/osc/babysitter.py", line 56, in run
    return prg.main(argv)
  File "/usr/lib/python3.10/site-packages/osc/cmdln.py", line 262, in main
    cmd(self.options.command, self.options, *self.args)
  File "/home/dimstar_suse/.osc-plugins/osc-staging.py", line 431, in do_staging
    UnselectCommand(api).perform(args[1:], opts.cleanup, opts.message)
  File "/home/dimstar_suse/.osc-plugins/osclib/unselect_command.py", line 68, in perform
    self.api.update_status_or_deactivate(prj, 'unselect')
  File "/home/dimstar_suse/.osc-plugins/osclib/stagingapi.py", line 1258, in update_status_or_deactivate
    self.delete_empty_adi_project(project)
  File "/home/dimstar_suse/.osc-plugins/osclib/stagingapi.py", line 1536, in delete_empty_adi_project
    delete_project(self.apiurl, project, force=True)
  File "/usr/lib/python3.10/site-packages/osc/core.py", line 6076, in delete_project
    packages = meta_get_packagelist(apiurl, project)
NameError: name 'project' is not defined. Did you mean: 'Project'?
```

The crash is right down in core

**Comment by DimStar77** [comment]
I can easily reproduce this without staging tooling in place -

`osc meta prj -e home:dimstar:bug1216`, fill in the meta and save it. Project created
`osc rdelete home:dimstar:bug1216 -m cleanup` => triggers the same crash

```
Traceback (most recent call last):
  File "/usr/bin/osc", line 33, in <module>
    sys.exit(load_entry_point('osc==1.0.0b3', 'console_scripts', 'osc')())
  File "/usr/lib/python3.10/site-packages/osc/babysitter.py", line 208, in main
    sys.exit(run(commandline.Osc()))
  File "/usr/lib/python3.10/site-packages/osc/babysitter.py", line 56, in run
    return prg.main(argv)
  File "/usr/lib/python3.10/site-packages/osc/cmdln.py", line 262, in main
    cmd(self.options.command, self.options, *self.args)
  File "/usr/lib/python3.10/site-packages/osc/commandline.py", line 3998, in do_rdelete
    delete_project(apiurl, project, opts.force, msg, recursive=opts.recursive)
  File "/usr/lib/python3.10/site-packages/osc/core.py", line 6076, in delete_project
    packages = meta_get_packagelist(apiurl, project)
NameError: name 'project' is not defined. Did you mean: 'Project'?

```
