### ISSUE TITLE
Crash upon printing weblinks of SRs

### ISSUE THREAD

**Issue by msirringhaus** [openSUSE/osc#1222]
**Describe the bug**
Setting the config-option `print_web_links = 1`, then doing `isc sr --no-cleanup`, osc creates a SR, but instead of printing the link, it crashes with
```
❯ isc sr --no-cleanup
The following submit request is already open: 288688.
Supersede the old request? (y/n/c) y
created request id 288689
Traceback (most recent call last):
  File "/usr/bin/osc", line 33, in <module>
    sys.exit(load_entry_point('osc==1.0.0b3', 'console_scripts', 'osc')())
  File "/usr/lib/python3.10/site-packages/osc/babysitter.py", line 208, in main
    sys.exit(run(commandline.Osc()))
  File "/usr/lib/python3.10/site-packages/osc/babysitter.py", line 56, in run
    return prg.main(argv)
  File "/usr/lib/python3.10/site-packages/osc/cmdln.py", line 262, in main
    cmd(self.options.command, self.options, *self.args)
  File "/usr/lib/python3.10/site-packages/osc/commandline.py", line 1859, in do_submitrequest
    obs_url = _private.get_configuration_option(apiurl, "obs_url")
AttributeError: module 'osc._private' has no attribute 'get_configuration_option'. Did you mean: 'get_configuration_value'?
```
Commenting out the config-option, it works (but obviously, doesn't print the link).

**Versions**
- Operating system: `openSUSE Tumbleweed`
- Packages: `osc-1.0.0~b3-1.1.noarch`

**To Reproduce**
1. Set `print_web_links = 1` in `~/.config/osc/oscrc`
2. Issue an `isc sr --no-cleanup`
3. Crash

**Expected behavior**
Throw no exception, but print the URL.

**Comment by dmach** [comment]
This has been fixed in #1219 already
