### ISSUE TITLE
python stack trace in "osc repourls"

### ISSUE THREAD

**Issue by mwilck** [openSUSE/osc#1232]
**Describe the bug**

`osc repourls` crashes:
```
> osc -A obs repourls openSUSE:Factory
Traceback (most recent call last):
  File "/usr/bin/osc", line 33, in <module>
    sys.exit(load_entry_point('osc==1.0.0b3', 'console_scripts', 'osc')())
  File "/usr/lib/python3.10/site-packages/osc/babysitter.py", line 208, in main
    sys.exit(run(commandline.Osc()))
  File "/usr/lib/python3.10/site-packages/osc/babysitter.py", line 56, in run
    return prg.main(argv)
  File "/usr/lib/python3.10/site-packages/osc/cmdln.py", line 262, in main
    cmd(self.options.command, self.options, *self.args)
  File "/usr/lib/python3.10/site-packages/osc/commandline.py", line 4581, in do_repourls
    download_url = _private.get_configuration_option(apiurl, "download_url")
AttributeError: module 'osc._private' has no attribute 'get_configuration_option'. Did you mean: 'get_configuration_value'?
```

**Versions**
- Operating system: openSUSE Tumbleweed
- Packages: osc-1.0.0~b3-1.1.noarch

**To Reproduce**
See above

**Expected behavior**
doesn't crash, prints repo urls

**Screenshots, console outputs**
See above

**Comment by dmach** [comment]
This has been fixed in #1219 already.
