### ISSUE TITLE
http.cookiejar.LoadError: '/suse/schwab/.osc_cookiejar' does not look like a Set-Cookie3 (LWP) format

### ISSUE THREAD

**Issue by andreas-schwab** [openSUSE/osc#1243]
This is a regression, I have never seen that with the pre-1.0 version. It looks like a race condition, since the file is constantly rewritten.  The contents of the file look correct.

Traceback (most recent call last):
  File "/usr/bin/osc", line 11, in <module>
    load_entry_point('osc==1.0.0b3', 'console_scripts', 'osc')()
  File "/usr/lib/python3.6/site-packages/osc/babysitter.py", line 208, in main
    sys.exit(run(commandline.Osc()))
  File "/usr/lib/python3.6/site-packages/osc/babysitter.py", line 56, in run
    return prg.main(argv)
  File "/usr/lib/python3.6/site-packages/osc/cmdln.py", line 262, in main
    cmd(self.options.command, self.options, *self.args)
  File "/usr/lib/python3.6/site-packages/osc/commandline.py", line 4249, in do_rdiff
    xml=opts.xml)
  File "/usr/lib/python3.6/site-packages/osc/core.py", line 5203, in server_diff_noex
    unified, missingok, meta, expand, onlyissues, True, xml)
  File "/usr/lib/python3.6/site-packages/osc/core.py", line 5163, in server_diff
    f = http_POST(u)
  File "/usr/lib/python3.6/site-packages/osc/connection.py", line 359, in http_POST
    return http_request("POST", *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/osc/connection.py", line 142, in new_func
    return func(method, url, headers, data, file)
  File "/usr/lib/python3.6/site-packages/osc/connection.py", line 269, in http_request
    success = handler.set_request_headers(url, headers)
  File "/usr/lib/python3.6/site-packages/osc/connection.py", line 475, in set_request_headers
    self._cookiejar.add_cookie_header(MockRequest(url, request_headers))
  File "/usr/lib/python3.6/site-packages/osc/connection.py", line 454, in _cookiejar
    jar.load()
  File "/usr/lib64/python3.6/http/cookiejar.py", line 1803, in load
    self._really_load(f, filename, ignore_discard, ignore_expires)
  File "/usr/lib64/python3.6/http/cookiejar.py", line 1906, in _really_load
    raise LoadError(msg)
http.cookiejar.LoadError: '/suse/schwab/.osc_cookiejar' does not look like a Set-Cookie3 (LWP) format file

**Comment by andreas-schwab** [comment]
Intermittently, the file is empty.

**Comment by dmach** [comment]
I fixed the constant rewriting and also handled the traceback on invalid cookiejar file: https://github.com/openSUSE/osc/pull/1249
