### ISSUE TITLE
Regression: deleting a non-empty repo results in a stack trace

### ISSUE THREAD

**Issue by DimStar77** [openSUSE/osc#1247]
**Describe the bug**

**Versions**
- Operating system: Tumbleweed
- Packages: osc-1.0.0~b3-2.1.noarch

**To Reproduce**
```
> osc meta prj -e home:dimstar:bug
Sending meta data...
Done.
> osc linkpac openSUSE:Factory aaa_base home:dimstar:bug
Sending meta data...
Done.
Creating _link... Done.
> osc rdelete home:dimstar:bug -m cleanup
Traceback (most recent call last):
  File "/usr/bin/osc", line 33, in <module>
    sys.exit(load_entry_point('osc==1.0.0b3', 'console_scripts', 'osc')())
  File "/usr/lib/python3.10/site-packages/osc/babysitter.py", line 208, in main
    sys.exit(run(commandline.Osc()))
  File "/usr/lib/python3.10/site-packages/osc/babysitter.py", line 56, in run
    return prg.main(argv)
  File "/usr/lib/python3.10/site-packages/osc/cmdln.py", line 262, in main
    cmd(self.options.command, self.options, *self.args)
  File "/usr/lib/python3.10/site-packages/osc/commandline.py", line 3998, in do_rdelete
    delete_project(apiurl, project, opts.force, msg, recursive=opts.recursive)
  File "/usr/lib/python3.10/site-packages/osc/core.py", line 6085, in delete_project
    raise oscerr.ProjectError(prj, error_msg)
AttributeError: module 'osc.oscerr' has no attribute 'ProjectError'
```

**Expected behavior**

The code is supposed to give back an error if the staging is not empty:

```
        packages = meta_get_packagelist(apiurl, prj)
        if packages:
            error_msg = \
                "Project contains packages. It must be empty before deleting it. " \
                "If you are sure that you want to remove this project and all its " \
                "packages use the 'recursive' option."
            raise oscerr.ProjectError(prj, error_msg)


```

**Comment by dmach** [comment]
This has been fixed in da029941bc78cd708f3db0c80a9327f904b6fd0b already.
