### ISSUE TITLE
load_entry_point traceback with 1.0.0 release on Tumbleweed

### ISSUE THREAD

**Issue by suntorytimed** [openSUSE/osc#1257]
**Describe the bug**
Since openSUSE:Tools got updated to 1.0.0 I can't execute osc anylonger. It throws this traceback:

```
() sweiberg@linux ~
$ osc
Traceback (most recent call last):
  File "/usr/bin/osc", line 33, in <module>
    sys.exit(load_entry_point('osc==1.0.0b4', 'console_scripts', 'osc')())
  File "/usr/bin/osc", line 25, in importlib_load_entry_point
    return next(matches).load()
StopIteration
```

**Versions**
- Operating system: openSUSE Tumbleweed
- Packages: osc-1.0.0~b4-350.2.noarch

**To Reproduce**
1. Run command `osc`
2. See error

**Expected behavior**
osc executing properly

**Screenshots, console outputs**
```
() sweiberg@linux ~
$ osc
Traceback (most recent call last):
  File "/usr/bin/osc", line 33, in <module>
    sys.exit(load_entry_point('osc==1.0.0b4', 'console_scripts', 'osc')())
  File "/usr/bin/osc", line 25, in importlib_load_entry_point
    return next(matches).load()
StopIteration
```

**Additional context**
No further, colliding osc installed on the machine (no installation via pypi). Issue first occurred with the update to 1.0.0b3

**Comment by suntorytimed** [comment]
Installed plugins:
```
i+ | osc                                 | Command-line client for the Open Build Serv-> | package
i+ | osc-plugin-staging                  | OSC plugin for the staging workflow           | package
i  | osclib                              | Supplemental osc libraries                    | package
i  | obs-service-download_files                | An OBS source service: download files   | package
i  | obs-service-format_spec_file              | An OBS source service: reformats a sp-> | package
i+ | obs-service-go_modules                    | An OBS source service: Download, veri-> | package
i+ | obs-service-obs_scm                       | Creates a OBS cpio from a remote SCM -> | package
i  | obs-service-obs_scm-common                | Common parts of SCM handling services   | package
i+ | obs-service-recompress                    | An OBS source service: Recompress files | package
i+ | obs-service-refresh_patches               | An OBS source service: Refreshs local-> | package
i  | obs-service-set_version                   | An OBS source service: Update spec fi-> | package
i+ | obs-service-source_validator              | An OBS source service: running all th-> | package
i+ | obs-service-tar                           | Creates a tar archive from local dire-> | package
i+ | obs-service-tar_scm                       | An OBS source service: create tar bal-> | package
i  | obs-service-verify_file                   | An OBS source service: file verificat-> | package
```

**Comment by lethliel** [comment]
Still cannot reproduce this.. 

Can you please provide the output of 
`osc version`

**Comment by suntorytimed** [comment]
`pip list` didn't detect, that there was a stale 0.182 installation in `/home/sweiberg/.local/lib/python3.10/site-packages` from my prior SLED installation. As I newly installed TW on the root but carried over the home it collided with the RPM package.
