### ISSUE TITLE
Container builds fail with `registry://` URL scheme

### ISSUE THREAD

**Issue by tacerus** [openSUSE/osc#1269]
**Describe the bug**

Upon building some containers, OBS (?) seems to return a `registry://` URL, but osc does not seem to support it.

**Versions**
- Operating system: openSUSE Tumbleweed
- Packages: osc-1.0.0~b5-1.1.noarch

**To Reproduce**
1. `osc co isv:SUSEInfra:Containers salt-ci`
2. `cd isv:SUSEInfra:Containers/salt-ci`
3. `osc build containerfile`

**Expected behavior**
The build should succeed. ;-)

**Screenshots, console outputs**

```
36/80 (SUSE:Registry) container:suse_sle15:15.4.tar.xz
Traceback (most recent call last):
  File "/usr/bin/osc", line 33, in <module>
    sys.exit(load_entry_point('osc==1.0.0b3', 'console_scripts', 'osc')())
  File "/usr/lib/python3.10/site-packages/osc/babysitter.py", line 208, in main
    sys.exit(run(commandline.Osc()))
  File "/usr/lib/python3.10/site-packages/osc/babysitter.py", line 56, in run
    return prg.main(argv)
  File "/usr/lib/python3.10/site-packages/osc/cmdln.py", line 262, in main
    cmd(self.options.command, self.options, *self.args)
  File "/usr/lib/python3.10/site-packages/osc/commandline.py", line 6752, in do_build
    return osc_build.main(self.get_api_url(), opts, args)
  File "/usr/lib/python3.10/site-packages/osc/build.py", line 1135, in main
    fetcher.run(bi)
  File "/usr/lib/python3.10/site-packages/osc/fetch.py", line 251, in run
    self.fetch(i, prefix=prefix)
  File "/usr/lib/python3.10/site-packages/osc/fetch.py", line 140, in fetch
    mg_stat = mg.urlgrab(pac.filename, filename=tmpfile.name,
  File "/usr/lib/python3.10/site-packages/osc/grabber.py", line 38, in urlgrab
    self._grabber.urlgrab(mirror, filename, text)
  File "/usr/lib/python3.10/site-packages/osc/grabber.py", line 25, in urlgrab
    for i in streamfile(url, progress_obj=self.progress_obj,
  File "/usr/lib/python3.10/site-packages/osc/core.py", line 6648, in streamfile
    f = http_meth.__call__(url, data=data)
  File "/usr/lib/python3.10/site-packages/osc/connection.py", line 354, in http_GET
    return http_request("GET", *args, **kwargs)
  File "/usr/lib/python3.10/site-packages/osc/connection.py", line 142, in new_func
    return func(method, url, headers, data, file)
  File "/usr/lib/python3.10/site-packages/osc/connection.py", line 207, in http_request
    response = manager.urlopen(method, url, body=data, headers=headers, preload_content=False)
  File "/usr/lib/python3.10/site-packages/urllib3/poolmanager.py", line 365, in urlopen
    conn = self.connection_from_host(u.host, port=u.port, scheme=u.scheme)
  File "/usr/lib/python3.10/site-packages/urllib3/poolmanager.py", line 246, in connection_from_host
    return self.connection_from_context(request_context)
  File "/usr/lib/python3.10/site-packages/urllib3/poolmanager.py", line 258, in connection_from_context
    raise URLSchemeUnknown(scheme)
urllib3.exceptions.URLSchemeUnknown: Not supported URL scheme registry
```

**Additional context**

To work around the problem, I added `url = url.replace('registry://','https://')` to `connection.py` - with that hack my containers build fine.

This has originally been brought up in the internal SUSE Slack: https://suse.slack.com/archives/C02DR0C5XUY/p1675336087119039.

**Comment by dmach** [comment]
I think the hack only ends up with 404 and the package gets downloaded from the API anyway.
I've submitted a pull request that simply skips invalid schemas and relies on the API download fallback.

**Comment by tacerus** [comment]
Thank you!
