### ISSUE TITLE
AttributeError: module 'urllib3.exceptions' has no attribute 'URLSchemeUnknown'

### ISSUE THREAD

**Issue by andreas-schwab** [openSUSE/osc#1322]
$ osc build standard x86_64 
Building aaa_base.spec for standard/x86_64
Run source service: /usr/lib/obs/service/format_spec_file --outdir /daten/src/osc/openSUSE:Factory/aaa_base/tmppi4pad4k.format_spec_file.service
Run source service: /usr/lib/obs/service/source_validator --outdir /daten/src/osc/openSUSE:Factory/aaa_base/tmprvhe30j2.source_validator.service
- package has aaa_base-rpmlintrc: (unchanged)
Getting buildconfig from server and store to /daten/src/osc/openSUSE:Factory/aaa_base/.osc/_buildconfig-standard-x86_64
Getting buildinfo from server and store to /daten/src/osc/openSUSE:Factory/aaa_base/.osc/_buildinfo-standard-x86_64.xml
Updating cache of required packages
87.5% cache miss. 21/168 dependencies cached.

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/osc/grabber.py", line 40, in urlgrab
    self._grabber.urlgrab(mirror, filename, text)
  File "/usr/lib/python3.6/site-packages/osc/grabber.py", line 28, in urlgrab
    text=text):
  File "/usr/lib/python3.6/site-packages/osc/core.py", line 6858, in streamfile
    f = http_meth.__call__(url, data=data)
  File "/usr/lib/python3.6/site-packages/osc/connection.py", line 385, in http_GET
    return http_request("GET", *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/osc/connection.py", line 143, in new_func
    return func(method, url, headers, data, file, retry_on_400)
  File "/usr/lib/python3.6/site-packages/osc/connection.py", line 212, in http_request
    raise urllib.error.HTTPError(url, response.status, response.reason, response.headers, response)
urllib.error.HTTPError: HTTP Error 404: Not Found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/osc", line 11, in <module>
    load_entry_point('osc==1.1.3', 'console_scripts', 'osc')()
  File "/usr/lib/python3.6/site-packages/osc/babysitter.py", line 227, in main
    sys.exit(run(commandline.OscMainCommand()))
  File "/usr/lib/python3.6/site-packages/osc/babysitter.py", line 69, in run
    prg.main(argv)
  File "/usr/lib/python3.6/site-packages/osc/commandline.py", line 531, in main
    cmd.run(args)
  File "/usr/lib/python3.6/site-packages/osc/commandline.py", line 240, in run
    cmd.run(args)
  File "/usr/lib/python3.6/site-packages/osc/commandline.py", line 475, in run
    self.func(args.command, args, *args.positional_args)
  File "/usr/lib/python3.6/site-packages/osc/commandline.py", line 7257, in do_build
    return osc_build.main(self.get_api_url(), opts, args)
  File "/usr/lib/python3.6/site-packages/osc/build.py", line 1148, in main
    fetcher.run(bi)
  File "/usr/lib/python3.6/site-packages/osc/fetch.py", line 267, in run
    self.fetch(i, prefix=prefix)
  File "/usr/lib/python3.6/site-packages/osc/fetch.py", line 144, in fetch
    text='%s(%s) %s' % (prefix, pac.project, pac.filename))
  File "/usr/lib/python3.6/site-packages/osc/grabber.py", line 42, in urlgrab
    except (HTTPError, URLError, urllib3.exceptions.URLSchemeUnknown) as e:
AttributeError: module 'urllib3.exceptions' has no attribute 'URLSchemeUnknown'

**Comment by dmach** [comment]
@andreas-schwab what's the distro? And what's the output from `rpm -qa | grep urllib3`?

**Comment by andreas-schwab** [comment]
1.25.10
