### ISSUE TITLE
osc buildhist fails to parse _history

### ISSUE THREAD

**Issue by andreas-schwab** [openSUSE/osc#136]
$ osc buildhist home:Andreas_Schwab:glibc glibc f ppc64le
Traceback (most recent call last):
  File "/usr/bin/osc", line 26, in <module>
    r = babysitter.run(osccli)
  File "/usr/lib/python2.7/site-packages/osc/babysitter.py", line 61, in run
    return prg.main(argv)
  File "/usr/lib/python2.7/site-packages/osc/cmdln.py", line 343, in main
    return self.cmd(args)
  File "/usr/lib/python2.7/site-packages/osc/cmdln.py", line 366, in cmd
    retval = self.onecmd(argv)
  File "/usr/lib/python2.7/site-packages/osc/cmdln.py", line 500, in onecmd
    return self._dispatch_cmd(handler, argv)
  File "/usr/lib/python2.7/site-packages/osc/cmdln.py", line 1230, in _dispatch_cmd
    return handler(argv[0], opts, *args)
  File "/usr/lib/python2.7/site-packages/osc/commandline.py", line 5908, in do_buildhistory
    print('\n'.join(get_buildhistory(apiurl, project, package, repository, arch, format)))
  File "/usr/lib/python2.7/site-packages/osc/core.py", line 5705, in get_buildhistory
    rev = int(node.get('rev'))
ValueError: invalid literal for int() with base 10: '21ce125388a9209b1ee683c47decf58d'
$ osc api /build/home:Andreas_Schwab:glibc/f/ppc64le/glibc/_history
`<buildhistory>
  <entry rev="21ce125388a9209b1ee683c47decf58d" srcmd5="6567d0051b9fa4f35d4765db1fa7edd6" versrel="2.20.90-457" bcnt="1" time="1416313253" duration="1221" />
  <entry rev="eef9afeabd78fda0c1bab4b8ac113af0" srcmd5="b1d942c0f06fb15caaddf4688a455d33" versrel="2.20.90-458" bcnt="1" time="1416394885" duration="1192" />
  <entry rev="dad2b12b01ad11cf16b36b4410dd855c" srcmd5="b8ca3d722a35de4d253bb4af6022d416" versrel="2.20.90-460" bcnt="1" time="1417258969" duration="1497" />
  <entry rev="73" srcmd5="66071f08b9ba7b9c53975e77bb4f543a" versrel="2.20.90-469" bcnt="1" time="1418816938" duration="1263" />
  <entry rev="95e18f17533a3be0950183d8273862ee" srcmd5="578f2a0a5cad853eb156fc3edb593340" versrel="2.20.90-470" bcnt="1" time="1419033027" duration="1236" />
</buildhistory>`

**Comment by adrianschroeter** [comment]
hm, easy to fix in osc, but it looks like an backend incompatible change in first place ... Michael? @mlschroe

**Comment by adrianschroeter** [comment]
no, it was always broken in osc .... fixed now in git master
