### ISSUE TITLE
proxy without auth does not work

### ISSUE THREAD

**Issue by lictex** [openSUSE/osc#1363]
```
> HTTP_PROXY=http://127.0.0.1:10000 osc up
Traceback (most recent call last):
  File "/usr/bin/osc", line 33, in <module>
    sys.exit(load_entry_point('osc==1.2.0', 'console_scripts', 'osc')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/osc", line 25, in importlib_load_entry_point
    return next(matches).load()
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/importlib/metadata/__init__.py", line 202, in load
    module = import_module(match.group('module'))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/lib/python3.11/site-packages/osc/babysitter.py", line 20, in <module>
    from . import commandline
  File "/usr/lib/python3.11/site-packages/osc/commandline.py", line 29, in <module>
    from . import build as osc_build
  File "/usr/lib/python3.11/site-packages/osc/build.py", line 20, in <module>
    from . import connection
  File "/usr/lib/python3.11/site-packages/osc/connection.py", line 130, in <module>
    HTTP_PROXY_MANAGER = get_proxy_manager("HTTP_PROXY")
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/osc/connection.py", line 110, in get_proxy_manager
    proxy_basic_auth = urllib.parse.unquote(proxy_purl.auth)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/urllib/parse.py", line 671, in unquote
    if '%' not in string:
       ^^^^^^^^^^^^^^^^^
TypeError: argument of type 'NoneType' is not iterable
```
----
https://github.com/openSUSE/osc/blob/c22aceb28dc3c6df82ffbb34e5f99caf21cb1deb/osc/connection.py#L110
`proxy_purl.auth` might be `None` here

**Comment by dmach** [comment]
Thanks for the report. I've submitted a pull request that should fix this.
Could you test it and report back if it works as expected?
