### ISSUE TITLE
osc qam fails to after a system upgrade

### ISSUE THREAD

**Issue by logsnaath** [openSUSE/osc#1429]
**Describe the bug**
After an upgrade of openSUSE Tumbleweed, `osc qam my`  fails

**Versions**
- Operating system: `openSUSE Tumbleweed`
- Packages: `osc-1.4.1-1.1.noarch`

**To Reproduce**
1. upgrade the system `sudo zypper dup`
2. Run command `osc -A <apiurl> qam my`
3. See error

```
$ osc qam my

Traceback (most recent call last):
  File "/usr/bin/osc", line 33, in <module>
    sys.exit(load_entry_point('osc==1.4.1', 'console_scripts', 'osc')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/osc/babysitter.py", line 226, in main
    sys.exit(run(commandline.OscMainCommand()))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/osc/babysitter.py", line 69, in run
    prg.main(argv)
  File "/usr/lib/python3.11/site-packages/osc/commandline.py", line 545, in main
    cmd.run(args)
  File "/usr/lib/python3.11/site-packages/osc/commandline.py", line 241, in run
    cmd.run(args)
  File "/usr/lib/osc-plugins/qam_my.py", line 46, in run
    action = ListAssignedUserAction(self.api, self.affected_user)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/oscqam/actions/listaction.py", line 44, in __init__
    super().__init__(remote, user)
  File "/usr/lib/python3.11/site-packages/oscqam/actions/oscaction.py", line 23, in __init__
    self.user = remote.users.by_name(user)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/oscqam/remotes/userremote.py", line 14, in by_name
    users = User.parse(self.remote, self.remote.get(url))
                                    ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/oscqam/remotes/remotefacade.py", line 58, in get
    remote = osc.core.http_GET(url)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/osc/connection.py", line 404, in http_GET
    return http_request("GET", *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/osc/connection.py", line 149, in new_func
    return func(method, url, headers, data, file, retry_on_400)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/osc/connection.py", line 312, in http_request
    SignatureAuthHandler(apiurl, options["user"], options["sshkey"], options["pass"]),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/osc/connection.py", line 587, in __init__
    self.basic_auth_password = bool(basic_auth_password)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/collections/__init__.py", line 1393, in __len__
    return len(self.data)
           ^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/collections/__init__.py", line 1393, in __len__
    return len(self.data)
           ^^^^^^^^^^^^^^
TypeError: object of type '_PasswordRetriever' has no len()
```

**Expected behavior**
Should list the packages

**Additional context**

After regenarating oscrc, it starts to work.

```
cat ~/.config/osc/oscrc

[general]
apiurl=https://api.xxxx.xxx

[https://api.xxxxx.xxx]
user=lxxxxx
credentials_mgr_class=osc.credentials.KeyringCredentialsManager:keyutils.osc.OscKernelKeyringBackend

```

**Comment by dmach** [comment]
Hi, thanks for the report.
It seems I broke integration with python3-keyring-keyutils.
I'll fix this shortly.
