### ISSUE TITLE
KeyError: 'apiurl_aliases'

### ISSUE THREAD

**Issue by andreas-schwab** [openSUSE/osc#1439]
$ osc config https://api.opensuse.org --delete aliases
Traceback (most recent call last):
  File "/usr/bin/osc", line 11, in <module>
    load_entry_point('osc==1.4.3', 'console_scripts', 'osc')()
  File "/usr/lib/python3.6/site-packages/osc/babysitter.py", line 226, in main
    sys.exit(run(commandline.OscMainCommand()))
  File "/usr/lib/python3.6/site-packages/osc/babysitter.py", line 69, in run
    prg.main(argv)
  File "/usr/lib/python3.6/site-packages/osc/commandline.py", line 545, in main
    cmd.run(args)
  File "/usr/lib/python3.6/site-packages/osc/commandline.py", line 241, in run
    cmd.run(args)
  File "/usr/lib/python3.6/site-packages/osc/commandline.py", line 489, in run
    self.func(args.command, args, *args.positional_args)
  File "/usr/lib/python3.6/site-packages/osc/commandline.py", line 9863, in do_config
    opt, newval = conf.config_set_option(section, opt, ' '.join(val), delete=opts.delete, update=True, creds_mgr_descr=creds_mgr_descr)
  File "/usr/lib/python3.6/site-packages/osc/conf.py", line 1620, in config_set_option
    section = config['apiurl_aliases'].get(section, section)
  File "/usr/lib/python3.6/site-packages/osc/conf.py", line 148, in __getitem__
    return self.extra_fields[name]
KeyError: 'apiurl_aliases'

**Comment by jengelh** [comment]
Also happens adding aliases:

```
12:06 a4:../telephony/linphone $ osc build
Building linphone.spec for openSUSE_Tumbleweed/x86_64
[...]
The build root needs packages from project 'network:telephony'.
Note that malicious packages can compromise the build result or even your system.
Would you like to ...
0 - quit (default)
1 - always trust packages from 'network:telephony'
2 - trust packages just this time
? 1
adding 'network:telephony' to oscrc: ['https://api.opensuse.org']['trusted_prj']
Traceback (most recent call last):
  File "/usr/bin/osc", line 33, in <module>
    sys.exit(load_entry_point('osc==1.4.3', 'console_scripts', 'osc')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/osc/babysitter.py", line 226, in main
    sys.exit(run(commandline.OscMainCommand()))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/osc/babysitter.py", line 69, in run
    prg.main(argv)
  File "/usr/lib/python3.11/site-packages/osc/commandline.py", line 545, in main
    cmd.run(args)
  File "/usr/lib/python3.11/site-packages/osc/commandline.py", line 241, in run
    cmd.run(args)
  File "/usr/lib/python3.11/site-packages/osc/commandline.py", line 489, in run
    self.func(args.command, args, *args.positional_args)
  File "/usr/lib/python3.11/site-packages/osc/commandline.py", line 7349, in do_build
    return osc_build.main(self.get_api_url(), store, opts, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/osc/build.py", line 1125, in main
    check_trusted_projects(apiurl, [i for i in bi.projects.keys() if not i == prj])
  File "/usr/lib/python3.11/site-packages/osc/build.py", line 580, in check_trusted_projects
    conf.config_set_option(apiurl, 'trusted_prj', ' '.join(trusted))
  File "/usr/lib/python3.11/site-packages/osc/conf.py", line 1620, in config_set_option
    section = config['apiurl_aliases'].get(section, section)
              ~~~~~~^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/osc/conf.py", line 148, in __getitem__
    return self.extra_fields[name]
           ~~~~~~~~~~~~~~~~~^^^^^^
KeyError: 'apiurl_aliases'
```

**Comment by SchoolGuy** [comment]
Can confirm.

```
┬─[enno@tower:~/S/E/h/python-sqlite3-to-mysql]─[15:57:53]
╰─>$ osc version
1.4.3
```

**Comment by mlewissmith** [comment]
This appears to affect any attempt to write/change any config values in [$apiurl] sections, but not the [general] section

   $ osc config general build-jobs 1
   'general': 'build-jobs' is set to '1'

but 

   $ osc config $APIURL --changepassword
   ...
   KeyError: 'apiurl_aliases'

**Comment by cpanel-hans** [comment]
I get the same error when running `osc config internal user`
...
KeyError: 'apiurl_aliases'

Broke for me when I updated from osc-1.2.0-372.1.noarch to osc-1.4.3-383.1.noarch

**Comment by drmuey** [comment]
9067a803cc seems relevant, was in v1.4.2 ee5a1c476

**Comment by pallaswept** [comment]
Same with copypac (my.private.api.url is edited in there for my privacy and is a real URL which does work with other OSC commands):

```
osc -A api.opensuse.org copypac -t my.private.api.url $PROJECT ffnvcodec $PROJECT
Traceback (most recent call last):
  File "/usr/bin/osc", line 33, in <module>
    sys.exit(load_entry_point('osc==1.4.3', 'console_scripts', 'osc')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/osc/babysitter.py", line 226, in main
    sys.exit(run(commandline.OscMainCommand()))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/osc/babysitter.py", line 69, in run
    prg.main(argv)
  File "/usr/lib/python3.11/site-packages/osc/commandline.py", line 545, in main
    cmd.run(args)
  File "/usr/lib/python3.11/site-packages/osc/commandline.py", line 241, in run
    cmd.run(args)
  File "/usr/lib/python3.11/site-packages/osc/commandline.py", line 489, in run
    self.func(args.command, args, *args.positional_args)
  File "/usr/lib/python3.11/site-packages/osc/commandline.py", line 3873, in do_copypac
    tgt_apiurl = conf.config['apiurl_aliases'].get(opts.to_apiurl, opts.to_apiurl)
                 ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/osc/conf.py", line 148, in __getitem__
    return self.extra_fields[name]
           ~~~~~~~~~~~~~~~~~^^^^^^
KeyError: 'apiurl_aliases'
```

I get the same thing if I use the alias or fully specify the URL. I tried the patch mentioned that hopefully fixes this and indeed I didn't get the same error, but it still didn't work:


```
osc -A api.opensuse.org copypac -t my.private.api.url $PROJECT ffnvcodec $PROJECT
Sending meta data...
Server returned an error: HTTP Error 405: Method Not Allowed
```

Which might be a different issue and need a different case logged, or might be a failure of the fix, I can't say for sure.
