### ISSUE TITLE
osc does not properly handle repodata in local builds

### ISSUE THREAD

**Issue by jplautz** [openSUSE/osc#147]
I'm using the latest osc/master source as of 2015-04-28

When running a local build with osc using the -p option pointing at a local directory that has had createrepo run on it, osc dies with a traceback:

Traceback (most recent call last):
  File "/usr/bin/osc", line 26, in <module>
    r = babysitter.run(osccli)
  File "/usr/lib64/python2.6/site-packages/osc/babysitter.py", line 61, in run
    return prg.main(argv)
  File "/usr/lib64/python2.6/site-packages/osc/cmdln.py", line 343, in main
    return self.cmd(args)
  File "/usr/lib64/python2.6/site-packages/osc/cmdln.py", line 366, in cmd
    retval = self.onecmd(argv)
  File "/usr/lib64/python2.6/site-packages/osc/cmdln.py", line 500, in onecmd
    return self._dispatch_cmd(handler, argv)
  File "/usr/lib64/python2.6/site-packages/osc/cmdln.py", line 1230, in _dispatch_cmd
    return handler(argv[0], opts, *args)
  File "/usr/lib64/python2.6/site-packages/osc/commandline.py", line 5672, in do_build
    return osc.build.main(self.get_api_url(), opts, args)
  File "/usr/lib64/python2.6/site-packages/osc/build.py", line 586, in main
    prefer_pkgs = get_prefer_pkgs(opts.prefer_pkgs, arch, build_type, cpiodata)
  File "/usr/lib64/python2.6/site-packages/osc/build.py", line 361, in get_prefer_pkgs
    depfile = create_deps(packageQueries.values())
  File "/usr/lib64/python2.6/site-packages/osc/build.py", line 376, in create_deps
    d = p.conflicts()
AttributeError: 'RepoDataQuery' object has no attribute 'conflicts'

The issue appears to trace back to:
https://github.com/openSUSE/osc/commit/7ca0b2d04e464a5e3c265b34edf481c78633bbae

build.py was updated to expect "conflicts" and "obsoletes" from the RepoDataQuery class, but  repodata.py was not updated to provide those methods.

**Comment by jplautz** [comment]
"evr" also appears to be missing

**Comment by marcus-h** [comment]
Yes, the RepoDataQuery should inherit from the "abstract"
PackageQuery (and properly implement the abstract methods).
I'll take care of it.

**Comment by marcus-h** [comment]
Fixed in commit a80b286ac922cafc76fbd6cd069f8412de2d58af.
Sorry for the long delay...
