### ISSUE TITLE
parse error during checkout and checkin

### ISSUE THREAD

**Issue by arunpersaud** [openSUSE/osc#153]
Hi

this seems to be the same as #93. So I tried to check the repo out again, but that didn't help:

    arun@apersaud:~/src/OBS/home:apersaud:branches:devel:languages:python3(master)>cd python3-cryptography
    /home/arun/src/OBS/home:apersaud:branches:devel:languages:python3/python3-cryptography
    arun@apersaud:~/src/OBS/home:apersaud:branches:devel:languages:python3/python3-cryptography(master)>osc ci -n
    Traceback (most recent call last):
      File "/usr/bin/osc", line 26, in <module>
        r = babysitter.run(osccli)
      File "/usr/lib/python2.7/site-packages/osc/babysitter.py", line 61, in run
        return prg.main(argv)
      File "/usr/lib/python2.7/site-packages/osc/cmdln.py", line 343, in main
        return self.cmd(args)
      File "/usr/lib/python2.7/site-packages/osc/cmdln.py", line 366, in cmd
        retval = self.onecmd(argv)
      File "/usr/lib/python2.7/site-packages/osc/cmdln.py", line 500, in onecmd
        return self._dispatch_cmd(handler, argv)
      File "/usr/lib/python2.7/site-packages/osc/cmdln.py", line 1230, in _dispatch_cmd
        return handler(argv[0], opts, *args)
      File "/usr/lib/python2.7/site-packages/osc/commandline.py", line 4405, in do_commit
        prj = Project(prj_path)
      File "/usr/lib/python2.7/site-packages/osc/core.py", line 625, in __init__
        self.pac_root = self.read_packages().getroot()
      File "/usr/lib/python2.7/site-packages/osc/core.py", line 751, in read_packages
        return ET.parse(packages_file)
      File "<string>", line 62, in parse
      File "<string>", line 38, in parse
    cElementTree.ParseError: not well-formed (invalid token): line 319, column 15
    arun@apersaud:~/src/OBS/home:apersaud:branches:devel:languages:python3/python3-cryptography(master)>cd ..
    arun@apersaud:~/src/OBS/home:apersaud:branches:devel:languages:python3(master)>mv python3-cryptography tmp
    arun@apersaud:~/src/OBS/home:apersaud:branches:devel:languages:python3(master)>osc co python3-cryptography
    A    python3-cryptography
    Traceback (most recent call last):
      File "/usr/bin/osc", line 26, in <module>
        r = babysitter.run(osccli)
      File "/usr/lib/python2.7/site-packages/osc/babysitter.py", line 61, in run
        return prg.main(argv)
      File "/usr/lib/python2.7/site-packages/osc/cmdln.py", line 343, in main
        return self.cmd(args)
      File "/usr/lib/python2.7/site-packages/osc/cmdln.py", line 366, in cmd
        retval = self.onecmd(argv)
      File "/usr/lib/python2.7/site-packages/osc/cmdln.py", line 500, in onecmd
        return self._dispatch_cmd(handler, argv)
      File "/usr/lib/python2.7/site-packages/osc/cmdln.py", line 1230, in _dispatch_cmd
        return handler(argv[0], opts, *args)
      File "/usr/lib/python2.7/site-packages/osc/commandline.py", line 4073, in do_checkout
        meta=opts.meta, outdir=opts.output_dir)
      File "/usr/lib/python2.7/site-packages/osc/core.py", line 4695, in checkout_package
        prj_obj = Project(prj_dir)
      File "/usr/lib/python2.7/site-packages/osc/core.py", line 625, in __init__
        self.pac_root = self.read_packages().getroot()
      File "/usr/lib/python2.7/site-packages/osc/core.py", line 751, in read_packages
        return ET.parse(packages_file)
      File "<string>", line 62, in parse
      File "<string>", line 38, in parse
    cElementTree.ParseError: not well-formed (invalid token): line 319, column 15

Here is my version information:

    arun@apersaud:~/src/OBS/home:apersaud:branches:devel:languages:python3(master)>osc --version
    0.151

I'm running Tumbleweed. Osc worked a few days ago and I haven't used it since then, but I did run a zypper up since then.

**Comment by arunpersaud** [comment]
Think I found the problem, the .osc/_packages in my project folder seems to be broken. Doing a clean checkout of the whole project solved the issue.

Here is the .osc/_packages file:

    <project name="home:apersaud:branches:devel:languages:python3">
      <package name="python3-cssselect" state=" " />
       ....
      <package name="python3-rodeo" state=" " />  
      <package name="python3-pytesseract" state=" " /> 
     </project> name="python3-pyalsaaudio" state=" " />
   </project>

For some reason the </project> tag shows up twice. 

Creating a pull request for better error messages now.
