### ISSUE TITLE
osc linkpac fails to overwrite link file

### ISSUE THREAD

**Issue by olafhering** [openSUSE/osc#1541]
This fails in 15.5, and also in current Tumbleweed.
````
osc linkpac -C add -d fooprj pkg tgtprj
osc linkpac -C add -d -f barprj pkg tgtprj
Traceback (most recent call last):
  File "/usr/bin/osc", line 33, in <module>
    sys.exit(load_entry_point('osc==1.6.1', 'console_scripts', 'osc')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/osc/babysitter.py", line 226, in main
    sys.exit(run(commandline.OscMainCommand()))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/osc/babysitter.py", line 69, in run
    prg.main(argv)
  File "/usr/lib/python3.11/site-packages/osc/commandline.py", line 558, in main
    cmd.run(args)
  File "/usr/lib/python3.11/site-packages/osc/commandline.py", line 246, in run
    cmd.run(args)
  File "/usr/lib/python3.11/site-packages/osc/commandline.py", line 502, in run
    self.func(args.command, args, *args.positional_args)
  File "/usr/lib/python3.11/site-packages/osc/commandline.py", line 3792, in do_linkpac
    link_pac(
  File "/usr/lib/python3.11/site-packages/osc/core.py", line 5825, in link_pac
    root = ET.fromstring(''.join(dst_meta))
                         ^^^^^^^^^^^^^^^^^
TypeError: sequence item 0: expected str instance, bytes found

````

**Comment by dmach** [comment]
I've fixed this in #1543.
Someday I'll port this to the XML object wrappers (aka models) that live in `osc.obs_api` module to get rid of such issues completely.
