### ISSUE TITLE
osc results: Cannot specify --csv and --multibuild-package at the same time

### ISSUE THREAD

**Issue by marcosbc** [openSUSE/osc#1579]
**Describe the bug**
t is not currently possible to specify the `--csv` and `--multibuild-package` options at the same time with the `osc results` command.

Use case: We want to be able to run `osc results --watch` using a specific format, which is only possible with `--csv` (via the `--format` option), but showing only the results for a specific multibuild package.

**Versions**
- Operating system: `openSUSE Tumbleweed`
- Packages: `osc-1.7.0-1.1.noarch`

**To Reproduce**
1. Run `osc results` with the `--csv` and `--multibuild-package` at the same time, it should fail:

    ```
    $ osc results -A api.opensuse.org openSUSE:Factory opensuse-tumbleweed-image --repo=images --multibuild-package=docker --csv
    Traceback (most recent call last):
      File "/opt/homebrew/bin/osc", line 33, in <module>
        sys.exit(load_entry_point('osc==1.1.4+22.git.17dbe25a', 'console_scripts', 'osc')())
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/opt/homebrew/lib/python3.11/site-packages/osc-1.1.4+22.git.17dbe25a-py3.11.egg/osc/babysitter.py", line 236, in main
        sys.exit(run(commandline.OscMainCommand()))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/opt/homebrew/lib/python3.11/site-packages/osc-1.1.4+22.git.17dbe25a-py3.11.egg/osc/babysitter.py", line 69, in run
        prg.main(argv)
      File "/opt/homebrew/lib/python3.11/site-packages/osc-1.1.4+22.git.17dbe25a-py3.11.egg/osc/commandline.py", line 531, in main
        cmd.run(args)
      File "/opt/homebrew/lib/python3.11/site-packages/osc-1.1.4+22.git.17dbe25a-py3.11.egg/osc/commandline.py", line 240, in run
        cmd.run(args)
      File "/opt/homebrew/lib/python3.11/site-packages/osc-1.1.4+22.git.17dbe25a-py3.11.egg/osc/commandline.py", line 475, in run
        self.func(args.command, args, *args.positional_args)
      File "/opt/homebrew/lib/python3.11/site-packages/osc-1.1.4+22.git.17dbe25a-py3.11.egg/osc/commandline.py", line 6042, in do_results
        for xml in get_package_results(**kwargs):
      File "/opt/homebrew/lib/python3.11/site-packages/osc-1.1.4+22.git.17dbe25a-py3.11.egg/osc/core.py", line 6599, in get_package_results
        xml = b''.join(show_results_meta(apiurl, project, package, *args, **kwargs))
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    TypeError: show_results_meta() got an unexpected keyword argument 'multibuild_packages'
    ```

**Expected behavior**
The `osc results` command should allow to use the `--csv` and `--multibuild-package` options at the same time, and show the results only for the specified multibuild package.

**Screenshots, console outputs**
See above.

**Additional context**
N/A.

**Comment by marcosbc** [comment]
I have sent a workaround that would resolve our use case in #1580. If the contribution were accepted, this issue would no longer be applicable for us, so it could be closed.
