### ISSUE TITLE
osc build -p /dirty/direcotry/ barfs if directory holds other files then (Debian) packages

### ISSUE THREAD

**Issue by gollub** [openSUSE/osc#158]
```
$ osc build -p /home/dgollub/work/
[...]
Scanning the following dirs for local packages: /home/dgollub/work/
Traceback (most recent call last):
  File "/usr/bin/osc", line 41, in <module>
    r = babysitter.run(osccli)
  File "/usr/lib/python2.7/dist-packages/osc/babysitter.py", line 61, in run
    return prg.main(argv)
  File "/usr/lib/python2.7/dist-packages/osc/cmdln.py", line 343, in main
    return self.cmd(args)
  File "/usr/lib/python2.7/dist-packages/osc/cmdln.py", line 366, in cmd
    retval = self.onecmd(argv)
  File "/usr/lib/python2.7/dist-packages/osc/cmdln.py", line 500, in onecmd
    return self._dispatch_cmd(handler, argv)
  File "/usr/lib/python2.7/dist-packages/osc/cmdln.py", line 1230, in _dispatch_cmd
    return handler(argv[0], opts, *args)
  File "/usr/lib/python2.7/dist-packages/osc/commandline.py", line 5710, in do_build
    return osc.build.main(self.get_api_url(), opts, args)
  File "/usr/lib/python2.7/dist-packages/osc/build.py", line 598, in main
    prefer_pkgs = get_prefer_pkgs(opts.prefer_pkgs, arch, build_type, cpiodata)
  File "/usr/lib/python2.7/dist-packages/osc/build.py", line 363, in get_prefer_pkgs
    depfile = create_deps(packageQueries.values())
  File "/usr/lib/python2.7/dist-packages/osc/build.py", line 384, in create_deps
    depfile.append('I:%s%s-%s 0-%s' % (id, p.name(), p.evr(), p.arch()))
  File "/usr/lib/python2.7/dist-packages/osc/util/packagequery.py", line 140, in evr
    evr = self.version() + "-" + self.release()
TypeError: cannot concatenate 'str' and 'NoneType' objects
```

This -p directory holds all kind of other directories and files - which I obviously shouldn't have done.

**Comment by gollub** [comment]
The reason seems to be that OSC can't handle "native" Debian packages.

Native packages don't have broken-out patches (quilt) and don't have a upstream project (e.g. a project driven by Debian). The version schema is: <debian-version> (no release!) for native packages. For non-native versions: <upstream-version>-<debian-release>


In osc/util/debquery.py:
```
    def __parse_control(self, control, all_tags=False, self_provides=True, *extra_tags):
[...]
        versrel = self.fields['version'].rsplit('-', 1)
        if len(versrel) == 2:
            self.fields['version'] = versrel[0]
            self.fields['release'] = versrel[1]
        else:
            self.fields['release'] = None

```

So I guess PackageQueryResult.evr() needs to handle the case for packages which don't come with a release version. To make -p working for Debian native-packages.

Providing a pull-request ...

**Comment by marcus-h** [comment]
Merged your pull request. Thanks!
