### ISSUE TITLE
Osc build exits with TypeError  'KeyinfoPubkey' if no publickeys are returned by the server

### ISSUE THREAD

**Issue by Thaodan** [openSUSE/osc#1596]
**Describe the bug**
When trying to build with osc build against a server that doesn't return public keys it exits before building with 'KeyinfoPubkey'.

**Versions**
- Operating system: openSUSE Tumbleweed
- Packages:  osc-1.8.1-420.1.noarch

**To Reproduce**
1. Run command osc build 
2. See error

**Expected behavior**
No error.

**Screenshots, console outputs**
<details>
```
Traceback (most recent call last):
  File "/usr/bin/osc", line 33, in <module>
    sys.exit(load_entry_point('osc==1.8.1', 'console_scripts', 'osc')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/osc/babysitter.py", line 227, in main
    sys.exit(run(commandline.OscMainCommand()))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/osc/babysitter.py", line 70, in run
    prg.main(argv)
  File "/usr/lib/python3.11/site-packages/osc/commandline.py", line 565, in main
    exit_code = cmd.run(args)
                ^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/osc/commandline.py", line 249, in run
    return cmd.run(args)
           ^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/osc/commandline.py", line 509, in run
    return self.func(args.command, args, *args.positional_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/osc/commandline.py", line 7600, in do_build
    return osc_build.main(self.get_api_url(), store, opts, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/osc/build.py", line 1202, in main
    fetcher.run(bi)
  File "/usr/lib/python3.11/site-packages/osc/fetch.py", line 313, in run
    keyinfo = obs_api.Keyinfo.from_api(buildinfo.apiurl, prj)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/osc/obs_api/keyinfo.py", line 33, in from_api
    return cls.from_file(response, apiurl=apiurl)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/osc/util/models.py", line 579, in from_file
    return cls.from_xml(root, apiurl=apiurl)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/osc/util/models.py", line 719, in from_xml
    entry = klass.from_xml(node, apiurl=apiurl)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/osc/util/models.py", line 774, in from_xml
    obj = cls(**kwargs, _apiurl=apiurl)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/osc/util/models.py", line 405, in __init__
    raise TypeError(
TypeError: The following fields of 'KeyinfoPubkey' object are not initialized and have no default either: 'userid', 'expires'
```
</details>

**Additional context**

**Comment by dmach** [comment]
@Thaodan how can I reproduce it? Does it happen on a public obs instance?
Unless there's another bug, it seems that a keyinfo entry is returned but lacks `userid` and `expires` fields.
Could you run `osc -A <apiurl> api /source/<project>/_keyinfo` on the project that causes the problem and paste the output here?

**Comment by Thaodan** [comment]
> Unless there's another bug, it seems that a keyinfo entry is returned
> but lacks userid and expires fields.

That seems to be true.

osc -A jollap api /source/sf:live:devel:oss/_keyinfo
<keyinfo>
  <pubkey keyid="47394f23" algo="rsa" keysize="4096" fingerprint="c3e3 d50a 6b4f 2395 9e0c 401a 5b1e 3989 4739 4f23">-----BEGIN PGP PUBLIC KEY BLOCK-----
Version: GnuPG v2

insert key here
-----END PGP PUBLIC KEY BLOCK-----
</pubkey>
</keyinfo>

**Comment by dmach** [comment]
You seem to be using the minimal set of attributes possible.
Let me make the others optional.

**Comment by Thaodan** [comment]
Does that mean that these attributes are optional as per the OBS API?

**Comment by dmach** [comment]
> Does that mean that these attributes are optional as per the OBS API?

Most likely. I've submitted a schema to OBS that they did not have yet and commented that the attributes shouldn't be optional: https://github.com/openSUSE/open-build-service/pull/16456
