### ISSUE TITLE
invalid argument: 'acceptinfo_oxsrcmd5'

### ISSUE THREAD

**Issue by lnussel** [openSUSE/osc#160]
$ osci rq show 61826
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/osc/babysitter.py", line 61, in run
    return prg.main(argv)
  File "/usr/lib/python2.7/site-packages/osc/cmdln.py", line 343, in main
    return self.cmd(args)
  File "/usr/lib/python2.7/site-packages/osc/cmdln.py", line 366, in cmd
    retval = self.onecmd(argv)
  File "/usr/lib/python2.7/site-packages/osc/cmdln.py", line 500, in onecmd
    return self._dispatch_cmd(handler, argv)
  File "/usr/lib/python2.7/site-packages/osc/cmdln.py", line 1230, in _dispatch_cmd
    return handler(argv[0], opts, *args)
  File "/usr/lib/python2.7/site-packages/osc/commandline.py", line 2210, in do_request
    r = get_request(apiurl, reqid)
  File "/usr/lib/python2.7/site-packages/osc/core.py", line 4016, in get_request
    r.read(root)
  File "/usr/lib/python2.7/site-packages/osc/core.py", line 2641, in read
    self.actions.append(Action.from_xml(action))
  File "/usr/lib/python2.7/site-packages/osc/core.py", line 2604, in from_xml
    return Action(action_node.get('type'), **kwargs)
  File "/usr/lib/python2.7/site-packages/osc/core.py", line 2533, in __init__
    raise oscerr.WrongArgs('invalid argument: \'%s\'' % i)
WrongArgs: invalid argument: 'acceptinfo_oxsrcmd5'
invalid argument: 'acceptinfo_oxsrcmd5'

**Comment by lnussel** [comment]
request contains

    <acceptinfo rev="2" srcmd5="7b59b525e94079b77891cf49a9029f30" osrcmd5="eb242463fbbaaf009109676f22910bd6" xsrcmd5="d0a2667bc6c734bad5cbd522efca7135" oxsrcmd5="f819c35579b849efd16bd9379d09615c"/>

**Comment by marcus-h** [comment]
On 2015-07-09 05:52:44 -0700, Ludwig Nussel wrote:
> $ osci rq show 61826

Hmm there's probably a digit missing? Are you using the
latest osc from openSUSE:Tools?

**Comment by marcus-h** [comment]
On 2015-07-09 05:53:24 -0700, Ludwig Nussel wrote:
> request contains
> 
>     <acceptinfo rev="2" srcmd5="7b59b525e94079b77891cf49a9029f30" osrcmd5="eb242463fbbaaf009109676f22910bd6" xsrcmd5="d0a2667bc6c734bad5cbd522efca7135" oxsrcmd5="f819c35579b849efd16bd9379d09615c"/>
> 
What's the value of the parent element's "type" attribute?
(I assume it is "maintenance_release" or "maintenance_incident")

**Comment by lnussel** [comment]
running TW osc-0.151.2-3.1.noarch

yes, it's a 
  <action type="maintenance_incident">

**Comment by marcus-h** [comment]
Ok - just update your osc to 0.152.0 (it's already in factory) and
it should work (if not, please reopen this ticket again).

**Comment by lnussel** [comment]
i could have sworn I ran zypper up before. Obviously I didn't. New version works indeed. Thanks!
