### ISSUE TITLE
osc up throws exception when `.osc/_in_update/_files` is empty

### ISSUE THREAD

**Issue by wfrisch** [openSUSE/osc#1655]
**Describe the bug**
If `osc up` is interrupted after it created  `.osc/_in_update/_files`, but before writing anything to it, subsequent executions of `osc up` will throw an exception.

**Versions**
```
$ osc version
1.9.2
```

**To Reproduce**
```
osc co openSUSE:Factory/bc
cd $_

# simulate interrupted update
mkdir .osc/_in_update
truncate --size=0 .osc/_in_update/_files

# resume update
osc up
```

**Expected behavior**
`osc` should recover gracefully, as if `.osc/_in_update/_files` did not exist.

**Screenshots, console outputs**
```
$ osc up
resuming broken update...
Traceback (most recent call last):
  File "/usr/bin/osc", line 33, in <module>
    sys.exit(load_entry_point('osc==1.9.2', 'console_scripts', 'osc')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/osc/babysitter.py", line 227, in main
    sys.exit(run(commandline.OscMainCommand()))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/osc/babysitter.py", line 70, in run
    prg.main(argv)
  File "/usr/lib/python3.11/site-packages/osc/commandline.py", line 565, in main
    exit_code = cmd.run(args)
                ^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/osc/commandline.py", line 249, in run
    return cmd.run(args)
           ^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/osc/commandline.py", line 509, in run
    return self.func(args.command, args, *args.positional_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/osc/commandline.py", line 5890, in do_update
    p.update(rev, opts.server_side_source_service_files, opts.limit_size)
  File "/usr/lib/python3.11/site-packages/osc/obs_scm/package.py", line 1392, in update
    root = ET.parse(os.path.join(self.storedir, '_in_update', '_files')).getroot()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/xml/etree/ElementTree.py", line 1219, in parse
    tree.parse(source, parser)
  File "/usr/lib64/python3.11/xml/etree/ElementTree.py", line 581, in parse
    self._root = parser._parse_whole(source)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
xml.etree.ElementTree.ParseError: no element found: line 1, column 0
```

**Additional context**
This was discovered when the SSD controller of the embedded code working group's server, that mirrors numerous code streams, crashed during an osc update.

**Comment by wfrisch** [comment]
Fixed before I found the time to implement a workaround in my script.
Very nice! Thanks!
