### ISSUE TITLE
xml etree parse error on one request's output

### ISSUE THREAD

**Issue by jengelh** [openSUSE/osc#1681]
**Describe the bug**

```
$ osc rq show 1179916

Request:    1179916
Created by: dirkmueller

Actions:
  submit:       devel:libraries:c_c++/libzdb@609fe597ddeaec347367c730173eb020 -> openSUSE:Factory

Message:
  <no message>

State:
  accepted                                                      2024-06-11T16:30:49 anag+factory
    | Staging Project openSUSE:Factory:Staging:adi:33 got accepted.

Review:
  accepted   Group: opensuse-review-team                        2024-06-11T15:43:01 darix
    | Accepted review for by_group opensuse-review-team request 1179916 from user factory-auto
  accepted   Project: openSUSE:Factory:Staging:adi:33           2024-06-11T16:30:48 anag+factory
    | Staging Project openSUSE:Factory:Staging:adi:33 got accepted.
  accepted   Group: factory-staging                             2024-06-11T07:50:39 anag+factory
    | Picked "openSUSE:Factory:Staging:adi:33"
  accepted   User: factory-auto                                 2024-06-11T07:50:55 factory-auto
    | Check script succeeded
  accepted   User: licensedigger                                2024-06-11T09:55:29 licensedigger
    | The legal review is accepted preliminary. The package may require actions later on.

History:
  2024-06-11T16:30:49 anag+factory                   Request got accepted
  2024-06-11T16:30:48 anag+factory                   Request got reviewed
  2024-06-11T16:30:48 anag+factory                   Review got accepted
  2024-06-11T15:43:01 darix                          Review got accepted
  2024-06-11T09:55:29 licensedigger                  Review got accepted
  2024-06-11T07:50:55 factory-auto                   Review got accepted
  2024-06-11T07:50:55 factory-auto                   Request got a new review request
  2024-06-11T07:50:39 anag+factory                   Review got accepted
  2024-06-11T07:50:39 anag+factory                   Request got a new review request
  2024-06-11T07:49:51 dirkmueller                    Request created
Traceback (most recent call last):
  File "/usr/bin/osc", line 33, in <module>
    sys.exit(load_entry_point('osc==1.10.1', 'console_scripts', 'osc')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/osc/babysitter.py", line 227, in main
    sys.exit(run(commandline.OscMainCommand()))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/osc/babysitter.py", line 70, in run
    prg.main(argv)
  File "/usr/lib/python3.11/site-packages/osc/commandline.py", line 296, in main
    exit_code = cmd.run(args)
                ^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/osc/commandline_common.py", line 214, in run
    return cmd.run(args)
           ^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/osc/commandline.py", line 240, in run
    return self.func(args.command, args, *args.positional_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/osc/commandline.py", line 3213, in do_request
    print_comments(apiurl, 'request', reqid)
  File "/usr/lib/python3.11/site-packages/osc/core.py", line 6254, in print_comments
    root = get_comments(apiurl, kind, *args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/osc/core.py", line 6242, in get_comments
    return ET.parse(f).getroot()
           ^^^^^^^^^^^
  File "/usr/lib64/python3.11/xml/etree/ElementTree.py", line 1219, in parse
    tree.parse(source, parser)
  File "/usr/lib64/python3.11/xml/etree/ElementTree.py", line 581, in parse
    self._root = parser._parse_whole(source)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 4, column 61
```

**Versions**
- Operating system: openSUSE TW 20241226
- Packages: osc-1.10.1

**Expected behavior**

If possible, give a more user-readable error description.

**Comment by dmach** [comment]
@jengelh I've submitted a PR that should fix this by displaying a snippet of the broken XML.

Example output:
```
$ osc rq show 1179916
...
xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 4, column 61:  0x1B[38mDISABLED0x1B[m0x0F      |```</comment>
```

It seems there are unescaped control characters in the retrieved XML.
Osc converts them to hex and highlights with red background.
