### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'keys'

### ISSUE THREAD

**Issue by andreasstieger** [openSUSE/osc#203]
```
$ rpm -q osc
osc-0.152.0-3.2.noarch
$ osc api '/search/channel/binary?match=[@package="gpg2"+and+@project="SUSE:Channels"+and+not(target/disabled)]'
```

<collection matches="0">

Problematic just now is devel:tools:scm/osc ...

```
$ rpm -q osc
osc-0.154.git20160531.2364a08-519.1.noarch
$ osc -A https://api.suse.de/ api '/search/channel/binary?match=[@package="gpg2"+and+@project="SUSE:Channels"+and+not(target/disabled)]'
Traceback (most recent call last):
  File "/usr/bin/osc", line 41, in <module>
    r = babysitter.run(osccli)
  File "/usr/lib/python2.7/site-packages/osc/babysitter.py", line 61, in run
    return prg.main(argv)
  File "/usr/lib/python2.7/site-packages/osc/cmdln.py", line 343, in main
    return self.cmd(args)
  File "/usr/lib/python2.7/site-packages/osc/cmdln.py", line 366, in cmd
    retval = self.onecmd(argv)
  File "/usr/lib/python2.7/site-packages/osc/cmdln.py", line 500, in onecmd
    return self._dispatch_cmd(handler, argv)
  File "/usr/lib/python2.7/site-packages/osc/cmdln.py", line 1230, in _dispatch_cmd
    return handler(argv[0], opts, *args)
  File "/usr/lib/python2.7/site-packages/osc/commandline.py", line 7309, in do_api
    headers=opts.headers)
  File "/usr/lib/python2.7/site-packages/osc/core.py", line 3218, in http_request
    for i in headers.keys():
AttributeError: 'NoneType' object has no attribute 'keys'
```

I am pretty sure that 0.154.git20160422.8466e49-0 was a working version.

**Comment by andreasstieger** [comment]
@marcus-h This is from c53a7681ef289181b03e1077efbfd246bf1247f6

**Comment by marcus-h** [comment]
On 2016-05-31 08:24:50 -0700, Andreas Stieger wrote:
> @marcus-h This is from c53a7681ef289181b03e1077efbfd246bf1247f6
> 
I just reverted this commit for now, because it causes some more
severe issues (see issue #202). My plan is to reconsider commit
c53a7681ef289181b03e1077efbfd246bf1247f6, once issue #202 is
resolved. Hence, I won't close this for now (so that I won't
forget to take care of it).
Thanks for the report and your pulls requests (much appreciated!).

**Comment by andreasstieger** [comment]
We could collect c53a7681ef289181b03e1077efbfd246bf1247f6, 93450de6e749b107dbb62c66187ba69f1dd76ffe in a branch and run CI on it?

**Comment by lethliel** [comment]
This works now and this issue can be closed
