### ISSUE TITLE
Building in a new branch without trust of "upstream" not possible

### ISSUE THREAD

**Issue by zaitor** [openSUSE/osc#268]
bjolie@drude:~/build/home:Zaitor:branches:multimedia:libs> cd gstreamer-transcoder/
bjolie@drude:~/build/home:Zaitor:branches:multimedia:libs/gstreamer-transcoder> osc build --clean
Run source service: /usr/lib/obs/service/format_spec_file --outdir /home/bjolie/build/home:Zaitor:branches:multimedia:libs/gstreamer-transcoder/tmpFcHk_l.format_spec_file.service
Run source service: /usr/lib/obs/service/source_validator --outdir /home/bjolie/build/home:Zaitor:branches:multimedia:libs/gstreamer-transcoder/tmpK3WfPp.source_validator.service
Building gstreamer-transcoder.spec for openSUSE_Tumbleweed/x86_64
Getting buildinfo from server and store to /home/bjolie/build/home:Zaitor:branches:multimedia:libs/gstreamer-transcoder/.osc/_buildinfo-openSUSE_Tumbleweed-x86_64.xml
Getting buildconfig from server and store to /home/bjolie/build/home:Zaitor:branches:multimedia:libs/gstreamer-transcoder/.osc/_buildconfig-openSUSE_Tumbleweed-x86_64
Updating cache of required packages

The build root needs packages from project 'multimedia:libs'.
Note that malicious packages can compromise the build result or even your system.
Would you like to ...
0 - quit (default)
1 - always trust packages from 'multimedia:libs'
2 - trust packages just this time
? Traceback (most recent call last):
  File "/usr/bin/osc", line 41, in <module>
    r = babysitter.run(osccli)
  File "/usr/lib/python2.7/site-packages/osc/babysitter.py", line 61, in run
    return prg.main(argv)
  File "/usr/lib/python2.7/site-packages/osc/cmdln.py", line 343, in main
    return self.cmd(args)
  File "/usr/lib/python2.7/site-packages/osc/cmdln.py", line 366, in cmd
    retval = self.onecmd(argv)
  File "/usr/lib/python2.7/site-packages/osc/cmdln.py", line 500, in onecmd
    return self._dispatch_cmd(handler, argv)
  File "/usr/lib/python2.7/site-packages/osc/cmdln.py", line 1230, in _dispatch_cmd
    return handler(argv[0], opts, *args)
  File "/usr/lib/python2.7/site-packages/osc/commandline.py", line 5969, in do_build
    return osc.build.main(self.get_api_url(), opts, args)
  File "/usr/lib/python2.7/site-packages/osc/build.py", line 855, in main
    check_trusted_projects(apiurl, [ i for i in bi.projects.keys() if not i == prj ])
  File "/usr/lib/python2.7/site-packages/osc/build.py", line 473, in check_trusted_projects
    r = raw_input(trustprompt % { 'project': prj })
  File "/usr/lib/python2.7/site-packages/osc/core.py", line 7261, in raw_input
    return func(*args)
IOError: [Errno 11] Resource temporarily unavailable
bjolie@drude:~/build/home:Zaitor:branches:multimedia:libs/gstreamer-transcoder>

**Comment by dmach** [comment]
I believe osc no longer throws tracebacks like this.
Also, the issue is over 5 years old. Closing.
If the problem still occurs, please open a new issue.
