### ISSUE TITLE
osc build fails when building kiwi images with imageonly repositories

### ISSUE THREAD

**Issue by Vogtinator** [openSUSE/osc#388]
```
<repository imageonly="true" alias="ibreakstuff">
    <source path="http://innocent.url"/>
</repository>
```

results in:

```
Traceback (most recent call last):
  File "/usr/bin/osc", line 41, in <module>
    r = babysitter.run(osccli)
  File "/usr/lib/python2.7/site-packages/osc/babysitter.py", line 61, in run
    return prg.main(argv)
  File "/usr/lib/python2.7/site-packages/osc/cmdln.py", line 344, in main
    return self.cmd(args)
  File "/usr/lib/python2.7/site-packages/osc/cmdln.py", line 367, in cmd
    retval = self.onecmd(argv)
  File "/usr/lib/python2.7/site-packages/osc/cmdln.py", line 501, in onecmd
    return self._dispatch_cmd(handler, argv)
  File "/usr/lib/python2.7/site-packages/osc/cmdln.py", line 1232, in _dispatch_cmd
    return handler(argv[0], opts, *args)
  File "/usr/lib/python2.7/site-packages/osc/commandline.py", line 6227, in do_build
    return osc.build.main(self.get_api_url(), opts, args)
  File "/usr/lib/python2.7/site-packages/osc/build.py", line 1078, in main
    project=m.group(1).replace(":", ":/")
AttributeError: 'NoneType' object has no attribute 'group'
```

**Comment by adrianschroeter** [comment]
On Freitag, 2. März 2018, 10:46:59 CET wrote Fabian Vogt:
> ```
> <repository imageonly="true" alias="ibreakstuff">
>     <source path="http://innocent.url"/>

you use a URL which can not be mapped by OBS to an OBS project/repo ?

this can not work indeed .... osc should report a nicer error
instead of a crash though ....

-- 

Adrian Schroeter
email: adrian@suse.de

SUSE Linux GmbH, GF: Felix Imendörffer, Jane Smithard, Graham Norton, HRB 21284 (AG Nürnberg) 
 
Maxfeldstraße 5                         
90409 Nürnberg 
Germany

**Comment by Vogtinator** [comment]
imageonly means it's only included in the image, not used as a package source.

**Comment by adrianschroeter** [comment]
On Freitag, 2. März 2018, 10:58:20 CET wrote Fabian Vogt:
> imageonly means it's only included in the image, not used as a package source.

true...

-- 

Adrian Schroeter
email: adrian@suse.de

SUSE Linux GmbH, GF: Felix Imendörffer, Jane Smithard, Graham Norton, HRB 21284 (AG Nürnberg) 
 
Maxfeldstraße 5                         
90409 Nürnberg 
Germany
