### ISSUE TITLE
osc commit fails with SyntaxError: expected path separator

### ISSUE THREAD

**Issue by non7top** [openSUSE/osc#391]
---> Package osc.i686 0:0.152.0-172.1 will be updated
---> Package osc.noarch 0:0.162.1-230.1 will be an update

```
$ osc commit -m "fuse"
Sending    fuse/fusermount.patch
Transmitting file data Traceback (most recent call last):
  File "/usr/bin/osc", line 41, in <module>
    r = babysitter.run(osccli)
  File "/usr/lib/python2.6/site-packages/osc/babysitter.py", line 61, in run
    return prg.main(argv)
  File "/usr/lib/python2.6/site-packages/osc/cmdln.py", line 344, in main
    return self.cmd(args)
  File "/usr/lib/python2.6/site-packages/osc/cmdln.py", line 367, in cmd
    retval = self.onecmd(argv)
  File "/usr/lib/python2.6/site-packages/osc/cmdln.py", line 501, in onecmd
    return self._dispatch_cmd(handler, argv)
  File "/usr/lib/python2.6/site-packages/osc/cmdln.py", line 1232, in _dispatch_cmd
    return handler(argv[0], opts, *args)
  File "/usr/lib/python2.6/site-packages/osc/commandline.py", line 4612, in do_commit
    self._commit(subcmd, opts, args)
  File "/usr/lib/python2.6/site-packages/osc/commandline.py", line 4658, in _commit
    prj.commit(msg=msg, skip_local_service_run=skip_local_service_run, verbose=opts.verbose, can_branch=can_branch)
  File "/usr/lib/python2.6/site-packages/osc/core.py", line 1003, in commit
    Package(os.path.join(self.dir, pac)).commit(msg, verbose=verbose, skip_local_service_run=skip_local_service_run)
  File "/usr/lib/python2.6/site-packages/osc/core.py", line 1504, in commit
    if sfilelist.get('error') and sfilelist.findall('.//entry[@hash]'):
  File "/usr/lib/python2.6/xml/etree/ElementPath.py", line 198, in findall
    return _compile(path).findall(element)
  File "/usr/lib/python2.6/xml/etree/ElementPath.py", line 176, in _compile
    p = Path(path)
  File "/usr/lib/python2.6/xml/etree/ElementPath.py", line 93, in __init__
    "expected path separator (%s)" % (op or tag)
SyntaxError: expected path separator ([)
```

**Comment by marcus-h** [comment]
On 2018-03-07 23:39:52 +0000, non7top wrote:
>   File "/usr/lib/python2.6/site-packages/osc/core.py", line 1504, in commit
>     if sfilelist.get('error') and sfilelist.findall('.//entry[@hash]'):
>   File "/usr/lib/python2.6/xml/etree/ElementPath.py", line 198, in findall
>     return _compile(path).findall(element)
>   File "/usr/lib/python2.6/xml/etree/ElementPath.py", line 176, in _compile
>     p = Path(path)
>   File "/usr/lib/python2.6/xml/etree/ElementPath.py", line 93, in __init__
>     "expected path separator (%s)" % (op or tag)
> SyntaxError: expected path separator ([)

@lethliel already fixed it in commit e017a8e => closing.
