### ISSUE TITLE
"osc buildhistory" crashes trying to parse invalid response from OBS

### ISSUE THREAD

**Issue by peti** [openSUSE/osc#408]
`osc buildhistory` crashes trying to parse invalid response from OBS:

~~~
osc -A https://api.suse.de buildhistory SUSE:SLE-11-SP2:GA pam-config standard s390
Traceback (most recent call last):
  File "/nix/store/vpf1v0wi5lh8siw85hil0f9jjjgcbpwd-python2.7-osc-0.159.0-4-g2d44589/bin/.osc-wrapper.py-wrapped", line 42, in <module>
    r = babysitter.run(osccli)
  File "/nix/store/13xnax7fpmcpmqkqwim1m8adqa6ih5av-python-2.7.14-env/lib/python2.7/site-packages/osc/babysitter.py", line 61, in run
    return prg.main(argv)
  File "/nix/store/13xnax7fpmcpmqkqwim1m8adqa6ih5av-python-2.7.14-env/lib/python2.7/site-packages/osc/cmdln.py", line 344, in main
    return self.cmd(args)
  File "/nix/store/13xnax7fpmcpmqkqwim1m8adqa6ih5av-python-2.7.14-env/lib/python2.7/site-packages/osc/cmdln.py", line 367, in cmd
    retval = self.onecmd(argv)
  File "/nix/store/13xnax7fpmcpmqkqwim1m8adqa6ih5av-python-2.7.14-env/lib/python2.7/site-packages/osc/cmdln.py", line 501, in onecmd
    return self._dispatch_cmd(handler, argv)
  File "/nix/store/13xnax7fpmcpmqkqwim1m8adqa6ih5av-python-2.7.14-env/lib/python2.7/site-packages/osc/cmdln.py", line 1232, in _dispatch_cmd
    return handler(argv[0], opts, *args)
  File "/nix/store/13xnax7fpmcpmqkqwim1m8adqa6ih5av-python-2.7.14-env/lib/python2.7/site-packages/osc/commandline.py", line 6395, in do_buildhistory
    print('\n'.join(get_buildhistory(apiurl, project, package, repository, arch, format, opts.limit)))
  File "/nix/store/13xnax7fpmcpmqkqwim1m8adqa6ih5av-python-2.7.14-env/lib/python2.7/site-packages/osc/core.py", line 6036, in get_buildhistory
    t = time.gmtime(int(node.get('time')))
ValueError: invalid literal for int() with base 10: 'e5af2afe3b22e282425e28e91a9e74a5'
~~~

What happens is that the server mysteriously feels like throwing the line

~~~
  <entry rev="38" srcmd5="e5af2afe3b22e282425e28e91a9e74a0.79-5" versrel="0.79-5" bcnt="31" time="e5af2afe3b22e282425e28e91a9e74a5" duration="3" />
~~~

into its response, which then takes down the whole `osc` process. Now, I realize that the server isn't behaving properly here, but still it's somewhat bad that this single bad record prevents me from using the query at all.

**Comment by adrianschroeter** [comment]
On Freitag, 20. April 2018, 13:14:49 CEST wrote Peter Simons:
> `osc buildhistory` crashes trying to parse invalid response from OBS:
> 
> ~~~
> osc -A https://api.suse.de buildhistory SUSE:SLE-11-SP2:GA pam-config standard s390
> Traceback (most recent call last):
>   File "/nix/store/vpf1v0wi5lh8siw85hil0f9jjjgcbpwd-python2.7-osc-0.159.0-4-g2d44589/bin/.osc-wrapper.py-wrapped", line 42, in <module>
>     r = babysitter.run(osccli)
>   File "/nix/store/13xnax7fpmcpmqkqwim1m8adqa6ih5av-python-2.7.14-env/lib/python2.7/site-packages/osc/babysitter.py", line 61, in run
>     return prg.main(argv)
>   File "/nix/store/13xnax7fpmcpmqkqwim1m8adqa6ih5av-python-2.7.14-env/lib/python2.7/site-packages/osc/cmdln.py", line 344, in main
>     return self.cmd(args)
>   File "/nix/store/13xnax7fpmcpmqkqwim1m8adqa6ih5av-python-2.7.14-env/lib/python2.7/site-packages/osc/cmdln.py", line 367, in cmd
>     retval = self.onecmd(argv)
>   File "/nix/store/13xnax7fpmcpmqkqwim1m8adqa6ih5av-python-2.7.14-env/lib/python2.7/site-packages/osc/cmdln.py", line 501, in onecmd
>     return self._dispatch_cmd(handler, argv)
>   File "/nix/store/13xnax7fpmcpmqkqwim1m8adqa6ih5av-python-2.7.14-env/lib/python2.7/site-packages/osc/cmdln.py", line 1232, in _dispatch_cmd
>     return handler(argv[0], opts, *args)
>   File "/nix/store/13xnax7fpmcpmqkqwim1m8adqa6ih5av-python-2.7.14-env/lib/python2.7/site-packages/osc/commandline.py", line 6395, in do_buildhistory
>     print('\n'.join(get_buildhistory(apiurl, project, package, repository, arch, format, opts.limit)))
>   File "/nix/store/13xnax7fpmcpmqkqwim1m8adqa6ih5av-python-2.7.14-env/lib/python2.7/site-packages/osc/core.py", line 6036, in get_buildhistory
>     t = time.gmtime(int(node.get('time')))
> ValueError: invalid literal for int() with base 10: 'e5af2afe3b22e282425e28e91a9e74a5'

the crash for an invalid response is absolute okay.


-- 

Adrian Schroeter
email: adrian@suse.de

SUSE Linux GmbH, GF: Felix Imendörffer, Jane Smithard, Graham Norton, HRB 21284 (AG Nürnberg) 
 
Maxfeldstraße 5                         
90409 Nürnberg 
Germany

**Comment by dmach** [comment]
Agreed, such crashes are ok as they happen only when something truly unexpected happens and we have a benefit of having more than just a plain error message.
