### ISSUE TITLE
Now requires python2-pyOpenSSL

### ISSUE THREAD

**Issue by jberry-suse** [openSUSE/osc#429]
Not sure if related to b730f880cfe85a8547f569355a21706f27ebfa78 as the only ssl related change recently or the [last python update in TW](https://build.opensuse.org/request/show/611151), but `zypper in osc` now results in the following error without `python2-pyOpenSSL`.

```
$ osc checkout openSUSE:Tools/openSUSE-release-tools
Traceback (most recent call last):
  File "/usr/bin/osc", line 10, in <module>
    from osc import commandline, babysitter
  File "/usr/lib/python2.7/site-packages/osc/commandline.py", line 9, in <module>
    from . import conf
  File "/usr/lib/python2.7/site-packages/osc/conf.py", line 44, in <module>
    import ssl
ImportError: No module named ssl
```

This broke our CI. Please either add a requires on that package of resolve the issue some other way. Thanks.

**Comment by jberry-suse** [comment]
Verified this does not occur when using TW snapshot `20180502` (just went back a month or so to verify).

**Comment by lethliel** [comment]
That's strange. I am using TW snapshot "20180606" and it works without python2-pyOpenSSL installed. 

```
lethliel@linux-88l9:~/obs> zypper se python | grep pyOpenSSL
   | python-pyOpenSSL-doc                                    | Documentation for python-pyOpenSSL                                                    | package    
   | python2-pyOpenSSL                                       | Python wrapper module around the OpenSSL library                                      | package    
   | python2-service_identity                                | Service identity verification for pyOpenSSL                                           | package    
   | python3-pyOpenSSL                                       | Python wrapper module around the OpenSSL library                                      | package    
   | python3-service_identity                                | Service identity verification for pyOpenSSL                                           | package
```

```
lethliel@linux-88l9:~/obs> osc co openSUSE:Tools/openSUSE-release-tools
A    openSUSE:Tools
A    openSUSE:Tools/openSUSE-release-tools
A    openSUSE:Tools/openSUSE-release-tools/_service
A    openSUSE:Tools/openSUSE-release-tools/_servicedata
A    openSUSE:Tools/openSUSE-release-tools/openSUSE-release-tools-20180614.3b99137.obscpio
A    openSUSE:Tools/openSUSE-release-tools/openSUSE-release-tools.changes
A    openSUSE:Tools/openSUSE-release-tools/openSUSE-release-tools.obsinfo
A    openSUSE:Tools/openSUSE-release-tools/openSUSE-release-tools.spec
At revision 98441f9d4fb3ae11bf658460948f8630.
```

But I will try with a clean install of TW with the current snapshot and see If I can reproduce your problem.

**Comment by lethliel** [comment]
I made a clean install of tumbleweed (latest snapshot).

- zypper in osc
- osc co openSUSE:Tools/openSUSE-release-tools

No problems. 

Nevertheless I investigated the docker container you are using. The problem is that `ssl.py` is missing in 
`/usr/lib64/python2.7/`

If I do a manual install of a base server system with tumbleweed and install osc `ssl.py` is there. 

So perhaps the image is borked?

**Comment by lethliel** [comment]
And here is what package should contain the ssl.py file (on a freshly installed tumbleweed):

```
marco@linux-kize:~> rpm -qf /usr/lib64/python2.7/ssl.py
python-2.7.15-1.1.x86_64
```

**Comment by lethliel** [comment]
Ok. Found the reason. (It is an osc bug)

When you install osc **only** python-base is required. And ssl.py is not included in python-base.

A `Requires: python2` solves the problem.

**Comment by jberry-suse** [comment]
Verified that `zypper in python2` in fresh TW container works. I assume you'll update the package on OBS?

**Comment by lethliel** [comment]
Yes. I will update the package in OBS...

**Comment by lethliel** [comment]
opened bug https://bugzilla.opensuse.org/show_bug.cgi?id=1097996 for this. 
Package update will follow this week.

**Comment by jberry-suse** [comment]
bump

**Comment by lethliel** [comment]
The new requires is now in the package and already submitted to factory.
