### ISSUE TITLE
NameError in SSL-Requests with Python3.6

### ISSUE THREAD

**Issue by crazyscientist** [openSUSE/osc#433]
After building/installing the current content of the `python3` branch the command
```osc-py3-wrapper.py whois apritschet```
raises the following exceptions:
```Traceback (most recent call last):
  File "/home/andip/virtualenvs/p3osc/lib/python3.6/site-packages/osc-0.162.1git-py3.6.egg/osc/babysitter.py", line 61, in run
  File "/home/andip/virtualenvs/p3osc/lib/python3.6/site-packages/osc-0.162.1git-py3.6.egg/osc/cmdln.py", line 344, in main
  File "/home/andip/virtualenvs/p3osc/lib/python3.6/site-packages/osc-0.162.1git-py3.6.egg/osc/cmdln.py", line 367, in cmd
  File "/home/andip/virtualenvs/p3osc/lib/python3.6/site-packages/osc-0.162.1git-py3.6.egg/osc/cmdln.py", line 501, in onecmd
  File "/home/andip/virtualenvs/p3osc/lib/python3.6/site-packages/osc-0.162.1git-py3.6.egg/osc/cmdln.py", line 1232, in _dispatch_cmd
  File "/home/andip/virtualenvs/p3osc/lib/python3.6/site-packages/osc-0.162.1git-py3.6.egg/osc/commandline.py", line 8188, in do_whois
  File "/home/andip/virtualenvs/p3osc/lib/python3.6/site-packages/osc-0.162.1git-py3.6.egg/osc/core.py", line 4603, in get_user_data
  File "/home/andip/virtualenvs/p3osc/lib/python3.6/site-packages/osc-0.162.1git-py3.6.egg/osc/core.py", line 4581, in get_user_meta
  File "/home/andip/virtualenvs/p3osc/lib/python3.6/site-packages/osc-0.162.1git-py3.6.egg/osc/core.py", line 3373, in http_GET
  File "/home/andip/virtualenvs/p3osc/lib/python3.6/site-packages/osc-0.162.1git-py3.6.egg/osc/core.py", line 3362, in http_request
  File "/usr/lib64/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib64/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/usr/lib64/python3.6/urllib/request.py", line 544, in _open
    '_open', req)
  File "/usr/lib64/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/home/andip/virtualenvs/p3osc/lib/python3.6/site-packages/osc-0.162.1git-py3.6.egg/osc/oscssl.py", line 222, in https_open
NameError: name 'selector' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/andip/virtualenvs/p3osc/bin/osc-py3-wrapper.py", line 4, in <module>
    __import__('pkg_resources').run_script('osc===0.162.1git', 'osc-py3-wrapper.py')
  File "/home/andip/virtualenvs/p3osc/lib/python3.6/site-packages/pkg_resources/__init__.py", line 657, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/andip/virtualenvs/p3osc/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1444, in run_script
    exec(script_code, namespace, namespace)
  File "/home/andip/virtualenvs/p3osc/lib/python3.6/site-packages/osc-0.162.1git-py3.6.egg/EGG-INFO/scripts/osc-py3-wrapper.py", line 41, in <module>
  File "/home/andip/virtualenvs/p3osc/lib/python3.6/site-packages/osc-0.162.1git-py3.6.egg/osc/babysitter.py", line 173, in run
TypeError: catching classes that do not inherit from BaseException is not allowed
```

The first exception can actually be fixed by replacing `selector` by `request_uri` in `osc/oscssl.py` in line 222.

**Comment by crazyscientist** [comment]
I would have created a pull request for my commit fc37d526b4516f0769a75d110712f66f81007c99, but it appears I have no permission...

**Comment by lethliel** [comment]
@crazyscientist Thank you very much for the hint. I changed the line according to your commit.
