### ISSUE TITLE
[python3] cannot set maintainer of a package

### ISSUE THREAD

**Issue by mcepl** [openSUSE/osc#452]
```
matej@milic: Twisted-18.7.0$ osc maintainer -a mcepl -s mcepl devel:languages:lua lua51-bit32
Traceback (most recent call last):
  File "/home/matej/.local/bin/osc", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/home/matej/archiv/knihovna/repos/osc/osc-py3-wrapper.py", line 41, in <module>
    r = babysitter.run(osccli)
  File "/home/matej/archiv/knihovna/repos/osc/osc/babysitter.py", line 61, in run
    return prg.main(argv)
  File "/home/matej/archiv/knihovna/repos/osc/osc/cmdln.py", line 344, in main
    return self.cmd(args)
  File "/home/matej/archiv/knihovna/repos/osc/osc/cmdln.py", line 367, in cmd
    retval = self.onecmd(argv)
  File "/home/matej/archiv/knihovna/repos/osc/osc/cmdln.py", line 501, in onecmd
    return self._dispatch_cmd(handler, argv)
  File "/home/matej/archiv/knihovna/repos/osc/osc/cmdln.py", line 1232, in _dispatch_cmd
    return handler(argv[0], opts, *args)
  File "/home/matej/archiv/knihovna/repos/osc/osc/commandline.py", line 8030, in do_maintainer
    addPerson(apiurl, prj, pac, opts.add, role)
  File "/home/matej/archiv/knihovna/repos/osc/osc/core.py", line 6897, in addPerson
    root = ET.fromstring(''.join(data))
TypeError: sequence item 0: expected str instance, bytes found
```

**Comment by lethliel** [comment]
Thanks for the report. I will fix this.

**Comment by lethliel** [comment]
fixed in https://github.com/openSUSE/osc/commit/a9fc04d9968f1a706b5f33a271f2cc8d368bdc0a
