### ISSUE TITLE
Missing progress bar in getbinaries (python3)

### ISSUE THREAD

**Issue by mcepl** [openSUSE/osc#499]
```
matej@milic: rpms$ osc getbinaries Virtualization libvirt openSUSE_Factory x86_64
Creating binaries
Traceback (most recent call last):
  File "/home/matej/.local/bin/osc", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/home/matej/archiv/knihovna/repos/osc/osc-py3-wrapper.py", line 41, in <module>
    r = babysitter.run(osccli)
  File "/home/matej/archiv/knihovna/repos/osc/osc/babysitter.py", line 61, in run
    return prg.main(argv)
  File "/home/matej/archiv/knihovna/repos/osc/osc/cmdln.py", line 344, in main
    return self.cmd(args)
  File "/home/matej/archiv/knihovna/repos/osc/osc/cmdln.py", line 367, in cmd
    retval = self.onecmd(argv)
  File "/home/matej/archiv/knihovna/repos/osc/osc/cmdln.py", line 501, in onecmd
    return self._dispatch_cmd(handler, argv)
  File "/home/matej/archiv/knihovna/repos/osc/osc/cmdln.py", line 1232, in _dispatch_cmd
    return handler(argv[0], opts, *args)
  File "/home/matej/archiv/knihovna/repos/osc/osc/commandline.py", line 7188, in do_getbinaries
    progress_meter = not opts.quiet)
  File "/home/matej/archiv/knihovna/repos/osc/osc/core.py", line 4659, in get_binary_file
    from .meter import TextMeter
  File "/home/matej/archiv/knihovna/repos/osc/osc/meter.py", line 6, in <module>
    import progressbar as pb
ModuleNotFoundError: No module named 'progressbar'
```

**Comment by lethliel** [comment]
You need to install python3-progressbar. 
You use the python3 branch?

**Comment by mcepl** [comment]
Oh, I see, I thought that it is a leftover from python2. Yes, I (happily) use python3 branch.

**Comment by lethliel** [comment]
As master and the python3 branch share the same code for progressbar generation since https://github.com/openSUSE/osc/commit/65b053abb3b5771303ec998a813d600e2a776ab6 it is also a issue for the master branch. 

I fixed it with this https://github.com/openSUSE/osc/commit/4a28448e14368d7aa66ec5afb541a7b48d5f145d for the python3 branch. The same will go into master. 

@mcepl 
So now osc does not crash. It will warn the user that python-progressbar needs to be installed and continue without the display of a progress bar.
