### ISSUE TITLE
osc add bytes/str issue [Python 3]

### ISSUE THREAD

**Issue by mcepl** [openSUSE/osc#507]
```
matej@stitny: neovim$ osc add git://github.com/neovim/neovim.git
Traceback (most recent call last):
  File "/home/matej/.local/bin/osc", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/home/matej/archiv/knihovna/repos/osc/osc-py3-wrapper.py", line 41, in <module>
    r = babysitter.run(osccli)
  File "/home/matej/archiv/knihovna/repos/osc/osc/babysitter.py", line 60, in run
    return prg.main(argv)
  File "/home/matej/archiv/knihovna/repos/osc/osc/cmdln.py", line 344, in main
    return self.cmd(args)
  File "/home/matej/archiv/knihovna/repos/osc/osc/cmdln.py", line 367, in cmd
    retval = self.onecmd(argv)
  File "/home/matej/archiv/knihovna/repos/osc/osc/cmdln.py", line 501, in onecmd
    return self._dispatch_cmd(handler, argv)
  File "/home/matej/archiv/knihovna/repos/osc/osc/cmdln.py", line 1232, in _dispatch_cmd
    return handler(argv[0], opts, *args)
  File "/home/matej/archiv/knihovna/repos/osc/osc/commandline.py", line 4573, in do_add
    addGitSource(arg)
  File "/home/matej/archiv/knihovna/repos/osc/osc/core.py", line 7062, in addGitSource
    f.write(ET.tostring(s, encoding=ET_ENCODING))
TypeError: a bytes-like object is required, not 'str'
matej@stitny: neovim$
```

**Comment by ismail** [comment]
This seems to be fixed on master now.

**Comment by lethliel** [comment]
nope. This is not fixed.

**Comment by lethliel** [comment]
now it is fixed :-)
