### ISSUE TITLE
TypeError: endheaders() takes exactly 1 argument (2 given)

### ISSUE THREAD

**Issue by andreas-schwab** [openSUSE/osc#536]
Traceback (most recent call last):
  File "/usr/bin/osc", line 41, in <module>
    r = babysitter.run(osccli)
  File "/usr/lib/python2.7/site-packages/osc/babysitter.py", line 61, in run
    return prg.main(argv)
  File "/usr/lib/python2.7/site-packages/osc/cmdln.py", line 344, in main
    return self.cmd(args)
  File "/usr/lib/python2.7/site-packages/osc/cmdln.py", line 367, in cmd
    retval = self.onecmd(argv)
  File "/usr/lib/python2.7/site-packages/osc/cmdln.py", line 501, in onecmd
    return self._dispatch_cmd(handler, argv)
  File "/usr/lib/python2.7/site-packages/osc/cmdln.py", line 1232, in _dispatch_cmd
    return handler(argv[0], opts, *args)
  File "/usr/lib/python2.7/site-packages/osc/commandline.py", line 412, in do_list
    for pkg in meta_get_packagelist(apiurl, project, deleted = opts.deleted, expand = opts.expand):
  File "/usr/lib/python2.7/site-packages/osc/core.py", line 3430, in meta_get_packagelist
    f = http_GET(u)
  File "/usr/lib/python2.7/site-packages/osc/core.py", line 3387, in http_GET
    def http_GET(*args, **kwargs):    return http_request('GET', *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/osc/core.py", line 3376, in http_request
    fd = urlopen(req, data=data)
  File "/usr/lib64/python2.7/urllib2.py", line 127, in urlopen                  
    return _opener.open(url, data, timeout)                                     
  File "/usr/lib64/python2.7/urllib2.py", line 404, in open                     
    response = self._open(req, data)                                            
  File "/usr/lib64/python2.7/urllib2.py", line 422, in _open                    
    '_open', req)                                                               
  File "/usr/lib64/python2.7/urllib2.py", line 382, in _call_chain              
    result = func(*args)                                                        
  File "/usr/lib/python2.7/site-packages/osc/oscssl.py", line 222, in https_open
    h.request(req.get_method(), request_uri, req.data, headers)                 
  File "/usr/lib64/python2.7/httplib.py", line 973, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib64/python2.7/httplib.py", line 1007, in _send_request
    self.endheaders(body)
TypeError: endheaders() takes exactly 1 argument (2 given)

**Comment by lethliel** [comment]
What was the command you issued?

**Comment by andreas-schwab** [comment]
osc ls .

**Comment by lethliel** [comment]
I cannot reproduce this error. Neither with the python3 version nor with the current python2 version. 

Can you please provide the following information: 

osc version (osc --version) 
OS Version

**Comment by andreas-schwab** [comment]
# zypper in privoxy
# systemctl start privoxy
$ https_proxy=localhost:8118 osc ls .

**Comment by lethliel** [comment]
I get errors when using the python3 version of osc. Related to https://github.com/openSUSE/osc/issues/534
But using Leap 15.0 with osc-0.165.0 (using the python2 version) with the fix for https://github.com/openSUSE/osc/issues/534 in https://github.com/openSUSE/osc/pull/538 works fine.

**Comment by andreas-schwab** [comment]
Try that on 13.2.

**Comment by lethliel** [comment]
osc 0.165.0 on 13.2 is not really supported.

**Comment by lethliel** [comment]
proxy handling was fixed
