### ISSUE TITLE
[py3] get_commitlog() explodes when format is xml

### ISSUE THREAD

**Issue by jberry-suse** [openSUSE/osc#545]
An example:

```
# osc origin -p openSUSE:Leap:15.1 package adminer
Traceback (most recent call last):
  File "/usr/bin/osc", line 41, in <module>
    r = babysitter.run(osccli)
  File "/usr/lib/python3.7/site-packages/osc/babysitter.py", line 61, in run
    return prg.main(argv)
  File "/usr/lib/python3.7/site-packages/osc/cmdln.py", line 344, in main
    return self.cmd(args)
  File "/usr/lib/python3.7/site-packages/osc/cmdln.py", line 367, in cmd
    retval = self.onecmd(argv)
  File "/usr/lib/python3.7/site-packages/osc/cmdln.py", line 501, in onecmd
    return self._dispatch_cmd(handler, argv)
  File "/usr/lib/python3.7/site-packages/osc/cmdln.py", line 1232, in _dispatch_cmd
    return handler(argv[0], opts, *args)
  File "/root/.osc-plugins/osc-origin.py", line 82, in do_origin
    globals()[function](apiurl, opts, *args[1:])
  File "/root/.osc-plugins/osc-origin.py", line 202, in osrt_origin_package
    origin_info = origin_find(apiurl, opts.project, packages[0])
  File "/root/.osc-plugins/osclib/memoize.py", line 161, in _fn
    value = fn(*args, **kwargs)
  File "/root/.osc-plugins/osclib/origin.py", line 212, in origin_find
    if project_source_contain(apiurl, origin, package, source_hash):
  File "/root/.osc-plugins/osclib/origin.py", line 239, in project_source_contain
    for source_hash_consider in package_source_hash_history(apiurl, project, package):
  File "/root/.osc-plugins/osclib/core.py", line 546, in package_source_hash_history
    get_commitlog(apiurl, project, package, None, format='xml'))
  File "/usr/lib/python3.7/site-packages/osc/core.py", line 6340, in get_commitlog
    comment.replace('&', '&amp;').replace('<', '&gt;').replace('>', '&lt;'))
TypeError: a bytes-like object is required, not 'str'
```

**Comment by jberry-suse** [comment]
blocks openSUSE/openSUSE-release-tools#1758

**Comment by lethliel** [comment]
Will fix this when i am back from vacation (Wednesday)

**Comment by lethliel** [comment]
This is the same as https://github.com/openSUSE/osc/issues/544. This will be closed as duplicate.
