### ISSUE TITLE
triggerreason unhandled exception on empty package

### ISSUE THREAD

**Issue by AdamMajer** [openSUSE/osc#546]
This maybe a little pedantic, but running triggerreason on newly created packages result in unhandled exception instead of nothing.

```
osc triggerreason  devel:languages:nodejs/nodejs12 openSUSE_Tumbleweed        x86_64
https://api.opensuse.org devel:languages:nodejs nodejs12 openSUSE_Tumbleweed x86_64
Traceback (most recent call last):
  File "/usr/bin/osc", line 41, in <module>
    r = babysitter.run(osccli)
  File "/usr/lib/python3.6/site-packages/osc/babysitter.py", line 61, in run
    return prg.main(argv)
  File "/usr/lib/python3.6/site-packages/osc/cmdln.py", line 344, in main
    return self.cmd(args)
  File "/usr/lib/python3.6/site-packages/osc/cmdln.py", line 367, in cmd
    retval = self.onecmd(argv)
  File "/usr/lib/python3.6/site-packages/osc/cmdln.py", line 501, in onecmd
    return self._dispatch_cmd(handler, argv)
  File "/usr/lib/python3.6/site-packages/osc/cmdln.py", line 1232, in _dispatch_cmd
    return handler(argv[0], opts, *args)
  File "/usr/lib/python3.6/site-packages/osc/commandline.py", line 5649, in do_triggerreason
    reason = root.find('explain').text
AttributeError: 'NoneType' object has no attribute 'text'

```

**Comment by lethliel** [comment]
Will fix this when i am back from vacation (Wednesday)
