### ISSUE TITLE
Source checker failurepy3] 

### ISSUE THREAD

**Issue by DimStar77** [openSUSE/osc#557]
Source checker is failing since the port to py3..

the backtrace is like this:

```
Traceback (most recent call last):
  File "/godata/pipelines/openSUSE.Source.Check/ReviewBot.py", line 177, in check_requests
    good = self.check_one_request(req)
  File "/godata/pipelines/openSUSE.Source.Check/ReviewBot.py", line 369, in check_one_request
    ret = func(req, a)
  File "/godata/pipelines/openSUSE.Source.Check/ReviewBot.py", line 450, in check_action_submit
    return self.check_source_submission(a.src_project, a.src_package, a.src_rev, a.tgt_project, a.tgt_package)
  File "./check_source.py", line 124, in check_source_submission
    server_service_files=True, expand_link=True)
  File "./check_source.py", line 207, in checkout_package
    result = osc.core.checkout_package(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/osc/core.py", line 5048, in checkout_package
    directory = make_dir(apiurl, project, package, pathname, prj_dir, conf.config['do_package_tracking'], outdir)
  File "/usr/lib/python3.7/site-packages/osc/core.py", line 4953, in make_dir
    print(statfrmt('A', prj_dir))
TypeError: a bytes-like object is required, not 'str'
```

**Comment by lethliel** [comment]
@DimStar77: Can I run check_source.py manually? And if, how?

**Comment by DimStar77** [comment]
It's part of the openSUSE/openSUSE-release-tools repo:

https://github.com/openSUSE/openSUSE-release-tools/blob/master/check_source.py

**Comment by DimStar77** [comment]
e.g. ```./check_source.py --dry id 703402```

**Comment by lethliel** [comment]
The problem is the following line in check_source.py (line 205):
`sys.stdout = open(os.devnull, 'wb')`
You are changing the stdout to binary and then python expects everything you write to it as a bytes-like object.

Change it to 

`sys.stdout = open(os.devnull, 'w')`
