### ISSUE TITLE
TypeError: unsupported operand type(s) for +: 'builtin_function_or_method' and 'bytes'

### ISSUE THREAD

**Issue by jayvdb** [openSUSE/osc#566]
```console
> osc build --define='flavour lua53'
Run source service: /usr/lib/obs/service/format_spec_file --outdir /home/jayvdb/projects/osc/home:jayvdb:branches:devel:languages:lua/lua-luarocks/tmpsnrhx8h5.format_spec_file.service
Run source service: /usr/lib/obs/service/source_validator --outdir /home/jayvdb/projects/osc/home:jayvdb:branches:devel:languages:lua/lua-luarocks/tmpj7jsvdmt.source_validator.service
(W) Attention, luarocks-3.0.4.tar.gz is not mentioned in spec files as source or patch.
###ASK /home/jayvdb/projects/osc/home:jayvdb:branches:devel:languages:lua/lua-luarocks/luarocks-3.0.4.tar.gz
WARNING: lua51-luarocks.changes does not exist. This package can not be submitted to openSUSE product projects.
Building lua-luarocks.spec for openSUSE_Tumbleweed/x86_64
Traceback (most recent call last):
  File "/usr/bin/osc", line 41, in <module>
    r = babysitter.run(osccli)
  File "/usr/lib/python3.7/site-packages/osc/babysitter.py", line 61, in run
    return prg.main(argv)
  File "/usr/lib/python3.7/site-packages/osc/cmdln.py", line 344, in main
    return self.cmd(args)
  File "/usr/lib/python3.7/site-packages/osc/cmdln.py", line 367, in cmd
    retval = self.onecmd(argv)
  File "/usr/lib/python3.7/site-packages/osc/cmdln.py", line 501, in onecmd
    return self._dispatch_cmd(handler, argv)
  File "/usr/lib/python3.7/site-packages/osc/cmdln.py", line 1232, in _dispatch_cmd
    return handler(argv[0], opts, *args)
  File "/usr/lib/python3.7/site-packages/osc/commandline.py", line 6347, in do_build
    return osc.build.main(self.get_api_url(), opts, args)
  File "/usr/lib/python3.7/site-packages/osc/build.py", line 698, in main
    build_descr_data = s.encode + build_descr_data
TypeError: unsupported operand type(s) for +: 'builtin_function_or_method' and 'bytes'
```

**Comment by jirislaby** [comment]
FWIW this must be new, as I never saw it before, only after update to 0.165.1.

**Comment by lethliel** [comment]
Thanks for the report. 

This is already fixed in commit https://github.com/openSUSE/osc/commit/13a174bdccec93b68f8a6fc6cae4a16fbda4712a
 Will be part of 0.165.2
