### ISSUE TITLE
osc with python3.7: TypeError: Can't mix strings and bytes in path components

### ISSUE THREAD

**Issue by toabctl** [openSUSE/osc#576]
Using `osc` from openSUSE:Tools on openSUSE TW:

```
$ osc --version
0.165.1
tom@minze:~/devel/bs/pub/home/tbechtold/containers/mariadb$ osc build
Building Dockerfile for containers-leap-15.1/x86_64
Getting buildinfo from server and store to /home/tom/devel/bs/pub/home/tbechtold/containers/mariadb/.osc/_buildinfo-containers-leap-15.1-x86_64.xml
Getting buildconfig from server and store to /home/tom/devel/bs/pub/home/tbechtold/containers/mariadb/.osc/_buildconfig-containers-leap-15.1-x86_64
Updating cache of required packages
0.2% cache miss. 404/405 dependencies cached.

fetching packages for 'openSUSE:Containers:Leap:15.1': | Elapsed Time: 0:00:03                                                                                
Traceback (most recent call last):
  File "/usr/bin/osc", line 41, in <module>
    r = babysitter.run(osccli)
  File "/usr/lib/python3.7/site-packages/osc/babysitter.py", line 61, in run
    return prg.main(argv)
  File "/usr/lib/python3.7/site-packages/osc/cmdln.py", line 344, in main
    return self.cmd(args)
  File "/usr/lib/python3.7/site-packages/osc/cmdln.py", line 367, in cmd
    retval = self.onecmd(argv)
  File "/usr/lib/python3.7/site-packages/osc/cmdln.py", line 501, in onecmd
    return self._dispatch_cmd(handler, argv)
  File "/usr/lib/python3.7/site-packages/osc/cmdln.py", line 1232, in _dispatch_cmd
    return handler(argv[0], opts, *args)
  File "/usr/lib/python3.7/site-packages/osc/commandline.py", line 6347, in do_build
    return osc.build.main(self.get_api_url(), opts, args)
  File "/usr/lib/python3.7/site-packages/osc/build.py", line 932, in main
    fetcher.run(bi)
  File "/usr/lib/python3.7/site-packages/osc/fetch.py", line 253, in run
    self.__fetch_cpio(buildinfo.apiurl)
  File "/usr/lib/python3.7/site-packages/osc/fetch.py", line 128, in __fetch_cpio
    self.__download_cpio_archive(apiurl, project, repo, arch, package, **pkgs)
  File "/usr/lib/python3.7/site-packages/osc/fetch.py", line 98, in __download_cpio_archive
    self.move_package(tmpfile, pac.localdir, pac)
  File "/usr/lib/python3.7/site-packages/osc/fetch.py", line 179, in move_package
    fullfilename = os.path.join(destdir, canonname)
  File "/usr/lib64/python3.7/posixpath.py", line 94, in join
    genericpath._check_arg_types('join', a, *p)
  File "/usr/lib64/python3.7/genericpath.py", line 151, in _check_arg_types
    raise TypeError("Can't mix strings and bytes in path components") from None
TypeError: Can't mix strings and bytes in path components
```

**Comment by lethliel** [comment]
Fixed with commit https://github.com/openSUSE/osc/commit/1c825ec8b6df8168918edce6517a9c260553b231
