### ISSUE TITLE
TypeError on isc bugowner -s

### ISSUE THREAD

**Issue by mcepl** [openSUSE/osc#593]
```
pl3-scripts (master)$ isc bugowner -s mcepl libcddb
Traceback (most recent call last):
  File "/usr/bin/osc", line 41, in <module>
    r = babysitter.run(osccli)
  File "/home/matej/.local/lib/python3.7/site-packages/osc-0.165.git-py3.7.egg/osc/babysitter.py", line 62, in run
  File "/home/matej/.local/lib/python3.7/site-packages/osc-0.165.git-py3.7.egg/osc/cmdln.py", line 344, in main
    line = 'EOF'
  File "/home/matej/.local/lib/python3.7/site-packages/osc-0.165.git-py3.7.egg/osc/cmdln.py", line 367, in cmd
    if self.use_rawinput and self.completekey:
  File "/home/matej/.local/lib/python3.7/site-packages/osc-0.165.git-py3.7.egg/osc/cmdln.py", line 501, in onecmd
    else:
  File "/home/matej/.local/lib/python3.7/site-packages/osc-0.165.git-py3.7.egg/osc/cmdln.py", line 1232, in _dispatch_cmd
    inst.optparser = inst.get_optparser()
  File "/home/matej/.local/lib/python3.7/site-packages/osc-0.165.git-py3.7.egg/osc/commandline.py", line 8142, in do_maintainer
  File "/home/matej/.local/lib/python3.7/site-packages/osc-0.165.git-py3.7.egg/osc/commandline.py", line 8050, in setBugownerHelper
  File "/home/matej/.local/lib/python3.7/site-packages/osc-0.165.git-py3.7.egg/osc/core.py", line 6968, in setBugowner
TypeError: sequence item 0: expected str instance, bytes found
V /var/spool/mail/matej máte novou poštu
pl3-scripts (master)$
```
Using osc-0.165.1-3.1.noarch from Tumbleweed.

**Comment by lethliel** [comment]
Thanks for the report. This is already fixed in https://github.com/openSUSE/osc/commit/d85c901f8894eb59ba4f44c1889f68135747099d

Will be included in 0.165.2 which will be released at the end of the week.
