### ISSUE TITLE
backtrace for '-h' 

### ISSUE THREAD

**Issue by rfrohl** [openSUSE/osc#600]
```
$ osc -h
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/osc/babysitter.py", line 61, in run
    return prg.main(argv)
  File "/usr/lib/python3.6/site-packages/osc/cmdln.py", line 325, in main
    self.options, args = self.optparser.parse_args(argv[1:])
  File "/usr/lib64/python3.6/optparse.py", line 1387, in parse_args
    stop = self._process_args(largs, rargs, values)
  File "/usr/lib64/python3.6/optparse.py", line 1431, in _process_args
    self._process_short_opts(rargs, values)
  File "/usr/lib64/python3.6/optparse.py", line 1536, in _process_short_opts
    option.process(opt, value, values, self)
  File "/usr/lib64/python3.6/optparse.py", line 785, in process
    self.action, self.dest, opt, value, values, parser)
  File "/usr/lib64/python3.6/optparse.py", line 807, in take_action
    parser.print_help()
  File "/usr/lib/python3.6/site-packages/osc/cmdln.py", line 1093, in print_help
    self.cmdln.onecmd(["help"])
  File "/usr/lib/python3.6/site-packages/osc/cmdln.py", line 501, in onecmd
    return self._dispatch_cmd(handler, argv)
  File "/usr/lib/python3.6/site-packages/osc/cmdln.py", line 1216, in _dispatch_cmd
    return handler(argv)
  File "/usr/lib/python3.6/site-packages/osc/cmdln.py", line 610, in do_help
    doc = self._help_preprocess(doc, cmdname)
  File "/usr/lib/python3.6/site-packages/osc/commandline.py", line 206, in _help_preprocess
    help_msg = cmdln.Cmdln._help_preprocess(self, help, cmdname)
  File "/usr/lib/python3.6/site-packages/osc/cmdln.py", line 730, in _help_preprocess
    help = preprocessor(help, cmdname)
  File "/usr/lib/python3.6/site-packages/osc/cmdln.py", line 845, in _help_preprocess_cmd_name
    handler = self._get_cmd_handler(cmdname)
  File "/usr/lib/python3.6/site-packages/osc/cmdln.py", line 983, in _get_cmd_handler
    handler = getattr(self, 'do_' + cmdname)
TypeError: must be str, not NoneType

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/osc", line 41, in <module>
    r = babysitter.run(osccli)
  File "/usr/lib/python3.6/site-packages/osc/babysitter.py", line 65, in run
    if getattr(prg.options, 'traceback', None) or getattr(prg.conf, 'config', {}).get('traceback', None) or \
AttributeError: 'Osc' object has no attribute 'options'
```

```
$ rpm -q osc
osc-0.165.1-lp151.2.3.1.noarch
```
(on Leap 15.1)

Please note that  I am using a plugin, but from the backtrace it is not obvious to me that the plugin is related. 
*edit:* More testing suggested it might be related, as removing the plugin does seem to fix the problem.

**Comment by rfrohl** [comment]
similar backtrace for '-v':
```
osc -v    
Traceback (most recent call last):
  File "/usr/bin/osc", line 41, in <module>
    r = babysitter.run(osccli)
  File "/usr/lib/python3.6/site-packages/osc/babysitter.py", line 61, in run
    return prg.main(argv)
  File "/usr/lib/python3.6/site-packages/osc/cmdln.py", line 346, in main
    return self.emptyline()
  File "/usr/lib/python3.6/site-packages/osc/cmdln.py", line 1007, in emptyline
    return self.do_help(["help"])
  File "/usr/lib/python3.6/site-packages/osc/cmdln.py", line 610, in do_help
    doc = self._help_preprocess(doc, cmdname)
  File "/usr/lib/python3.6/site-packages/osc/commandline.py", line 206, in _help_preprocess
    help_msg = cmdln.Cmdln._help_preprocess(self, help, cmdname)
  File "/usr/lib/python3.6/site-packages/osc/cmdln.py", line 730, in _help_preprocess
    help = preprocessor(help, cmdname)
  File "/usr/lib/python3.6/site-packages/osc/cmdln.py", line 845, in _help_preprocess_cmd_name
    handler = self._get_cmd_handler(cmdname)
  File "/usr/lib/python3.6/site-packages/osc/cmdln.py", line 983, in _get_cmd_handler
    handler = getattr(self, 'do_' + cmdname)
TypeError: must be str, not NoneType
```

**Comment by lethliel** [comment]
[SNIP]

> $ rpm -q osc
> osc-0.165.1-lp151.2.3.1.noarch
> ```
> 
> (on Leap 15.1)
> 
> Please note that I am using a plugin, but from the backtrace it is not obvious to me that the plugin is related.
> _edit:_ More testing suggested it might be related, as removing the plugin does seem to fix the problem.

Yes. Seems to be plugin related. Which plugin are you using? Then I can try to investigate the problem.

With a standard installation on Leap15.1 and osc 0.165.1 this does not happen.

**Comment by rfrohl** [comment]
> Which plugin are you using? Then I can try to investigate the problem.

The plugin is part of the osc-plugins for the UM workflow. I will send a link via mail.
