### ISSUE TITLE
traceback with 'osc service run'

### ISSUE THREAD

**Issue by nickbroon** [openSUSE/osc#620]
Minimal reproduction using a ubuntu 18.04 docker container, (although the same is also seen in a ubuntu 18.04 VM):

```
docker run -ti ubuntu:18.04

apt-get update && apt-get install -y --allow-unauthenticated gnupg wget
wget -O suse.key http://download.opensuse.org/repositories/openSUSE:/Tools/xUbuntu_18.04/Release.key
apt-key add *.key
echo "deb [trusted=yes] http://download.opensuse.org/repositories/openSUSE:/Tools/xUbuntu_18.04/ /" >> /etc/apt/sources.list.d/opensuse.list
apt update && apt install -y osc obs-service-download-url
osc co openSUSE:Tools obs-service-generator_pom
cd openSUSE\:Tools/obs-service-generator_pom/
osc service run
```

resulting in the following trackback:

```
Traceback (most recent call last):
  File "/usr/bin/osc", line 41, in <module>
    r = babysitter.run(osccli)
  File "/usr/lib/python2.7/dist-packages/osc/babysitter.py", line 62, in run
    return prg.main(argv)
  File "/usr/lib/python2.7/dist-packages/osc/cmdln.py", line 344, in main
    return self.cmd(args)
  File "/usr/lib/python2.7/dist-packages/osc/cmdln.py", line 367, in cmd
    retval = self.onecmd(argv)
  File "/usr/lib/python2.7/dist-packages/osc/cmdln.py", line 501, in onecmd
    return self._dispatch_cmd(handler, argv)
  File "/usr/lib/python2.7/dist-packages/osc/cmdln.py", line 1232, in _dispatch_cmd
    return handler(argv[0], opts, *args)
  File "/usr/lib/python2.7/dist-packages/osc/commandline.py", line 6938, in do_service
    return p.run_source_services(mode, singleservice)
  File "/usr/lib/python2.7/dist-packages/osc/core.py", line 2444, in run_source_services
    r = si.execute(self.absdir, mode, singleservice, verbose)
  File "/usr/lib/python2.7/dist-packages/osc/core.py", line 466, in execute
    r = run_external(*cmd)
  File "/usr/lib/python2.7/dist-packages/osc/core.py", line 7720, in run_external
    return subprocess.call(cmd, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 172, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 13] Permission denied
```

**Comment by lethliel** [comment]
This is a problem in obs-service-download_url and is fixed by adding execute permissions to the script download_url. 

I opened PR https://github.com/openSUSE/obs-service-download_url/pull/2 for this.

**Comment by lethliel** [comment]
This was now fixed in openSUSE:Tools
