### ISSUE TITLE
TypeError: load_keyring() takes exactly 2 arguments (1 given)

### ISSUE THREAD

**Issue by andreas-schwab** [openSUSE/osc#663]
Traceback (most recent call last):
  File "/usr/bin/osc", line 41, in <module>
    r = babysitter.run(osccli)
  File "/usr/lib/python2.7/site-packages/osc/babysitter.py", line 62, in run
    return prg.main(argv)
  File "/usr/lib/python2.7/site-packages/osc/cmdln.py", line 336, in main
    self.postoptparse()
  File "/usr/lib/python2.7/site-packages/osc/commandline.py", line 145, in postoptparse
    override_verbose = self.options.verbose)
  File "/usr/lib/python2.7/site-packages/osc/conf.py", line 899, in get_config
    password = creds_mgr.get_password(url, user)
  File "/usr/lib/python2.7/site-packages/osc/credentials.py", line 186, in get_password
    self._load_backend()
  File "/usr/lib/python2.7/site-packages/osc/credentials.py", line 176, in _load_backend
    keyring_backend = keyring.core.load_keyring(self._backend_cls_name)
TypeError: load_keyring() takes exactly 2 arguments (1 given)

**Comment by lethliel** [comment]
Thanks for reporting. Can you please provide the following information:

- OS version
-  osc version
- Do you use Plaintext or passx password?

**Comment by marcus-h** [comment]
On 2019-11-02 07:31:20 -0700, Andreas Schwab wrote:
...

>   File "/usr/lib/python2.7/site-packages/osc/credentials.py", line 176, in _load_backend
>     keyring_backend = keyring.core.load_keyring(self._backend_cls_name)
> TypeError: load_keyring() takes exactly 2 arguments (1 given)
>
Hmm it seems the keyring version is either too old or too new.
What's the output of "rpm -q python-keyring" (or "rpm -q python2-keyring")?

**Comment by dmach** [comment]
We do not have enough information to reproduce the issue. Closing.
