### ISSUE TITLE
osc traceback wiping chroot

### ISSUE THREAD

**Issue by nickbroon** [openSUSE/osc#743]
There are possibly two issues here. The first is not obvious to me, but the second exception appears to trying to use https://github.com/openSUSE/osc/blob/d279dfbedbd33de0efeb5bc57b6146b9882bd729/osc/babysitter.py#L25 as an exception which does not inherit from BaseException.

```
16:06:00  + osc chroot --wipe --force --root /build-root/Vyatta_Master-standard-x86_64
16:06:00  Wiping build root: '/build-root/Vyatta_Master-standard-x86_64'
16:06:01  Traceback (most recent call last):
16:06:01    File "/usr/lib/python3/dist-packages/osc/babysitter.py", line 62, in run
16:06:01      return prg.main(argv)
16:06:01    File "/usr/lib/python3/dist-packages/osc/cmdln.py", line 344, in main
16:06:01      return self.cmd(args)
16:06:01    File "/usr/lib/python3/dist-packages/osc/cmdln.py", line 367, in cmd
16:06:01      retval = self.onecmd(argv)
16:06:01    File "/usr/lib/python3/dist-packages/osc/cmdln.py", line 501, in onecmd
16:06:01      return self._dispatch_cmd(handler, argv)
16:06:01    File "/usr/lib/python3/dist-packages/osc/cmdln.py", line 1232, in _dispatch_cmd
16:06:01      return handler(argv[0], opts, *args)
16:06:01    File "/usr/lib/python3/dist-packages/osc/commandline.py", line 6473, in do_build
16:06:01      sys.exit(osc.build.run_build(*build_args))
16:06:01  SystemExit: 0
16:06:01  
16:06:01  During handling of the above exception, another exception occurred:
16:06:01  
16:06:01  Traceback (most recent call last):
16:06:01    File "/usr/bin/osc", line 41, in <module>
16:06:01      r = babysitter.run(osccli)
16:06:01    File "/usr/lib/python3/dist-packages/osc/babysitter.py", line 174, in run
16:06:01      except SSLError as e:
16:06:01  TypeError: catching classes that do not inherit from BaseException is not allowed
```

**Comment by nickbroon** [comment]
Completely untested but a fix for the second exception might be:

``` python
try:
    from M2Crypto.SSL.Checker import SSLVerificationError
    from M2Crypto.SSL import SSLError as SSLError
except:
    class SSLError(Exception):
        pass
    class SSLVerificationError(Exception):
        pass

```

**Comment by marcus-h** [comment]
On 2020-02-18 08:54:35 -0800, Nick Brown wrote:
> Completely untested but a fix for the second exception might be:
>
> ``` python
> try:
>     from M2Crypto.SSL.Checker import SSLVerificationError
>     from M2Crypto.SSL import SSLError as SSLError
> except:
>     class SSLError(Exception):
>         pass
>     class SSLVerificationError(Exception):
>         pass
>
> ```
Yes, that would do the trick. Are you in the mood for creating
a PR?:)

**Comment by nickbroon** [comment]
#744  PR already open :-)

**Comment by marcus-h** [comment]
Please ignore my comment - I just saw the PR:)

**Comment by nickbroon** [comment]
When will the next osc release containing this fix be made?
