### ISSUE TITLE
HTTPError not handled correctly in python3.8

### ISSUE THREAD

**Issue by lethliel** [openSUSE/osc#745]
HTTPError not handled correctly in python3.8

```
Sending    /tmp/tmpjv6t8zoahome:ignatenkobrain:rust-rust-crc32fast/_constraints
Transmitting file data .Traceback (most recent call last):
  File "./distgit-obsimport.py", line 185, in <module>
    osc_working_pkg.commit(msg=f"Imported {args.git_repo_prefix}/{args.git_repo_name}@{repo_commit}")
  File "/usr/lib/python3.8/site-packages/osc/core.py", line 1564, in commit
    self.put_source_file(filename, tdir)
  File "/usr/lib/python3.8/site-packages/osc/core.py", line 1384, in put_source_file
    http_PUT(u, file = tfilename)
  File "/usr/lib/python3.8/site-packages/osc/core.py", line 3402, in http_PUT
    def http_PUT(*args, **kwargs):    return http_request('PUT', *args, **kwargs)
  File "/usr/lib/python3.8/site-packages/osc/core.py", line 3389, in http_request
    fd = urlopen(req, data=data)
  File "/usr/lib64/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib64/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib64/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/usr/lib64/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib64/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/lib64/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 400: Bad Request
```

**Comment by ignatenkobrain** [comment]
@adrianschroeter did something and it started to work without changes on a client...

**Comment by lethliel** [comment]
@ignatenkobrain Yes. But osc should not throw such an traceback. 

It should look like this:

```
osc ci
Sending    _constraints
Transmitting file data .Server returned an error: HTTP Error 400: Bad Request
constraints validation error: ERROR: Extra element cpu in interleave
```

At least this is what it looks like in python3.7.

**Comment by dmach** [comment]
It seems this is no longer applicable to the current code base (and the issue is nearly 3 years old).
Please open a new issue if the problem persists.
