### ISSUE TITLE
Traceback config with two backends and no username

### ISSUE THREAD

**Issue by lethliel** [openSUSE/osc#761]
When migrating from an existing oscrc with keyring support the following exception is thrown, when the oscrc includes two APIs:

Conditions:
* osc > 0.166.0 must be used
* no username / password in the API section of oscrc
* osc ls 

I also find it questionable that always the configuration of *all* endpoints is read. 

At the end both credentials_mgr_class entries are generated correct.

```
marco@linux-2ule:~> osc ls home:mstrigl
No user found in section https://api.opensuse.org
Please enter new credentials.
Username: mstrigl
Password: 
1) SecretService Keyring (Backend provided by python-keyring)
2) chainer ChainerBackend (Backend provided by python-keyring)
3) fail Keyring (Backend provided by python-keyring)
4) file EncryptedKeyring (Backend provided by python-keyring)
5) file PlaintextKeyring (Backend provided by python-keyring)
6) kwallet DBusKeyring (Backend provided by python-keyring)
7) Config file credentials manager (Store the credentials in the config file (plain text))
8) Obfuscated Config file credentials manager (Store the credentials in the config file (obfuscated))
9) Transient password store (Do not store the password and always ask for the password)
Select credentials manager: 9
No user found in section https://api.suse.de
Please enter new credentials.
Username: mstrigl
Password: 
1) SecretService Keyring (Backend provided by python-keyring)
2) chainer ChainerBackend (Backend provided by python-keyring)
3) fail Keyring (Backend provided by python-keyring)
4) file EncryptedKeyring (Backend provided by python-keyring)
5) file PlaintextKeyring (Backend provided by python-keyring)
6) kwallet DBusKeyring (Backend provided by python-keyring)
7) Config file credentials manager (Store the credentials in the config file (plain text))
8) Obfuscated Config file credentials manager (Store the credentials in the config file (obfuscated))
9) Transient password store (Do not store the password and always ask for the password)
Select credentials manager: 9
Traceback (most recent call last):
  File "/usr/bin/osc", line 41, in <module>
    r = babysitter.run(osccli)
  File "/usr/lib/python3.7/site-packages/osc/babysitter.py", line 64, in run
    return prg.main(argv)
  File "/usr/lib/python3.7/site-packages/osc/cmdln.py", line 344, in main
    return self.cmd(args)
  File "/usr/lib/python3.7/site-packages/osc/cmdln.py", line 367, in cmd
    retval = self.onecmd(argv)
  File "/usr/lib/python3.7/site-packages/osc/cmdln.py", line 501, in onecmd
    return self._dispatch_cmd(handler, argv)
  File "/usr/lib/python3.7/site-packages/osc/cmdln.py", line 1232, in _dispatch_cmd
    return handler(argv[0], opts, *args)
  File "/usr/lib/python3.7/site-packages/osc/commandline.py", line 425, in do_list
    for pkg in meta_get_packagelist(apiurl, project, deleted = opts.deleted, expand = opts.expand):
  File "/usr/lib/python3.7/site-packages/osc/core.py", line 3442, in meta_get_packagelist
    u = makeurl(apiurl, ['source', prj], query)
  File "/usr/lib/python3.7/site-packages/osc/core.py", line 3307, in makeurl
    if conf.config['verbose'] > 1:
TypeError: '>' not supported between instances of 'str' and 'int'
```

**Comment by sknorr** [comment]
Still an issue in 0.174.
