### ISSUE TITLE
IncompleteRead in `osc build`

### ISSUE THREAD

**Issue by ItachiSan** [openSUSE/osc#771]
## Expected
`osc build` works as intended

## Current situation
The command fails.

## How to reproduce
I am currently trying to build any of my packages, leading to such issue:

```console
itachisan@MY_MACHINE:~/Packaging/obs/gecode $ osc --http-full-debug --post-mortem build --clean

# Lot of logs, everything works fine...
# Until this:

Getting buildinfo from server and store to /mnt/data/Progetti/Packaging/obs/gecode/.osc/_buildinfo-standard-x86_64.xml

-- POST https://api.opensuse.org/build/home:ItachiSan:archlinux/standard/x86_64/gecode/_buildinfo
send: b'POST /build/home:ItachiSan:archlinux/standard/x86_64/gecode/_buildinfo HTTP/1.1\r\nAccept-Encoding: identity\r\nContent-type: application/octet-stream\r\nContent-length: 2560\r\nHost: api.opensuse.org\r\nUser-agent: osc/0.168.2\r\nCookie: openSUSE_session=SESSION_COOKIE\r\nConnection: close\r\n\r\n'
send: b'07070100000000000081A400000000000000000000000000000000000006CC000000000000000000000000000000000000000900000000PKGBUILD\x00\x00# Maintainer:  Giovanni \'ItachiSan\' Santini <giovannisantini93@yahoo.it>\n# Contributor: Alexander Scharinger <e1028732 at student dot tuwien dot ac dot at>\n# Contributor: Gustavo A. Gomez Farhat <gustavo_dot_gomez_dot_farhat at gmail_dot_com>\npkgname=gecode\npkgver=6.2.0\npkgrel=0\npkgdesc="The Generic Constraint Development Environment"\narch=(\'i686\' \'x86_64\')\nurl="http://www.gecode.org"\nlicense=(\'MIT\')\n# If qt4 is installed, gecode will compile with Gecode Interactive Search\n# Tool Support (GIST).\n# If you want GIST support or if you want pacman to maintain a dependency,\n# cause you have qt4 already installed, then you will have to add qt4 in the\n# depends array.\n#depends=(\'qt4\')\n# For support for trigonometric and transcendental float constraints you will\n# need to use the following dependencies and additionaly add the directories to\n# the arguments of the configure call in the build() function.\n# For further inormation see section 2.6.2 of the Gecode documentation\n# "Modeling and Programming with Gecode".\ndepends=(\'qt5-base\' \'mpfr\' \'gmp\')\nsource=("$pkgname-$pkgver.tar")\n# MD5 sum can not be found anywhere on the webpage.\n# Use the following shell command to generate and update the md5 sum.\n# $ makepkg -g >> PKGBUILD\nsha256sums=(\'SKIP\')\n\nbuild() {\n  cd "$srcdir/$pkgname-$pkgver"\n  ./configure --prefix=/usr --disable-examples\n  #./configure --prefix=/usr --disable-examples --with-mpfr-include=/usr/include/ --with-mpfr-lib=/usr/lib/ --with-gmp-include=/usr/include/ --with-gmp-lib=/usr/lib/\n  make\n}\n\npackage() {\n  cd "$srcdir/$pkgname-$pkgver"\n  make DESTDIR="$pkgdir" install\n  rm -r "$pkgdir/usr/include/examples/"\n  install -m 644 -D LICENSE "$pkgdir/usr/share/licenses/$pkgname/LICENSE"\n}\n\n# vim:set ts=2 sw=2 et:\n07070100000000000081A400000000000000000000000000000000000001B3000000000000000000000000000000000000000900000000_service\x00\x00<services>\n  <service name="obs_scm">\n    <param name="scm">git</param>\n    <param name="url">https://github.com/Gecode/gecode.git</param>\n    <param name="revision">refs/tags/release-6.2.0</param>\n    <param name="versionformat">@PARENT_TAG@</param>\n    <param name="versionrewrite-pattern">release(.*)</param>\n  </service>\n  <service name="tar"         mode="buildtime"/>\n  <service name="set_version" mode="buildtime"/>\n</services>\n\x0007070100000000000081A40000000000000000000000000000000000000000000000000000000000000000000000000000000B00000000TRAILER!!!\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
reply: 'HTTP/1.1 200 OK\r\n'
header: Date: Fri, 20 Mar 2020 09:17:55 GMT
header: Server: Apache/2.4.23 (Linux/SUSE)
header: Strict-Transport-Security: max-age=31536000
header: cache-control: private
header: vary: Accept-Encoding
header: referrer-policy: strict-origin-when-cross-origin
header: x-permitted-cross-domain-policies: none
header: x-xss-protection: 1; mode=block
header: x-opensuse-runtimes: {"view":0.4883706569671631,"db":9.46301594376564,"backend":505.885413}
header: x-request-id: 803cb4d2-6566-4b16-92df-fec306fab8d8
header: x-opensuse-apiversion: 2.11~alpha.20200319T174902.a968354ab1
header: content-disposition: inline
header: x-download-options: noopen
header: content-transfer-encoding: binary
header: x-frame-options: SAMEORIGIN
header: x-runtime: 0.541000
header: x-content-type-options: nosniff
header: x-powered-by: Phusion Passenger 6.0.4
header: etag: W/"c4f73c9deef8962718255810dd33d1ac"
header: status: 200 OK
header: content-type: text/xml
header: Connection: close
header: Transfer-Encoding: chunked
Traceback (most recent call last):
  File "/usr/lib/python3.8/http/client.py", line 588, in _readinto_chunked
    n = self._safe_readinto(mvb)
  File "/usr/lib/python3.8/http/client.py", line 618, in _safe_readinto
    raise IncompleteRead(bytes(b[:n]), amt-n)
http.client.IncompleteRead: IncompleteRead(7179 bytes read, 1013 more expected)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/osc/babysitter.py", line 64, in run
    return prg.main(argv)
  File "/usr/lib/python3.8/site-packages/osc/cmdln.py", line 344, in main
    return self.cmd(args)
  File "/usr/lib/python3.8/site-packages/osc/cmdln.py", line 367, in cmd
    retval = self.onecmd(argv)
  File "/usr/lib/python3.8/site-packages/osc/cmdln.py", line 501, in onecmd
    return self._dispatch_cmd(handler, argv)
  File "/usr/lib/python3.8/site-packages/osc/cmdln.py", line 1232, in _dispatch_cmd
    return handler(argv[0], opts, *args)
  File "/usr/lib/python3.8/site-packages/osc/commandline.py", line 6533, in do_build
    return osc.build.main(self.get_api_url(), opts, args)
  File "/usr/lib/python3.8/site-packages/osc/build.py", line 851, in main
    bi_text = decode_it(get_buildinfo(apiurl,
  File "/usr/lib/python3.8/site-packages/osc/core.py", line 6181, in get_buildinfo
    return f.read()
  File "/usr/lib/python3.8/tempfile.py", line 474, in func_wrapper
    return func(*args, **kwargs)
  File "/usr/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.8/http/client.py", line 488, in readinto
    return self._readinto_chunked(b)
  File "/usr/lib/python3.8/http/client.py", line 599, in _readinto_chunked
    raise IncompleteRead(bytes(b[0:total_bytes]))
http.client.IncompleteRead: IncompleteRead(0 bytes read)
> /usr/lib/python3.8/http/client.py(599)_readinto_chunked()
-> raise IncompleteRead(bytes(b[0:total_bytes]))

# PDB shell here

```

**Comment by lethliel** [comment]
Which version of python-M2Crypto are you using?

**Comment by ItachiSan** [comment]
0.35.2:

```
$ LANG=C pacman -Qi python-m2crypto 
Name            : python-m2crypto
Version         : 0.35.2-2
Description     : A crypto and SSL toolkit for Python
Architecture    : x86_64
URL             : https://pypi.python.org/pypi/M2Crypto
Licenses        : BSD
Groups          : None
Provides        : None
Depends On      : python  openssl
Optional Deps   : None
Required By     : osc
Optional For    : None
Conflicts With  : None
Replaces        : None
Installed Size  : 1385.25 KiB
Packager        : Felix Yan <felixonmars@archlinux.org>
Build Date      : Mon Nov 4 10:41:02 2019
Install Date    : Thu Mar 19 16:00:08 2020
Install Reason  : Installed as a dependency for another package
Install Script  : No
Validated By    : Signature
```

**Comment by marcus-h** [comment]
On 2020-03-20 08:38:55 -0700, Giovanni Santini wrote:
> 0.35.2:
>
> ```
> $ LANG=C pacman -Qi python-m2crypto
> Name            : python-m2crypto
> Version         : 0.35.2-2

It probably misses [1] (unless it was backported), which is required
for python3.8.


[1] https://gitlab.com/m2crypto/m2crypto/-/merge_requests/242

**Comment by bill-auger** [comment]
i had this same problem on parabola/arch - i can confirm that applying the patch suggested by marcus-h, onto the 0.35.2 release of python-m2crypto, allowed the build to start

https://gitlab.com/m2crypto/m2crypto/-/commit/d3a43ffe1bfe4c128d6ab7c390419dee68f4ca5a.patch

**Comment by ItachiSan** [comment]
The issue is solved as of:
https://git.archlinux.org/svntogit/community.git/commit/trunk?h=packages/python-m2crypto&id=b74180bef91fa4ef64fd5b946d754d761150ae0d

**Comment by nickbroon** [comment]
In summary: If using osc with python 3.8 at least version 0.36 of m2crypto is required.
The work around is to use `sslcertck = 0` in .oscrc to disable the use of m2crypto.

**Comment by crazyscientist** [comment]
> The work around is to use sslcertck = 0 in .oscrc to disable the use of m2crypto.

I cannot confirm this workaround for `osc` on Ubuntu 20.04 with `M2Crypto` version 0.31.0-9ubuntu1. Even after applying the workaround I get the same error:

`IncompleteRead(0 bytes read)`

**Comment by marcus-h** [comment]
On 2020-12-10 06:22:48 -0800, Andreas Hasenkopf wrote:
> > The work around is to use sslcertck = 0 in .oscrc to disable the use of m2crypto.
>
> I cannot confirm this workaround for `osc` on Ubuntu 20.04 with `M2Crypto` version 0.31.0-9ubuntu1. Even after applying the workaround I get the same error:
>
> `IncompleteRead(0 bytes read)`
>
Did you set the option in the corresponding apiurl section? Setting
this option in the "general" section has no effect.

**Comment by crazyscientist** [comment]
> Did you set the option in the corresponding apiurl section?

Why should I have put the option into the `apiurl` section? Thanks for clarifying the correct place for this option. 
But never mind, upgrading `M2Crypto` worked like a charm and does not require any config changes.

**Comment by marcus-h** [comment]
On 2020-12-11 00:16:42 -0800, Andreas Hasenkopf wrote:
> > Did you set the option in the corresponding apiurl section?
>
> Why should I have put the option into the `apiurl` section?

A per apiurl setting offers a bit more "flexibility". For instance,
if you communicate with an OBS that has bad certificate but it is
in your local network (which you trust), you can disable the cert
check for this particular OBS instance. For all other OBS instances,
like api.o.o, cert checking is still done.
