### ISSUE TITLE
workerinfo backtrace

### ISSUE THREAD

**Issue by AdamMajer** [openSUSE/osc#775]
Issuing a `workerinfo` without required parameters results in a backtrace. I would expect the error to be printed without the excess noise.

```python3

> osc workerinfo
Traceback (most recent call last):
  File "/usr/bin/osc", line 41, in <module>
    r = babysitter.run(osccli)
  File "/usr/lib/python3.6/site-packages/osc/babysitter.py", line 62, in run
    return prg.main(argv)
  File "/usr/lib/python3.6/site-packages/osc/cmdln.py", line 344, in main
    return self.cmd(args)
  File "/usr/lib/python3.6/site-packages/osc/cmdln.py", line 367, in cmd
    retval = self.onecmd(argv)
  File "/usr/lib/python3.6/site-packages/osc/cmdln.py", line 501, in onecmd
    return self._dispatch_cmd(handler, argv)
  File "/usr/lib/python3.6/site-packages/osc/cmdln.py", line 1232, in _dispatch_cmd
    return handler(argv[0], opts, *args)
TypeError: do_workerinfo() missing 1 required positional argument: 'worker'
```

**Comment by marcus-h** [comment]
On 2020-03-30 08:08:20 -0700, Adam Majer wrote:
> Issuing a `workerinfo` without required parameters results in a backtrace. I would expect the error to be printed without the excess noise.

That's issue #735 ("osc api command without arguments throws traceback").

**Comment by AdamMajer** [comment]
Great, I'll close it as a duplicate.
