### ISSUE TITLE
osc submitrequest on python 3.8 leads to an exception

### ISSUE THREAD

**Issue by geigi** [openSUSE/osc#837]
Running submitrequest leads to an exception:
```
osc submitrequest -m "Update ..."
```

**Environment**
- Ubuntu 20.04
- Python 3.8.2
- `osc --version`: 0.167.1

**Exception**
```
Traceback (most recent call last):
  File "/usr/bin/osc", line 41, in <module>
    r = babysitter.run(osccli)
  File "/usr/lib/python3/dist-packages/osc/babysitter.py", line 62, in run
    return prg.main(argv)
  File "/usr/lib/python3/dist-packages/osc/cmdln.py", line 344, in main
    return self.cmd(args)
  File "/usr/lib/python3/dist-packages/osc/cmdln.py", line 367, in cmd
    retval = self.onecmd(argv)
  File "/usr/lib/python3/dist-packages/osc/cmdln.py", line 501, in onecmd
    return self._dispatch_cmd(handler, argv)
  File "/usr/lib/python3/dist-packages/osc/cmdln.py", line 1232, in _dispatch_cmd
    return handler(argv[0], opts, *args)
  File "/usr/lib/python3/dist-packages/osc/commandline.py", line 1458, in do_submitrequest
    result = create_submit_request(apiurl,
  File "/usr/lib/python3/dist-packages/osc/core.py", line 4243, in create_submit_request
    cgi.escape(message))
AttributeError: module 'cgi' has no attribute 'escape'
```

Seems like `html.escape` is the suggested replacement for python 3.8.

**Comment by geigi** [comment]
Sorry I just saw that this is already fixed in master...
