### ISSUE TITLE
superseding a "multiple" sr with `-s` submits but produces python Traceback and does not supersed old one:

### ISSUE THREAD

**Issue by bnavigator** [openSUSE/osc#849]
I got this error when submitting SR 839609 to supersede 839591:

```
greiner@greinerT450s:~/src/osc/home:bnavigator:branches:devel:languages:python/ > osc up
Updating python-poetry
At revision 0a4280304cd2305c4b05b2dde0bce711.
Updating python-tomlkit
At revision 6235067796326b8eda6f05ae31207ea6.
Updating python-poetry-core
At revision c2b8345365f39e282c684c7bf681271c.
Pending requests for project: home:bnavigator:branches:devel:languages:python (1)
839591  State:new        By:bnavigator   When:2020-10-05T14:24:38
        submit:          home:bnavigator:branches:devel:languages:python/python-poetry@c2fcc0640a24aad42f4a283e51a969c0 -> devel:languages:python
        submit:          home:bnavigator:branches:devel:languages:python/python-poetry-core@c2b8345365f39e282c684c7bf681271c -> devel:languages:python
        submit:          home:bnavigator:branches:devel:languages:python/python-tomlkit@379d26e5d529b95d8997e978070dc9bc -> devel:languages:python
        Descr: update poetry and it's deps: requires new poetry-core
 

greiner@greinerT450s:~/src/osc/home:bnavigator:branches:devel:languages:python/ > osc sr devel:languages:python -m "update poetry and it's deps: requires new poetry-core"  -s 839591
Request(s) created:  839609 Traceback (most recent call last):
  File "/usr/bin/osc", line 41, in <module>
    r = babysitter.run(osccli)
  File "/usr/lib/python3.8/site-packages/osc/babysitter.py", line 64, in run
    return prg.main(argv)
  File "/usr/lib/python3.8/site-packages/osc/cmdln.py", line 347, in main
    return self.cmd(args)
  File "/usr/lib/python3.8/site-packages/osc/cmdln.py", line 370, in cmd
    retval = self.onecmd(argv)
  File "/usr/lib/python3.8/site-packages/osc/cmdln.py", line 504, in onecmd
    return self._dispatch_cmd(handler, argv)
  File "/usr/lib/python3.8/site-packages/osc/cmdln.py", line 1235, in _dispatch_cmd
    return handler(argv[0], opts, *args)
  File "/usr/lib/python3.8/site-packages/osc/commandline.py", line 1333, in do_submitrequest
    'superseded by %s' % result, result)
UnboundLocalError: local variable 'result' referenced before assignment
```

839609 got submitted but the state of 839591 was not updated

https://build.opensuse.org/request/show/839609
https://build.opensuse.org/request/show/839591

**Comment by mcepl** [comment]
Still true with `osc-0.171.0-310.2.noarch`:
```
home:mcepl:branches:python39@stitny$ isc sr -s 232623  SUSE:SLE-15-SP3:GA
Request(s) created:  232960 Traceback (most recent call last):
  File "/usr/bin/osc", line 41, in <module>
    r = babysitter.run(osccli)
  File "/usr/lib/python3.8/site-packages/osc/babysitter.py", line 69, in run
    return prg.main(argv)
  File "/usr/lib/python3.8/site-packages/osc/cmdln.py", line 347, in main
    return self.cmd(args)
  File "/usr/lib/python3.8/site-packages/osc/cmdln.py", line 370, in cmd
    retval = self.onecmd(argv)
  File "/usr/lib/python3.8/site-packages/osc/cmdln.py", line 504, in onecmd
    return self._dispatch_cmd(handler, argv)
  File "/usr/lib/python3.8/site-packages/osc/cmdln.py", line 1235, in _dispatch_cmd
    return handler(argv[0], opts, *args)
  File "/usr/lib/python3.8/site-packages/osc/commandline.py", line 1332, in do_submitrequest
    'superseded by %s' % result, result)
UnboundLocalError: local variable 'result' referenced before assignment
home:mcepl:branches:python39@stitny$ which osc
```

**Comment by aaptel** [comment]
Still happening in osc-0.172.0-1.1.noarch

**Comment by aaptel** [comment]
I've taken a look at the code, I think it's just a matter of using `sr_ids[0]` instead of `result`. Not sure about the purpose rest of the list `sr_ids`.
