### ISSUE TITLE
osc proxy problem

### ISSUE THREAD

**Issue by myphj** [openSUSE/osc#85]
When I use osc 0.139 + python 2.7,
 the following problem is met.

---

hj44.park@S3 17:39:46 (2008) ~/ [] > osc list      

-- GET https://168.219.241.168:444/source
WARNING: SSL certificate checks disabled. Connection is insecure!

GET https://168.219.241.168:444/source
Failed to reach a server:
## [Errno 8] _ssl.c:504: EOF occurred in violation of protocol

I executed the followings : 
hj44.park@S3 17:39:49 (2009) ~/ [] > export no_proxy="168.219.241.168"
## But currently, this error comes out.

hj44.park@S3 17:40:05 (2010) ~/ [] > osc list

-- GET https://168.219.241.168:444/source
WARNING: SSL certificate checks disabled. Connection is insecure!

GET https://168.219.241.168:444/source
Traceback (most recent call last):
  File "/usr/bin/osc", line 22, in <module>
    r = babysitter.run(osccli)
  File "/usr/lib/python2.7/dist-packages/osc/babysitter.py", line 53, in run
    return prg.main()
  File "/usr/lib/python2.7/dist-packages/osc/cmdln.py", line 310, in main
    return self.cmd(args)
  File "/usr/lib/python2.7/dist-packages/osc/cmdln.py", line 333, in cmd
    retval = self.onecmd(argv)
  File "/usr/lib/python2.7/dist-packages/osc/cmdln.py", line 449, in onecmd
    return self._dispatch_cmd(handler, argv)
  File "/usr/lib/python2.7/dist-packages/osc/cmdln.py", line 1179, in _dispatch_cmd
    return handler(argv[0], opts, _args)
  File "/usr/lib/python2.7/dist-packages/osc/commandline.py", line 376, in do_list
    for prj in meta_get_project_list(apiurl, opts.deleted):
  File "/usr/lib/python2.7/dist-packages/osc/core.py", line 3024, in meta_get_project_list
    f = http_GET(u)
  File "/usr/lib/python2.7/dist-packages/osc/core.py", line 2937, in http_GET
    def http_GET(_args, *_kwargs):    return http_request('GET', *args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/osc/core.py", line 2925, in http_request
    fd = urllib2.urlopen(req, data=data)
  File "/usr/lib/python2.7/urllib2.py", line 126, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 400, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 418, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 378, in _call_chain
    result = func(_args)
  File "/usr/lib/python2.7/urllib2.py", line 1215, in https_open
    return self.do_open(httplib.HTTPSConnection, req)
  File "/usr/lib/python2.7/urllib2.py", line 1174, in do_open
    h.request(req.get_method(), req.get_selector(), req.data, headers)
  File "/usr/lib/python2.7/httplib.py", line 958, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 992, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 954, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 814, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/dist-packages/osc/conf.py", line 522, in new_method
    meth(_args, **kwargs)
  File "/usr/lib/python2.7/httplib.py", line 790, in send
    self.sock.sendall(data)
## AttributeError: 'NoneType' object has no attribute 'sendall'

I cannot find out what is the problem.
I tried to understand with python 2.7 source, but I could not.

What's the problem and What can I do to solve?

**Comment by lethliel** [comment]
This is almost 5 years old with a now unsupported osc version and python2.7. 
Please open a new issue if this problem is occurring with a recent osc version and python3
