### ISSUE TITLE
get_source_file fails on Windows

### ISSUE THREAD

**Issue by jayvdb** [openSUSE/osc#963]
A lot of tests fail in `get_source_file` on Windows with `TypeError: a bytes-like object is required, not 'str'`

Probably this is because on Windows, `locale.getpreferredencoding()` is `cp1252`

```
======================================================================
ERROR [0.000s]: testDiffRemoteExistingLocalNotExisting (test_difffiles.TestDiffFiles)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\vandjohn\gh\osc\tests\common.py", line 160, in wrapped_test_method
    test_method(*args)
  File "C:\Users\vandjohn\gh\osc\tests\common.py", line 160, in wrapped_test_method
    test_method(*args)
  File "C:\Users\vandjohn\gh\osc\tests\common.py", line 160, in wrapped_test_method
    test_method(*args)
  File "C:\Users\vandjohn\gh\osc\tests\test_difffiles.py", line 254, in testDiffRemoteExistingLocalNotExisting
    self.__check_diff(p, exp, 3)
  File "C:\Users\vandjohn\gh\osc\tests\test_difffiles.py", line 301, in __check_diff
    for i in p.get_diff(revision):
  File "C:\Users\vandjohn\gh\osc\osc\core.py", line 2086, in get_diff
    get_source_file(self.apiurl, self.prjname, self.name, f.name, tmpfile, revision)
  File "C:\Users\vandjohn\gh\osc\osc\core.py", line 4733, in get_source_file
    u = makeurl(apiurl, ['source', prj, package, pathname2url(filename.encode(locale.getpreferredencoding(), 'replace'))], query=query)
  File "C:\Users\vandjohn\Downloads\WPy64-3771\python-3.7.7.amd64\lib\nturl2path.py", line 53, in pathname2url
    if not ':' in p:
TypeError: a bytes-like object is required, not 'str'

======================================================================
ERROR [0.365s]: testDiffRemoteMissingLocalDeleted (test_difffiles.TestDiffFiles)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\vandjohn\gh\osc\tests\common.py", line 160, in wrapped_test_method
    test_method(*args)
  File "C:\Users\vandjohn\gh\osc\tests\test_difffiles.py", line 297, in testDiffRemoteMissingLocalDeleted
    self.__check_diff(p, '', 3)
  File "C:\Users\vandjohn\gh\osc\tests\test_difffiles.py", line 301, in __check_diff
    for i in p.get_diff(revision):
  File "C:\Users\vandjohn\gh\osc\osc\core.py", line 2086, in get_diff
    get_source_file(self.apiurl, self.prjname, self.name, f.name, tmpfile, revision)
  File "C:\Users\vandjohn\gh\osc\osc\core.py", line 4733, in get_source_file
    u = makeurl(apiurl, ['source', prj, package, pathname2url(filename.encode(locale.getpreferredencoding(), 'replace'))], query=query)
  File "C:\Users\vandjohn\Downloads\WPy64-3771\python-3.7.7.amd64\lib\nturl2path.py", line 53, in pathname2url
    if not ':' in p:
TypeError: a bytes-like object is required, not 'str'

======================================================================
ERROR [0.348s]: testDiffRemoteMissingLocalExisting (test_difffiles.TestDiffFiles)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\vandjohn\gh\osc\tests\common.py", line 160, in wrapped_test_method
    test_method(*args)
  File "C:\Users\vandjohn\gh\osc\tests\test_difffiles.py", line 286, in testDiffRemoteMissingLocalExisting
    self.__check_diff(p, exp, 3)
  File "C:\Users\vandjohn\gh\osc\tests\test_difffiles.py", line 301, in __check_diff
    for i in p.get_diff(revision):
  File "C:\Users\vandjohn\gh\osc\osc\core.py", line 2086, in get_diff
    get_source_file(self.apiurl, self.prjname, self.name, f.name, tmpfile, revision)
  File "C:\Users\vandjohn\gh\osc\osc\core.py", line 4733, in get_source_file
    u = makeurl(apiurl, ['source', prj, package, pathname2url(filename.encode(locale.getpreferredencoding(), 'replace'))], query=query)
  File "C:\Users\vandjohn\Downloads\WPy64-3771\python-3.7.7.amd64\lib\nturl2path.py", line 53, in pathname2url
    if not ':' in p:
TypeError: a bytes-like object is required, not 'str'

======================================================================
ERROR [0.000s]: testDiffRemoteModified (test_difffiles.TestDiffFiles)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\vandjohn\gh\osc\tests\common.py", line 160, in wrapped_test_method
    test_method(*args)
  File "C:\Users\vandjohn\gh\osc\tests\common.py", line 160, in wrapped_test_method
    test_method(*args)
  File "C:\Users\vandjohn\gh\osc\tests\test_difffiles.py", line 217, in testDiffRemoteModified
    self.__check_diff(p, exp, 3)
  File "C:\Users\vandjohn\gh\osc\tests\test_difffiles.py", line 301, in __check_diff
    for i in p.get_diff(revision):
  File "C:\Users\vandjohn\gh\osc\osc\core.py", line 2086, in get_diff
    get_source_file(self.apiurl, self.prjname, self.name, f.name, tmpfile, revision)
  File "C:\Users\vandjohn\gh\osc\osc\core.py", line 4733, in get_source_file
    u = makeurl(apiurl, ['source', prj, package, pathname2url(filename.encode(locale.getpreferredencoding(), 'replace'))], query=query)
  File "C:\Users\vandjohn\Downloads\WPy64-3771\python-3.7.7.amd64\lib\nturl2path.py", line 53, in pathname2url
    if not ':' in p:
TypeError: a bytes-like object is required, not 'str'

======================================================================
ERROR [0.346s]: testDiffRemoteNoChange (test_difffiles.TestDiffFiles)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\vandjohn\gh\osc\tests\common.py", line 160, in wrapped_test_method
    test_method(*args)
  File "C:\Users\vandjohn\gh\osc\tests\test_difffiles.py", line 195, in testDiffRemoteNoChange
    self.__check_diff(p, '', 3)
  File "C:\Users\vandjohn\gh\osc\tests\test_difffiles.py", line 301, in __check_diff
    for i in p.get_diff(revision):
  File "C:\Users\vandjohn\gh\osc\osc\core.py", line 2086, in get_diff
    get_source_file(self.apiurl, self.prjname, self.name, f.name, tmpfile, revision)
  File "C:\Users\vandjohn\gh\osc\osc\core.py", line 4733, in get_source_file
    u = makeurl(apiurl, ['source', prj, package, pathname2url(filename.encode(locale.getpreferredencoding(), 'replace'))], query=query)
  File "C:\Users\vandjohn\Downloads\WPy64-3771\python-3.7.7.amd64\lib\nturl2path.py", line 53, in pathname2url
    if not ':' in p:
TypeError: a bytes-like object is required, not 'str'

======================================================================
ERROR [0.384s]: testDiffRemoteNotExistingLocalAdded (test_difffiles.TestDiffFiles)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\vandjohn\gh\osc\tests\common.py", line 160, in wrapped_test_method
    test_method(*args)
  File "C:\Users\vandjohn\gh\osc\tests\test_difffiles.py", line 233, in testDiffRemoteNotExistingLocalAdded
    self.__check_diff(p, exp, 3)
  File "C:\Users\vandjohn\gh\osc\tests\test_difffiles.py", line 301, in __check_diff
    for i in p.get_diff(revision):
  File "C:\Users\vandjohn\gh\osc\osc\core.py", line 2086, in get_diff
    get_source_file(self.apiurl, self.prjname, self.name, f.name, tmpfile, revision)
  File "C:\Users\vandjohn\gh\osc\osc\core.py", line 4733, in get_source_file
    u = makeurl(apiurl, ['source', prj, package, pathname2url(filename.encode(locale.getpreferredencoding(), 'replace'))], query=query)
  File "C:\Users\vandjohn\Downloads\WPy64-3771\python-3.7.7.amd64\lib\nturl2path.py", line 53, in pathname2url
    if not ':' in p:
TypeError: a bytes-like object is required, not 'str'
```

**Comment by dmach** [comment]
Closing as we dropped Windows from supported operating systems (https://github.com/openSUSE/osc/pull/995)
