### ISSUE TITLE
download uses os.fchmod, not available on Windows

### ISSUE THREAD

**Issue by jayvdb** [openSUSE/osc#964]
Similar to https://github.com/openSUSE/osc/issues/948 , [`os.fchmod`](https://docs.python.org/3/library/os.html#os.fchmod) is not available on Windows.

**Comment by jayvdb** [comment]
Also 

```py
Traceback (most recent call last):
  File "C:/Users/vandjohn/Downloads/WPy64-3771/python-3.7.7.amd64/Scripts/osc-wrapper.py", line 10, in <module>
    from osc import commandline, babysitter
  File "C:\Users\vandjohn\Downloads\WPy64-3771\python-3.7.7.amd64\lib\site-packages\osc\babysitter.py", line 60, in <module>
    for sig in (signal.SIGWINCH,):
AttributeError: module 'signal' has no attribute 'SIGWINCH'
```

**Comment by dmach** [comment]
When python 2.7 support is dropped, we can switch to `os.chmod()`

From python docs:
```
os.fchmod(fd, mode)
 As of Python 3.3, this is equivalent to os.chmod(fd, mode)
```

`signal.SIGWINCH` will probably need some special handling
