### ISSUE TITLE
unsupported format character 'B' (0x42) at index 66

### ISSUE THREAD

**Issue by mcepl** [openSUSE/osc#965]
Could it be because I am building from `devel:libraries:c_c++` (notice non-alphanumeric characters `+`)?

```
libgit2@stitny$ oscb --clean
Building libgit2.spec for openSUSE_Factory/x86_64
Run source service: /usr/lib/obs/service/format_spec_file --outdir /home/matej/build/home:mcepl:branches:devel:libraries:c_c++/libgit2/tmphkl0g84r.format_spec_file.service
Run source service: /usr/lib/obs/service/source_validator --outdir /home/matej/build/home:mcepl:branches:devel:libraries:c_c++/libgit2/tmptc2onr7b.source_validator.service
- package has baselibs.conf: (new or modified)
--------------------------------------------------------------
libgit2-1_3
--------------------------------------------------------------
###ASK /home/matej/build/home:mcepl:branches:devel:libraries:c_c++/libgit2/baselibs.conf
Getting buildconfig from server and store to /home/matej/build/home:mcepl:branches:devel:libraries:c_c++/libgit2/.osc/_buildconfig-openSUSE_Factory-x86_64
Getting buildinfo from server and store to /home/matej/build/home:mcepl:branches:devel:libraries:c_c++/libgit2/.osc/_buildinfo-openSUSE_Factory-x86_64.xml
Updating cache of required packages

The build root needs packages from project 'devel:libraries:c_c++'.
Note that malicious packages can compromise the build result or even your system.
Would you like to ...
0 - quit (default)
1 - always trust packages from 'devel:libraries:c_c++'
2 - trust packages just this time
? 2
Traceback (most recent call last):
  File "/home/matej/.local/bin/osc", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/home/matej/archiv/knihovna/repos/osc/osc-wrapper.py", line 45, in <module>
    r = babysitter.run(osccli)
  File "/home/matej/archiv/knihovna/repos/osc/osc/babysitter.py", line 69, in run
    return prg.main(argv)
  File "/home/matej/archiv/knihovna/repos/osc/osc/cmdln.py", line 347, in main
    return self.cmd(args)
  File "/home/matej/archiv/knihovna/repos/osc/osc/cmdln.py", line 370, in cmd
    retval = self.onecmd(argv)
  File "/home/matej/archiv/knihovna/repos/osc/osc/cmdln.py", line 504, in onecmd
    return self._dispatch_cmd(handler, argv)
  File "/home/matej/archiv/knihovna/repos/osc/osc/cmdln.py", line 1235, in _dispatch_cmd
    return handler(argv[0], opts, *args)
  File "/home/matej/archiv/knihovna/repos/osc/osc/commandline.py", line 6733, in do_build
    return osc.build.main(self.get_api_url(), opts, args)
  File "/home/matej/archiv/knihovna/repos/osc/osc/build.py", line 1074, in main
    fetcher.run(bi)
  File "/home/matej/archiv/knihovna/repos/osc/osc/fetch.py", line 210, in run
    i.makeurls(self.cachedir, urllist)
  File "/home/matej/archiv/knihovna/repos/osc/osc/build.py", line 291, in makeurls
    self.urllist.append(url % self.mp)
ValueError: unsupported format character 'B' (0x42) at index 66
libgit2@stitny$
```

**Comment by marcus-h** [comment]
On 2021-10-20 01:36:48 -0700, Matěj Cepl wrote:
> Could it be because I am building from `devel:libraries:c_c++` (notice non-alphanumeric characters `+`)?

The buildinfo provides a download url which contains the substring
"%2B" (encoding of the +) - this interferes with osc's %-formatting.
Probably running a .replace('%', '%%') on the raw url should do the
trick. But I have to think about it again.

> ***@***.***$ oscb --clean

...

>   File "/home/matej/archiv/knihovna/repos/osc/osc/fetch.py", line 210, in run
>     i.makeurls(self.cachedir, urllist)
>   File "/home/matej/archiv/knihovna/repos/osc/osc/build.py", line 291, in makeurls
>     self.urllist.append(url % self.mp)
> ValueError: unsupported format character 'B' (0x42) at index 66
> ***@***.***$
