### ISSUE TITLE
Resize of terminal while osc getbinaries makes osc crash

### ISSUE THREAD

**Issue by zaitor** [openSUSE/osc#972]
Resize of (gnome)-terminal window, while a osc getbinaries is in progress, kills osc/download

```
user@world:~> osc getbinaries --debug --destdir=/some/random/writeable/dir/ openSUSE:Factory:Staging:J/kernel-default/standard/x86_64
_buildenv: 100%|#####################################################################| Time: 0:00:00
_statistics: 100%|###################################################################| Time: 0:00:00
kernel-default-5.15.2-1.2.x86_64.rpm: 100%|##########################################| Time: 0:00:19
Traceback (most recent call last):2.x86_64.rpm:   2%|                                | ETA:  0:03:22
  File "/usr/bin/osc", line 45, in <module>
    r = babysitter.run(osccli)
  File "/usr/lib/python3.8/site-packages/osc/babysitter.py", line 69, in run
    return prg.main(argv)
  File "/usr/lib/python3.8/site-packages/osc/cmdln.py", line 347, in main
    return self.cmd(args)
  File "/usr/lib/python3.8/site-packages/osc/cmdln.py", line 370, in cmd
    retval = self.onecmd(argv)
  File "/usr/lib/python3.8/site-packages/osc/cmdln.py", line 504, in onecmd
    return self._dispatch_cmd(handler, argv)
  File "/usr/lib/python3.8/site-packages/osc/cmdln.py", line 1235, in _dispatch_cmd
    return handler(argv[0], opts, *args)
  File "/usr/lib/python3.8/site-packages/osc/commandline.py", line 7519, in do_getbinaries
    get_binary_file(apiurl,
  File "/usr/lib/python3.8/site-packages/osc/core.py", line 4714, in get_binary_file
    download(u, target_filename, progress_obj, target_mtime)
  File "/usr/lib/python3.8/site-packages/osc/core.py", line 4672, in download
    for buf in streamfile(url, http_GET, BUFSIZE, progress_obj=progress_obj):
  File "/usr/lib/python3.8/site-packages/osc/core.py", line 6123, in streamfile
    data = xread(bufsize)
  File "/usr/lib64/python3.8/tempfile.py", line 473, in func_wrapper
    return func(*args, **kwargs)
  File "/usr/lib64/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib64/python3.8/http/client.py", line 503, in readinto
    n = self.fp.readinto(b)
  File "/usr/lib64/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib64/python3.8/site-packages/M2Crypto/SSL/Connection.py", line 406, in recv_into
    buflen = len(buff_bytes)
TypeError: object of type 'NoneType' has no len()

```

**Comment by marcus-h** [comment]
On 2021-11-16 13:43:58 +0000, Bjørn Lie wrote:
> Resize of (gnome)-terminal window, while a osc getbinaries is in progress, kills osc/download
>
Which osc version are you using?

> ```
> ***@***.***:~> osc getbinaries --debug --destdir=/some/random/writeable/dir/ openSUSE:Factory:Staging:J/kernel-default/standard/x86_64

<SNIP>

>   File "/usr/lib64/python3.8/socket.py", line 669, in readinto
>     return self._sock.recv_into(b)
>   File "/usr/lib64/python3.8/site-packages/M2Crypto/SSL/Connection.py", line 406, in recv_into
>     buflen = len(buff_bytes)
> TypeError: object of type 'NoneType' has no len()
>
Hmm m2crypto should/could probably handle this case more gracefully.
However, this is probably caused by some signal that interrupts a
read(...) syscall.

**Comment by zaitor** [comment]
> Which osc version are you using?

i+ | osc  | package | 0.174.0-1.2 | noarch | openSUSE-Tumbleweed-Oss

**Comment by dmach** [comment]
For the record, there was an attempt to fix this in https://github.com/openSUSE/osc/issues/584

**Comment by dmach** [comment]
The linked PR https://github.com/openSUSE/osc/pull/987 workarounds the crash by avoiding setting the SIGWINCH signal handler in progressbar's code.
A proper fix would be restarting the interrupted syscalls in the right place(s), but that's way beyond the scope of a reasonable fix in osc :)

**Comment by mcepl** [comment]
This is back again, living as if nothing has changed.

**Comment by marcus-h** [comment]
On 2022-02-22 05:53:50 -0800, Matěj Cepl wrote:
> This is back again, living as if nothing has changed.
>
Hmm are you really sure that you are using the "correct" branch?
(I'm just asking because you "suddenly" start to run into two issues,
which should have been fixed.)

**Comment by mcepl** [comment]
Apparently I need to remove my openSUSE package first.
