### ISSUE TITLE
Type error on any osc call

### ISSUE THREAD

**Issue by saber716rus** [openSUSE/osc#985]
nikolanp@localhost ~> osc ls
Traceback (most recent call last):
  File "/usr/bin/osc", line 41, in <module>
    r = babysitter.run(osccli)
  File "/usr/lib/python3.6/site-packages/osc/babysitter.py", line 69, in run
    return prg.main(argv)
  File "/usr/lib/python3.6/site-packages/osc/cmdln.py", line 339, in main
    self.postoptparse()
  File "/usr/lib/python3.6/site-packages/osc/commandline.py", line 146, in postoptparse
    override_verbose = self.options.verbose)
  File "/usr/lib/python3.6/site-packages/osc/conf.py", line 845, in get_config
    cp = get_configParser(conffile)
  File "/usr/lib/python3.6/site-packages/osc/conf.py", line 638, in get_configParser
    get_configParser.cp.read(conffile)
  File "/usr/lib64/python3.6/configparser.py", line 697, in read
    self._read(fp, filename)
  File "/usr/lib/python3.6/site-packages/osc/OscConfigParser.py", line 281, in _read
    raise configparser.MissingSectionHeaderError(fpname, lineno, line)
configparser.MissingSectionHeaderError: File contains no section headers.
file: '/home/nikolanp/.oscrc', line: 1
'su-wrapper = sudo\n'
nikolanp@localhost ~> osc build --clean
Traceback (most recent call last):
  File "/usr/bin/osc", line 41, in <module>
    r = babysitter.run(osccli)
  File "/usr/lib/python3.6/site-packages/osc/babysitter.py", line 69, in run
    return prg.main(argv)
  File "/usr/lib/python3.6/site-packages/osc/cmdln.py", line 339, in main
    self.postoptparse()
  File "/usr/lib/python3.6/site-packages/osc/commandline.py", line 146, in postoptparse
    override_verbose = self.options.verbose)
  File "/usr/lib/python3.6/site-packages/osc/conf.py", line 845, in get_config
    cp = get_configParser(conffile)
  File "/usr/lib/python3.6/site-packages/osc/conf.py", line 638, in get_configParser
    get_configParser.cp.read(conffile)
  File "/usr/lib64/python3.6/configparser.py", line 697, in read
    self._read(fp, filename)
  File "/usr/lib/python3.6/site-packages/osc/OscConfigParser.py", line 281, in _read
    raise configparser.MissingSectionHeaderError(fpname, lineno, line)
configparser.MissingSectionHeaderError: File contains no section headers.
file: '/home/nikolanp/.oscrc', line: 1
'su-wrapper = sudo\n'
nikolanp@localhost ~> sudo osc build --clean
Error: '/home/nikolanp' is not an osc project dir or working copy
nikolanp@localhost ~> osc ls
Traceback (most recent call last):
  File "/usr/bin/osc", line 41, in <module>
    r = babysitter.run(osccli)
  File "/usr/lib/python3.6/site-packages/osc/babysitter.py", line 69, in run
    return prg.main(argv)
  File "/usr/lib/python3.6/site-packages/osc/cmdln.py", line 339, in main
    self.postoptparse()
  File "/usr/lib/python3.6/site-packages/osc/commandline.py", line 146, in postoptparse
    override_verbose = self.options.verbose)
  File "/usr/lib/python3.6/site-packages/osc/conf.py", line 845, in get_config
    cp = get_configParser(conffile)
  File "/usr/lib/python3.6/site-packages/osc/conf.py", line 638, in get_configParser
    get_configParser.cp.read(conffile)
  File "/usr/lib64/python3.6/configparser.py", line 697, in read
    self._read(fp, filename)
  File "/usr/lib/python3.6/site-packages/osc/OscConfigParser.py", line 281, in _read
    raise configparser.MissingSectionHeaderError(fpname, lineno, line)
configparser.MissingSectionHeaderError: File contains no section headers.
file: '/home/nikolanp/.oscrc', line: 1
'su-wrapper = sudo\n'
nikolanp@localhost ~>

**Comment by marcus-h** [comment]
On 2021-12-19 01:45:01 -0800, Nikolay wrote:
> ***@***.*** ~> osc ls
> Traceback (most recent call last):
>   File "/usr/bin/osc", line 41, in <module>
>     r = babysitter.run(osccli)
>   File "/usr/lib/python3.6/site-packages/osc/babysitter.py", line 69, in run
>     return prg.main(argv)
>   File "/usr/lib/python3.6/site-packages/osc/cmdln.py", line 339, in main
>     self.postoptparse()
>   File "/usr/lib/python3.6/site-packages/osc/commandline.py", line 146, in postoptparse
>     override_verbose = self.options.verbose)
>   File "/usr/lib/python3.6/site-packages/osc/conf.py", line 845, in get_config
>     cp = get_configParser(conffile)
>   File "/usr/lib/python3.6/site-packages/osc/conf.py", line 638, in get_configParser
>     get_configParser.cp.read(conffile)
>   File "/usr/lib64/python3.6/configparser.py", line 697, in read
>     self._read(fp, filename)
>   File "/usr/lib/python3.6/site-packages/osc/OscConfigParser.py", line 281, in _read
>     raise configparser.MissingSectionHeaderError(fpname, lineno, line)
> configparser.MissingSectionHeaderError: File contains no section headers.
> file: '/home/nikolanp/.oscrc', line: 1
> 'su-wrapper = sudo\n'

It seems that your /home/nikolanp/.oscrc misses a [general] section at
the beginning of the file. From the excerpt, it should probably look
like this

[general]
su-wrapper = ...
...

Anyway, your config file is "broken". Either you manually fix it (as
described above) or you (re)move it and let osc create a new one (this
one is then probably stored in ~/.config/osc/oscrc).

> ***@***.*** ~> sudo osc build --clean
> Error: '/home/nikolanp' is not an osc project dir or working copy

This "works" because it seems that root has a valid /root/.oscrc or
/root/.config/osc/oscrc file.

**Comment by saber716rus** [comment]
The error just comes out. After all, I did everything according to your instructions. https://en.opensuse.org/openSUSE:Build_Service_Tutorial
[oscrc.zip](https://github.com/openSUSE/osc/files/7777068/oscrc.zip)

**Comment by saber716rus** [comment]
and there is no such thing in /root. root@localhost ~# cd /root/
root@localhost ~# ls
bin/  inst-sys/

**Comment by saber716rus** [comment]
This is the solution, but then correct the instructions. https://ru.opensuse.org/openSUSE:Руководство_по_использованию_службы_сборки
Without this [general] line, osc does not work.

**Comment by marcus-h** [comment]
On 2021-12-26 06:06:26 -0800, Nikolay wrote:
> The error just comes out. After all, I did everything according to your instructions. https://en.opensuse.org/openSUSE:Build_Service_Tutorial
> [oscrc.zip](https://github.com/openSUSE/osc/files/7777068/oscrc.zip)
>
The sole content of the .oscrc file is "su-wrapper = sudo\n\n". This
is an invalid oscrc configuration file. Just remove your ~/.oscrc
file. Afterwards, osc will create a new ~/.config/osc/oscrc file (unless
this file already exists).

**Comment by marcus-h** [comment]
On 2021-12-26 06:09:48 -0800, Nikolay wrote:
> and there is no such thing in /root. ***@***.*** ~# cd /root/
> ***@***.*** ~# ls
> bin/  inst-sys/
>
Try "ls -a" to also list files that start with a dot.
